"""Version-masked ROM identity (owner ruling 2026-10-02: "Version-masked identity").

Every SLink companion prints "SoulLink <version>" on its main menu from a FIXED-WIDTH field (FIELD bytes: the text,
its terminator, then padding), so stamping a release version changes only the bytes of that field -- and, on the Game
Boy, the cartridge's global checksum at 0x14E-0x14F, which sums every other byte. The canonical identity of a build
is the sha1 of the ROM with those bytes zeroed. Anything that qualifies a build (receipts, the signed G4 fingerprints,
the evidence a release gate reads) is keyed on the canonical identity, so a stamp never re-qualifies anything;
anything that must name the exact cartridge on disk (runtime admission rows, the UPS, the web patcher's md5) keeps
the exact hash and is regenerated by the stamp.

This module is toolchain-free: the builders, the stamp tool and the validators all import it.
"""
from __future__ import annotations

import hashlib

FIELD = 20                       # bytes reserved for "SoulLink <version>" + terminator + padding, in every family
PREFIX = 9                       # len("SoulLink "): one byte per character in every charmap, and part of the canonical identity
GB_CHECKSUM = (0x14E, 0x14F)     # Game Boy global checksum: the one place outside the field a version stamp reaches
VERSION_MAX = 10                 # "v0.3.0-dev"; "SoulLink " + 10 characters + terminator <= FIELD


def _spans(rom_len: int, slots, gb: bool) -> list[tuple[int, int]]:
    """The byte ranges the canonical identity zeroes. A slot of exactly FIELD bytes names a version FIELD and only its version part
    (everything after the PREFIX) is masked: the "SoulLink " wordmark stays in the identity, so a wordmark or charmap change is a
    code change, never a stamp. Any other slot (the Gen 2 Stadium table) is masked whole."""
    spans = []
    for slot in slots:
        off, length = (slot["offset"], slot["length"]) if isinstance(slot, dict) else slot
        if off < 0 or length <= 0 or off + length > rom_len:
            raise ValueError(f"version slot {off:#x}+{length} is outside the {rom_len}-byte ROM")
        if length == FIELD:
            off, length = off + PREFIX, FIELD - PREFIX
        spans.append((off, off + length))
    if gb:
        spans.append((GB_CHECKSUM[0], GB_CHECKSUM[1] + 1))
    spans.sort()
    for (_, end), (start, _) in zip(spans, spans[1:], strict=False):
        if start < end:
            raise ValueError("version slots overlap each other or the checksum")
    return spans


def canonical_bytes(rom: bytes, slots, *, gb: bool = False) -> bytes:
    """`rom` with every version slot (and, for a Game Boy ROM, the global checksum) zeroed."""
    out = bytearray(rom)
    for start, end in _spans(len(rom), slots, gb):
        out[start:end] = bytes(end - start)
    return bytes(out)


def canonical_sha1(rom: bytes, slots, *, gb: bool = False) -> str:
    return hashlib.sha1(canonical_bytes(rom, slots, gb=gb)).hexdigest()


def canonical_sha256(blob: bytes, slots) -> str:
    """For a payload that is not a whole ROM (the Gen 3 native payload digest)."""
    return hashlib.sha256(canonical_bytes(blob, slots)).hexdigest()


def assert_version_only_difference(a: bytes, b: bytes, slots, *, gb: bool = False) -> None:
    """Raise unless `a` and `b` are the same build up to the version field (the stamp's one guarantee)."""
    if len(a) != len(b):
        raise ValueError(f"builds differ in size: {len(a)} vs {len(b)}")
    if canonical_bytes(a, slots, gb=gb) != canonical_bytes(b, slots, gb=gb):
        spans = _spans(len(a), slots, gb)
        outside = [i for i in range(len(a)) if a[i] != b[i] and not any(s <= i < e for s, e in spans)]
        raise ValueError(f"the builds differ outside the version field, first at {outside[0]:#x} ({len(outside)} bytes)")


def slot_from_sym(sym_text: str, label: str, length: int = FIELD) -> dict:
    """The version slot of a Game Boy build, from its rgbds .sym text: file offset of `label` (bank:addr)."""
    for line in sym_text.splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[1] == label and ":" in parts[0]:
            bank, addr = (int(x, 16) for x in parts[0].split(":"))
            if bank and addr < 0x4000:
                raise ValueError(f"{label} is at {parts[0]}: a banked label below $4000 has no ROM offset")
            offset = addr if bank == 0 else bank * 0x4000 + (addr - 0x4000)
            return {"offset": offset, "length": length}
    raise KeyError(f"{label} is not in the symbol file")


def slot_from_text(blob: bytes, field: bytes) -> dict:
    """The version slot of a payload, found by its own (unique) field bytes."""
    at = blob.find(field)
    if at < 0 or blob.find(field, at + 1) >= 0:
        raise ValueError("the version field must occur exactly once in the payload")
    return {"offset": at, "length": len(field)}
