"""GENERATED by tools/gen_gen1_title.py -- do not edit. The SoulLink logo for the Gen 1 title screen:
2bpp tiles and the two rows of tile ids that place them."""

FIRST_ID = 0x6a
TILE_COUNT = 18
SMALL = {'v': b'\x00\x00\x11\x11\x11\n\x04', 'd': b'\x01\x01\r\x13\x11\x13\r', 'e': b'\x00\x00\x0e\x11\x1f\x10\x0e', '0': b'\x0e\x11\x13\x15\x19\x11\x0e', '1': b'\x04\x0c\x04\x04\x04\x04\x0e', '2': b'\x0e\x11\x01\x02\x04\x08\x1f', '3': b'\x1e\x01\x01\x0e\x01\x01\x1e', '4': b'\x02\x06\n\x12\x1f\x02\x02', '5': b'\x1f\x10\x1e\x01\x01\x11\x0e', '6': b'\x06\x08\x10\x1e\x11\x11\x0e', '7': b'\x1f\x01\x02\x04\x08\x08\x08', '8': b'\x0e\x11\x11\x0e\x11\x11\x0e', '9': b'\x0e\x11\x11\x0f\x01\x02\x0c', '.': b'\x00\x00\x00\x00\x00\x0c\x0c', '-': b'\x00\x00\x00\x1f\x00\x00\x00'}
ROW0 = bytes.fromhex('6a6b6c6d6e6f707172')
ROW1 = bytes.fromhex('737475767778797a7b')
TILES = bytes.fromhex(
    "000007070f0c0f090f090f090f0c07070000e0e0f030f098f3fbe7fef734f79c0000000000000000f3f3fb1afbcefbce"
    "0000010101010101fdfdfd67fd67fd670000efefef39ef39ef39ef39ef39ef3900000f0f0f890f890f8f0f890f890f89"
    "00000000008000807fff7fc17fcc7fcc00003c3c3c263f273f26bfa4bfe1bfe1000000000000c0c0c060c0e080e080c0"
    "0f0f0f090f0c07070003000000000000f79cf79cf73ee3fb00f1000000000000fbcefbcefb1ff1fd00f8000000000000"
    "fd67fd67fd07fdff00fe000000000000ef39ef38ef38efff00f7000000000000efe9ef39ef39efff00f7000000000000"
    "7fcc7fcc7fcc7fff00bf000000000000bfe4bfe6bfe6bfff00df000000000000c0c0c060c060c0e000e0000000000000"
)
