"""GENERATED by tools/gen_gen1_title.py -- do not edit. The SoulLink logo for the Gen 1 title screen:
2bpp tiles and the two rows of tile ids that place them."""

FIRST_ID = 0x6a
TILE_COUNT = 18
ROW0 = bytes.fromhex('6a6b6c6d6e6f707172')
ROW1 = bytes.fromhex('737475767778797a7b')
TILES = bytes.fromhex(
    "0000000007070f0c0f090f090f090f0c00000000e0e0f030f098f3fbe7fef73400000000000000000000f3f3fb1afbce"
    "00000000010101010101fdfdfd67fd6700000000efefef39ef39ef39ef39ef39000000000f0f0f890f890f8f0f890f89"
    "000000000000008000807fff7fc17fcc000000003c3c3c263f273f26bfa4bfe10000000000000000c0c0c060c0e080e0"
    "07070f0f0f090f0c0707000300000000f79cf79cf79cf73ee3fb00f100000000fbcefbcefbcefb1ff1fd00f800000000"
    "fd67fd67fd67fd07fdff00fe00000000ef39ef39ef38ef38efff00f7000000000f89efe9ef39ef39efff00f700000000"
    "7fcc7fcc7fcc7fcc7fff00bf00000000bfe1bfe4bfe6bfe6bfff00df0000000080c0c0c0c060c060c0e000e000000000"
)
