"""Polished Crystal v3.2.3 rules/presentation adapter (game_id gen2_polished, one title).

Polished is its OWN family, like pureRGB is for Gen 1: same Game Boy engine lineage as Crystal, but a
different pack (data/games/polished_crystal/, generated by tools/gen_polished_pack.py), 9-bit species
with forms, a different party_struct middle (server/adapters/polished_codec.py), 20 newbox PC boxes, and
moved trainer classes (RIVAL0/1/2 + LYRA1/2). It never pairs with a vanilla Gen 2 cartridge.

It subclasses Gen2GSCAdapter for the methods whose logic is pack-shape agnostic (gift/legend area
namespacing, area display names, move data, type names, artifact kinds, native-UI capabilities, badges,
status tokens) and overrides everything bound to the vanilla pack or to species 1..251. The parent's
__init__ is never run: this adapter loads its own generated Polished packs instead of the vanilla layout.

SOURCE: polishedcrystal@3fa43192379df5c3e7b09a08e4d5d79af4f02f42 (tag v3.2.3, ROM sha1 6930b48a…,
data/polished_sources.lock.json); docs/polished/RAM.md, docs/polished/NEWBOX.md.
"""
from __future__ import annotations

import copy
import hashlib
import json
import pathlib
import re
from functools import cache
from pathlib import Path

from . import polished_codec, polished_rom_scan
from .base import companion_required_reason
from .gen2_gsc import _AREA, _STATIC, Gen2GSCAdapter, _display

_ROOT = Path(__file__).resolve().parents[2]
_DATA = _ROOT / "data" / "games" / "polished_crystal"
TITLE = "polished_crystal"
# P3: the rom_type the Polished Lua client sends in its hello (server/adapters/__init__.py rows).
_ROM_TYPES = {"polished_crystal": TITLE}
_COMMIT = "3fa43192379df5c3e7b09a08e4d5d79af4f02f42"
_SPLIT = {"Physical": 0, "Special": 1, "Status": 2}
_KEY = re.compile(r"([0-9A-F]{6}):([0-9A-F]{4}):([0-9A-F]{3}):([0-9A-F]{2})")
_GENDERLESS, _ALL_FEMALE, _ALL_MALE = 15, 8, 0   # GENDER_UNKNOWN / GENDER_F100 / GENDER_F0, pokemon_data_constants.asm:39-49
# P8: "rand_overlay" is the companion overlay randomized by the Manager (fork patch 0018 run on the overlay);
# "clean" (the release) stays refused at hello by companion_refusal (patch-first).
_KINDS = ("clean", "overlay", "rand_overlay")
_COMPANION = ("overlay", "rand_overlay")
_TIME_INDEX = {"morning": 0, "day": 1, "night": 2, "all": 0}


def _type_display(name):
    """The one display name for a type id, whichever row declared it (species, variant or move).

    `Unknown_T` is the pack's marker for a type with no name and must render as '???' in BOTH
    loops: move_data() has always rewritten it for moves, so a species row typed Unknown_T used to
    pin type_name(id) to 'Unknown_T' while the same id showed '???' on the move side. The parent
    Gen2GSCAdapter requires the two loops to agree ('conflicting type names',
    server/adapters/gen2_gsc.py:181), so Polished routes both through this function.
    """
    name = name.removesuffix("_TYPE")
    return "???" if name == "Unknown_T" else _display(name)


def _require(condition, message):
    if not condition:
        raise ValueError(message)


def _integer(value, low, high):
    return type(value) is int and low <= value <= high


FORMS_INDEX = pathlib.Path(__file__).resolve().parents[2] / "data" / "games" / "polished_crystal" / "forms_index.json"


def _json(name):
    try:
        value = json.loads((_DATA / f"{name}.json").read_text("utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"unavailable or invalid Polished pack: {name}.json") from error
    _require(isinstance(value, dict), f"pack must be an object: {name}.json")
    return value


@cache
def _panel_line_max() -> int:
    """Glyphs per ROM panel line, from the pinned profile's overlay.panel block (not a constant here)."""
    try:
        line_max = _json("profile")["titles"]["polished"]["overlay"]["panel"]["line_max"]
    except (KeyError, TypeError) as error:
        raise ValueError("Polished profile has no overlay.panel.line_max") from error
    _require(_integer(line_max, 1, 20), "Polished panel line_max must be 1..20")
    return line_max


@cache
def _rom_sha1() -> str:
    with open(_ROOT / "data" / "polished_sources.lock.json", encoding="utf-8") as fh:
        return json.load(fh)["outputs"]["polishedcrystal"]["sha1"]


@cache
def _companion_abi() -> int | None:
    """The mailbox ABI the companion was BUILT against: abi_version of data/polished/overlay_provenance.json
    (written by tools/build_polished_companion.py), as Gen 2 pins its profile.json overlay.abi -- an ABI bump
    without a rebuilt companion then refuses rather than admits. None when unreadable or not a positive
    integer, which refuses every hello (fail closed)."""
    try:
        with open(_ROOT / "data" / "polished" / "overlay_provenance.json", encoding="utf-8") as fh:
            abi = json.load(fh)["abi_version"]
    except (OSError, ValueError, KeyError, TypeError):
        return None
    return abi if type(abi) is int and abi > 0 else None


def scan_randomized(rom: bytes) -> dict:
    """A randomized companion cartridge's own tables, read unpinned at the overlay's offsets (UPR moves no
    table): wild, fishing, trees, contest, the species/level at every resolved script site (starters = the
    three Elm's Lab givepokes, in UPR's order) and the NPC trades. Roamers are not read: the 0018 handler has
    no roamer writer, so they are the overlay's own. Raises on anything that does not decode."""
    reader = polished_rom_scan.Rom(rom, pinned=False)
    mons = reader.scripted_mons()
    return {"title": TITLE, "wild": reader.wild(), "fishing": reader.fishing(), "trees": reader.trees(),
            "contest": reader.contest(),
            "starters": [m for m in mons if m["source"] in polished_rom_scan.STARTER_SOURCES],
            "statics": [m for m in mons if m["source"] not in polished_rom_scan.STARTER_SOURCES],
            "trades": reader.npc_trades()}


@cache
def _pack_forms() -> frozenset:
    """Every (species, form) the pack names: the 46 variant and 56 cosmetic forms (species_index.json)."""
    return frozenset((row["species"], row["form"]) for row in _json("species_index")["forms"])


def _adopt_mon(row, species, form, label):
    own = (row.get("species"), row.get("form", 1))
    _require(form <= 1 or (species, form) in _pack_forms() or (species, form) == own,
             f"{label}: species {species} has no form {form}")
    if not (form <= 1 and own[1] <= 1):
        row["form"] = form
    row["species"] = species


def _adopt_slots(rows, decoded, label, badges):
    """Overlay decoded (species, form, raw level) triples onto the pack's slot dicts, in place, keeping the
    pack's own level encoding. UPR rewrites species (variant forms included, owner ruling 2026-10-04) and plain
    levels only, never a LEVEL_FROM_BADGES byte. A decoded form is adopted when it exists for that species
    (NO_FORM / PLAIN_FORM, a pack variant or cosmetic form, or the slot's own spelling); any other pair means
    the decode is misaligned -> refused. NO_FORM and PLAIN_FORM are the same mon, so the pack's spelling stays."""
    _require(len(rows) == len(decoded), f"{label}: slot count differs from the pack")
    for row, (species, form, level) in zip(rows, decoded, strict=True):
        _adopt_mon(row, species, form, label)
        if "level_raw" in row:                    # wild rows: level None + raw byte + offset from ``badges``
            row.update(level_raw=level, level_from_badges_offset=level - badges)
        else:
            row["level"] = level


def _adopt_encounters(pack: dict, tables: dict) -> dict:
    """The pack's encounter tables (maps, times, thresholds, policy) with this cartridge's species and levels."""
    out = copy.deepcopy(pack)
    badges = out["wild"]["level_from_badges"]
    rows = {(table, *row["map"]): row for table, decoded in tables["wild"].items() for row in decoded}
    seen = set()
    for kind in ("grass", "water"):
        for row in out["wild"][kind]:
            key = (row["table"].removesuffix("WildMons"), row["map_group"], row["map_number"])
            source = rows.get(key)
            _require(source is not None, f"wild {key}: not on the cartridge")
            seen.add(key)
            n, i = len(row["slots"]), _TIME_INDEX[row["time"]]
            row["rate"] = source["rates"][i]
            _adopt_slots(row["slots"], [(sp, f, lv) for lv, sp, f in source["slots"][i * n:(i + 1) * n]], f"wild {key}", badges)
    _require(seen == set(rows), "the cartridge has wild maps the pack does not")
    groups = out["fishing"]["groups"]
    _require(len(groups) == len(tables["fishing"]), "fish group count differs")
    for group, decoded in zip(groups, tables["fishing"], strict=True):
        for rod, entries in zip(("old", "good", "super"), decoded["rods"], strict=True):
            _require([e["threshold"] for e in group[rod]] == [e[0] for e in entries], "fish thresholds differ")
            _adopt_slots(group[rod], [(sp, f, lv) for _c, sp, f, lv in entries], f"fish group {group['group_id']}", badges)
    sets = out["tree"]["sets"]
    _require(len(sets) == len(tables["trees"]), "tree set count differs")
    for tree, lists in zip(sets, tables["trees"], strict=True):
        _require(len(lists) == sum(bool(tree.get(r)) for r in ("common", "rare")), "tree list count differs")
        for rarity, entries in zip(("common", "rare"), lists, strict=False):
            _require([e["weight"] for e in tree[rarity]] == [e[0] for e in entries], "tree weights differ")
            _adopt_slots(tree[rarity], [(sp, f, lv) for _c, sp, f, lv in entries], f"tree set {tree['set_id']}", badges)
    slots = out["contest"]["slots"]
    _require([s["weight"] for s in slots] == [r[0] for r in tables["contest"]], "contest weights differ")
    for slot, (_c, species, form, low, high) in zip(slots, tables["contest"], strict=True):
        _adopt_mon(slot, species, form, "contest")
        slot.update(min_level=low, max_level=high)
    return out


def _form_label(row):
    """'ALOLAN_FORM' -> 'Alolan', 'GYARADOS_RED_FORM' -> 'Red', 'TAUROS_PALDEAN_FIRE_FORM' -> 'Paldean Fire'."""
    label = row["form_const"].removesuffix("_FORM").removeprefix(row["species_const"] + "_")
    return label.replace("_", " ").title()

# ROM display names the damage calculator spells differently. Kept byte-identical to
# tools/gen_polished_calc.py's SPECIES_FIXUPS, which builds calc/src/calc/data/polished.js's
# species keys from it: the two must agree or a species silently misses the calc's toID() lookup
# and falls back to the vanilla gen 3 dex. tests/unit/test_gen_polished_calc.py asserts they agree.
CALC_SPECIES_FIXUPS = {"Nidoran♀": "Nidoran-F", "Nidoran♂": "Nidoran-M"}

# The calc's own stat ids -> the pack's base_stats keys.
_STAT_KEYS = (("hp", "hp"), ("atk", "attack"), ("df", "defense"),
              ("spa", "special_attack"), ("spd", "special_defense"), ("spe", "speed"))


def _calc_species_name(name):
    return CALC_SPECIES_FIXUPS.get(name, name)


def _crystal_stat(base, dv, ev, level, *, hp=False):
    """Polished's own stat arithmetic (engine/pokemon/mon_stats.asm CalcPkmnStatC, lines 763-836).

    de = (base + DV) * 2 + 1 + floor(EV / 4);  stat = floor(de * level / 100) + STAT_MIN_NORMAL,
    or + level + STAT_MIN_HP for HP (constants/battle_constants.asm:81-82). This is pokecrystal's
    formula with EVs in the stat-exp slot -- NOT the modern 2*base + IV one the calc uses at gen 3,
    which is why calc_stats() hands the engine IV = 2*DV + 1.
    """
    quotient = ((base + dv) * 2 + 1 + ev // 4) * level // 100
    return quotient + level + 10 if hp else quotient + 5


class Gen2PolishedAdapter(Gen2GSCAdapter):
    """Game facts only for Polished Crystal; constructing it cannot activate a runtime route."""

    def _record_type(self, number, display):
        """Register one type id's display name, refusing a second, different name for it.

        Mirrors Gen2GSCAdapter's 'conflicting type names' rule (server/adapters/gen2_gsc.py:181);
        setdefault() would keep the first writer silently and let a species row and a move row
        disagree about the same id.
        """
        existing = self._types.get(number)
        _require(existing is None or existing == display,
                 f"conflicting type names for id {number}: {existing!r} and {display!r}")
        self._types[number] = display

    def __init__(self, title: str | None = None, *, rom_type: str | None = None,
                 is_rr: bool = False, artifact_kind: str | None = None, data_root: Path | None = None):
        if rom_type is not None:
            _require(rom_type in _ROM_TYPES, f"no Polished title for rom_type {rom_type!r}")
        _require(title in (None, TITLE) and not is_rr, "Polished Crystal has one title and no RR layout")
        _require(data_root is None, "the Polished pack has one fixed location")
        self.title = TITLE
        species = _json("species_index")
        self.source = copy.deepcopy(species.get("source", {}))
        _require(self.source.get("commit") == _COMMIT and self.source.get("rom_sha1") == _rom_sha1()
                 and self.source.get("evidence_level") == "SOURCE", "Polished pack source mismatch")

        def load(name, schema, data=None):
            data = data or _json(name)
            _require(data.get("schema") == schema, f"{name}: unsupported pack schema")
            _require(data.get("source") == self.source and data.get("title") == TITLE,
                     f"{name}: source/title provenance mismatch")
            return data

        load("species_index", "polished-species-v1", species)
        # Species ids are the 9-bit wire id: 1..254, 257..291 (255 = EGG, 256 invalid, species_index.json).
        self._species = {int(k): v for k, v in species["species"].items()}
        _require(len(self._species) == species["constants"]["NUM_POKEMON"]
                 and not {0, 255, 256} & self._species.keys() and max(self._species) < 0x200,
                 "species pack ids invalid")
        # (species, form) -> variant row. Variant forms carry their own stats/types (Alolan etc.);
        # cosmetic forms (Unown letters, Magikarp patterns) are the base species in every rule.
        self._variants = {(row["species"], row["form"]): row for row in species["forms"] if row["kind"] == "variant"}
        # BaseData record index -> the same variant row. A variant form's EFFECTIVE species id IS its record
        # index (forms_index.json, tools/gen_polished_forms.py), which is what keeps server/state.py unchanged.
        self._variant_by_record = {}
        if FORMS_INDEX.exists():
            forms_index = json.loads(FORMS_INDEX.read_text(encoding="utf-8"))
            for row in forms_index["variant_forms"]:
                if row.get("kind") != "variant":
                    continue
                base = next((s for s in self._variants.values()
                             if s["species"] == row["species_id"]), None)
                merged = dict(base or {})
                merged.update({"species": row["species_id"], "form": row["form_id"],
                               "record_index": row["record_index"],
                               "form_const": row["form_constant"],
                               "evolves_to": row.get("evolves_to", [])})
                self._variant_by_record[row["record_index"]] = merged
        self._types = {}
        for row in [*self._species.values(), *self._variants.values()]:
            _require(isinstance(row.get("name"), str) and _integer(row.get("gender_ratio"), 0, 15),
                     "invalid species name or gender ratio")
            for number, name in zip(row["type_ids"], row["types"], strict=True):
                _require(_integer(number, 0, 31), "invalid type id")
                self._record_type(number, _type_display(name))
        evolution = load("evolutions", "polished-evolutions-v1")
        self._families = {int(k): v for k, v in evolution["family"].items()}
        self._variant_families_cache = None
        _require(self._families.keys() == self._species.keys()
                 and all(self._families[v] == v for v in self._families.values()), "invalid evolution families")
        items = load("items", "polished-items-v1")
        self._items = {int(k): v for k, v in items["items"].items()}
        _require(set(self._items) == set(range(1, 255)), "incomplete item inventory")
        moves = load("moves", "polished-moves-v1")["moves"]
        self._moves = {row["id"]: row for row in moves}
        _require(set(self._moves) == set(range(1, 256)), "incomplete/duplicate move pack")
        for row in moves:
            _require(row.get("split") in _SPLIT and _integer(row.get("type_id"), 0, 31), "invalid move type or split")
            self._record_type(row["type_id"], _type_display(row["type"]))

        # Areas: Polished's pack has no area_map, so the area id is derived the way
        # tools/gen_gen2_area_map.py derives vanilla's -- the map's landmark constant, lowercased, with the
        # Bug-Catching Contest map split out. P3: the Lua client must send the same ids.
        names = load("map_names", "polished-map-names-v1")
        fish = {f"{r['map_group']}:{r['map_number']}": r["group_id"]
                for r in _json("encounter_tables")["fishing"]["map_groups"]}
        self._areas = {}
        self._area_names = {}
        for key, row in names["maps"].items():
            area_id = row["landmark_const"].lower()
            if row["constant"] == "NATIONAL_PARK_BUG_CONTEST":
                area_id = "national_park_contest"
            _require(_AREA.fullmatch(area_id) is not None and row["encoded_id"] == row["group"] * 256 + row["number"],
                     "invalid map identity")
            self._areas[str(row["encoded_id"])] = {
                "area_id": area_id, "map_group": row["group"], "map_number": row["number"],
                "map_const": row["constant"], "map_name": row["source_label"], "fishing_group": fish.get(key)}
            self._area_names.setdefault(area_id, row["landmark_name"])

        self._encounters = load("encounter_tables", "polished-encounter-tables-v1")
        policy = self._encounters["policy"]
        _require(policy.get("egg_hatch_area") == "gift_daycare" and policy.get("roamer_area") == "legend_<species>"
                 and policy.get("contest_area") == "national_park_contest"
                 and policy.get("roamer_consumes_ordinary_area") is False, "acquisition policy mismatch")
        self._roamers = {row["species"] for row in self._encounters["roamers"]["initial"]}
        _require(self._roamers and self._roamers <= self._species.keys(), "invalid roamer inventory")
        self._legend_species = set(self._roamers)

        gifts = load("gifts", "polished-gifts-v1")["gifts"]
        # Same O-16 rule as vanilla: a static's area id is static_<lowercase map constant>_<species>.
        # P3: the client must emit these ids; the Polished pack carries none of its own.
        statics = load("static_encounters", "polished-static-encounters-v1")["encounters"]
        self._static_ids = set()
        for row in statics:
            if not row.get("applicability", {}).get("selected") or row.get("source_unused"):
                continue
            area = self._areas.get(str(row["map_group"] * 256 + row["map_number"]))
            _require(area is not None and _integer(row["species"], 1, 0x1FF), "static row on an unknown map")
            canonical = f"static_{area['map_const'].lower()}_{row['species']}"
            _require(_STATIC.fullmatch(canonical) is not None, "invalid static area id")
            self._static_ids.add(canonical)
        # A gift area qualifies as fixed-species when every selected givepoke in it names one species
        # (gen2_gsc._fixed_species_gift_areas), here over the one Polished pack.
        by_area = {}
        for row in gifts:
            if row.get("applicability", {}).get("selected") and row.get("operation") == "givepoke":
                area = self._areas[str(row["map_group"] * 256 + row["map_number"])]["area_id"]
                by_area.setdefault(area, set()).add(row.get("species"))
        self._fixed_gift_areas = frozenset(a for a, s in by_area.items() if len(s) == 1)
        self._tables = self._presentation_tables()

        # trainer_id = class * 256 + instance (trainers.json id_packing; wOtherTrainerClass/wOtherTrainerID).
        # Rivals (owner ruling 2026-10-08): every instance of RIVAL0 $1B, RIVAL1 $1C, RIVAL2 $1D ONLY. LYRA1 $1E and
        # LYRA2 $1F are named by the pack (constants/trainer_constants.asm:95-127, RAM.md §4.3) but are NOT Rival Team
        # Swap battles. The three are selected by NAME from trainers.json, never by number.
        trainers = load("trainers", "polished-trainers-v1")
        self._trainer_classes = {int(k): v for k, v in trainers["classes"].items()}
        self._trainer_names = {(int(cls), int(inst)): row.get("name", "")
                               for cls, rows in trainers["parties"].items() for inst, row in rows.items()}
        _require(all(_integer(c, 1, 255) and _integer(i, 1, 255) for c, i in self._trainer_names),
                 "trainer (class, instance) outside a byte")
        _require(trainers["rival_classes"].keys() == {"RIVAL0", "RIVAL1", "RIVAL2", "LYRA1", "LYRA2"}
                 and all(trainers["class_constants"][str(c)] == k for k, c in trainers["rival_classes"].items()),
                 "rival classes missing or inconsistent")
        rivals = {trainers["rival_classes"][name] for name in ("RIVAL0", "RIVAL1", "RIVAL2")}
        self._rival_ids = frozenset(c * 256 + i for c, i in self._trainer_names if c in rivals)
        self._artifact_kind, self.randomized, self._rom_adopted = "clean", False, False
        if artifact_kind is not None:
            self.set_artifact_kind(artifact_kind)

    @property
    def game_id(self):
        return "gen2_polished"

    def rival_trainer_ids(self):
        # RIVAL0/1/2 only (owner 2026-10-08); a fresh set so a caller can never mutate the adapter's own.
        return set(self._rival_ids)

    # One title: a hello can never need its own per-player adapter.
    def per_player_key(self, rom_type):
        return _ROM_TYPES.get(rom_type)

    @staticmethod
    def companion_refusal(hello):
        # Owner 2026-10-02 patch-first: the Polished companion overlay is required; a clean build is refused.
        # A randomized overlay (rand_overlay) carries the same companion and publishes the same ABI.
        rom_type = hello.get("rom_type")
        if rom_type not in _ROM_TYPES:
            return None
        pinned, abi = _companion_abi(), hello.get("companion_abi")
        if pinned is None or type(abi) is not int or abi != pinned or hello.get("artifact_kind") not in _COMPANION:
            return companion_required_reason("Polished Crystal")
        return None

    # ── randomized cartridges (P8, the Polished counterpart of Gen 2's R4) ─────────────
    def set_artifact_kind(self, kind):
        _require(kind in _KINDS, "Polished Crystal only supports the clean/overlay/rand_overlay artifact kinds")
        self._artifact_kind = kind
        # a randomized cartridge answers encounters only from its own ROM (use_rom_encounters)
        self.randomized = kind == "rand_overlay"

    @classmethod
    def supports_randomized(cls, rom_type):
        # rand_overlay, bound at hello by the contract's rom_sha1 (rom_contract_by_sha1)
        return isinstance(rom_type, str) and rom_type in _ROM_TYPES

    # The Manager's contract carries no table fingerprint for Polished (upr_pipeline: fingerprint ""): the run
    # binds each cartridge by the full-ROM sha1 the client rehashes, as Gen 2 does.
    rom_contract_by_sha1 = True

    def supports_info_panel(self):
        return self._artifact_kind in _COMPANION   # the panel ships in the companion, randomized or not

    def native_trade_ui(self):
        return self._artifact_kind in _COMPANION

    def info_panel_width(self):
        # The Polished ROM panel is `lines` x `line_max` glyphs per page (profile overlay.panel), far narrower than the
        # 20-column vanilla screen; the server builds its compact single-line rows for any width 0 < w <= 20. Wide
        # `label|field|...` rows are unreadable here ('|' is unmapped, values cut at 16). 0 = no panel on a clean build.
        if not self.supports_info_panel():
            return 0
        return _panel_line_max()

    def encounter_table(self, area_id):
        # a randomized cartridge shows only its own tables, never the vanilla ones beside it
        if self.randomized and not self._rom_adopted:
            return None
        return copy.deepcopy(self._tables.get(area_id))

    def ingest_rom_content(self, payload):
        """The cartridge's own tables (scan_randomized). The payload must be the SERVER's read of the Manager's
        file for this player (server.py _contracted_rom): bytes -- which a JSON hello cannot carry -- whose sha1
        is the contract's pin. Anything a client reports stays unqualified."""
        if not (isinstance(payload, dict) and type(payload.get("rom")) is bytes):
            raise ValueError("Polished Crystal client ROM-content admission is not qualified")
        rom, pin = payload["rom"], payload.get("rom_sha1")
        _require(isinstance(pin, str) and hashlib.sha1(rom).hexdigest() == pin.lower(),
                 "cartridge bytes differ from the contract sha1")
        _require(payload.get("rom_type") in _ROM_TYPES, "not a Polished Crystal cartridge")
        return scan_randomized(rom)

    def use_rom_encounters(self, tables):
        """Adopt ingest_rom_content's tables for this player's cartridge. {} (an unreadable cartridge) shows no
        encounters at all, never the vanilla ones. Area ids stay the pack's (static/gift/legend ids name the
        vanilla site); roamers are the overlay's own (no handler writer), so legend names need no remap."""
        self._rom_adopted = True
        if not tables:
            self._tables = {}
            return
        _require(tables.get("title") == TITLE, "ROM tables belong to another title")
        self._encounters = _adopt_encounters(self._encounters, tables)
        self._tables = self._presentation_tables()

    # ── identity (polished_codec.key: DDDDDD:OOOO:SSS:TT) ────────────────────────────
    def _key(self, key):
        match = _KEY.fullmatch(key) if isinstance(key, str) else None
        return match if match and int(match[3], 16) in self._species else None

    def is_valid_mon_key(self, key):
        return self._key(key) is not None

    def parse_ot_id(self, key):
        match = self._key(key)
        return match[2] if match else ""

    def gender_from_key(self, key, species_id):
        # species_id is the wire's EFFECTIVE id (a variant's record index); the key carries the raw species + form
        match = self._key(key)
        raw, form = (int(match[3], 16), int(match[4], 16) & 0x1F) if match else (None, 0)
        if match is None or species_id not in (raw, polished_codec.effective_species(raw, form)):
            return ""
        ratio = self._row(raw, form)["gender_ratio"]
        if ratio == _GENDERLESS:
            return "genderless"
        # Polished stores gender explicitly (form byte bit 7, FEMALE = %10000000); the ratio only
        # overrides it for single-gender species.
        if ratio in (_ALL_FEMALE, _ALL_MALE):
            return "female" if ratio == _ALL_FEMALE else "male"
        return "female" if int(match[4], 16) & 0x40 else "male"

    def is_shiny(self, key):
        match = self._key(key)
        return bool(match and int(match[4], 16) & 0x80)

    # ── species (9-bit id, optional form) ────────────────────────────────────────────
    def _row(self, species_id, form=0):
        return self._variants.get((species_id, form)) or self._species[species_id]

    def species_name(self, species_id, form=0):
        record = self._variant_by_record.get(species_id) if type(species_id) is int else None
        if record is not None:   # an effective id: named exactly as species_name(species, form) names it
            return f"{self._species[record['species']]['name']} ({_form_label(record)})"
        if not _integer(species_id, 1, 0x1FF) or species_id not in self._species:
            return f"#{species_id}" if type(species_id) is int else "#?"
        variant = self._variants.get((species_id, form))
        name = self._species[species_id]["name"]
        return f"{name} ({_form_label(variant)})" if variant else name

    def species_types(self, species_id, form=0):
        # Owner ruling 2026-10-04: a variant form is a DIFFERENT mon. The codec hands the shared state an
        # EFFECTIVE species id (the variant's BaseData record index, 292..337), so the type clause judges
        # Alolan Rattata on Alolan Rattata's types without state.py ever seeing a form.
        # The old "form 0 of a variant-bearing species -> None" skip is gone: it silently exempted every
        # standard/variant pair (review cx-7110b381 #1), which the effective id makes unnecessary.
        record = self._variant_by_record.get(species_id) if type(species_id) is int else None
        if record is not None:
            return tuple(record["type_ids"])
        if type(form) is int and (species_id, form) in self._variants:
            return tuple(self._variants[(species_id, form)]["type_ids"])
        return tuple(self._row(species_id, form)["type_ids"]) if species_id in self._species else None

    def evo_family(self, species_id):
        """Owner ruling 2026-10-04: a regional form is a DIFFERENT mon from its standard
        counterpart, but an evolution is the SAME mon as its pre-evolution. So the family is the
        lowest effective id in the connected component of the evolution graph over BOTH the
        variant edges (forms_index.json evolves_to) and the plain edges (evolutions.json).

        A variant with no evolution edge (31 of 46) is a singleton - never merged into its
        standard counterpart, because nothing in the graph says it should be.
        """
        if type(species_id) is not int:
            return species_id
        if self._variant_families_cache is None:
            self._variant_families_cache = self._variant_families()
        return self._variant_families_cache.get(species_id, species_id)

    def _variant_families(self) -> dict:
        """Union-find over the combined graph; plain species keep the pack's own families."""
        parent = {}

        def find(x):
            parent.setdefault(x, x)
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        def union(a, b):
            ra, rb = find(a), find(b)
            if ra != rb:
                parent[max(ra, rb)] = min(ra, rb)

        for species, family in self._families.items():
            union(species, family)
        for record, row in self._variant_by_record.items():
            find(record)
            for target in row.get("evolves_to", []):
                tid = target["effective_species_id"]
                if tid is not None:
                    union(record, tid)
        # lowest id in each component wins, so the answer is deterministic
        lowest = {}
        for node in list(parent):
            root = find(node)
            lowest[root] = min(lowest.get(root, node), node)
        return {node: lowest[find(node)] for node in parent}

    def to_national_dex(self, species_id):
        row = self._species.get(species_id) if type(species_id) is int else None
        return (row or {}).get("national_dex") or 0   # ids > 251 have no national dex in the pinned source

    # ── items / moves ────────────────────────────────────────────────────────────────
    def is_valid_held_item(self, item_id):
        if not _integer(item_id, 0, 254):
            return False
        row = self._items.get(item_id)
        # Mail never travels (O-14). Key items live in their own id space (items.json key_items), and
        # Polished has no CANT_TOSS permission byte (items.json note).
        return item_id == 0 or bool(row and not row["placeholder"] and not row["key_item"] and not row["mail"])

    def item_name(self, item_id):
        row = self._items.get(item_id) if _integer(item_id, 1, 254) else None
        return row["name"] if row and not row["placeholder"] else ""

    def move_data(self, move_id):
        data = super().move_data(move_id)
        if data is not None and data["type_name"] == "Unknown_T":
            data["type_name"] = "???"
        return data

    def calc_name(self, kind, name):
        # Polished's display names are the calc's own English names for every shared concept, and
        # every lookup here is toID()-keyed either way, so identity is the whole table.
        return name

    def calc_species(self, species_id):
        """The calc's species key for an EFFECTIVE id (base.GamePresentationAdapter.calc_species).

        A plain species is its pack name under CALC_SPECIES_FIXUPS; a variant form -- whose
        effective id IS its BaseData record index -- is "<base>-<form label>", the key
        tools/gen_polished_calc.py writes into calc/src/calc/data/polished.js. Both are re-spellings
        of species_name(), never a second naming policy.
        """
        if type(species_id) is not int:
            return super().calc_species(species_id)
        record = self._variant_by_record.get(species_id)
        if record is not None:
            base = _calc_species_name(self._species[record["species"]]["name"])
            return f"{base}-{_form_label(record).replace(' ', '-')}"
        if species_id in self._species:
            return _calc_species_name(self._species[species_id]["name"])
        return super().calc_species(species_id)

    def calc_profile(self):
        # Gen 3 MECHANICS on Polished's own data: a per-move physical/special split, natures and
        # an 85-100% damage roll are exactly what calc/calc/src/mechanics/gen3.ts's calculateADV
        # implements, and the damage pipeline ((((2*lv/5+2)*A*bp/D)/50)+2) is the one the engine
        # runs (BattleCommand_damagecalc, DamagePass1..4). Data swap only, via calc.usePolished().
        # No `sets`: Polished ships no trainer-setdex file, so the calc's Prep tab stays hidden
        # (calc/src/js/slink_bridge.js _maybeLoadGameSets -> _supportsPrepTab). docs/polished/CALC.md.
        return {"name": "Polished Crystal", "gen": 3, "dex": "polished"}

    def calc_stats(self, detail):
        """IVs (Polished's DVs, doubled -- see below) and EVs from the 70-byte party blob, in the
        calculator's gen 3 shape.

        Gen2GSCAdapter.calc_stats emits `dvs`/`stat_exp` because the GEN 2 stat formula wants them.
        Polished's stat formula is pokecrystal's CalcPkmnStatC with EVs in the stat-exp slot
        (engine/pokemon/mon_stats.asm:763-836): (base + DV) * 2 + 1 + floor(EV/4), times level,
        over 100. The calc's gen 3 path is the same shape but halves the DV term, so the DV is
        re-expressed as IV = 2*DV + 1 -- total over every DV (0 -> 1, 15 -> 31), still inside the
        calc's 0..31 IV range, and exact rather than a fudge factor.
        `stats` is that same arithmetic under a NEUTRAL nature, so the page can cross-check the
        engine's result against it.

        None when the client sent no blob -- the normal case for an ENEMY, because the Polished
        client's foe_entry carries no blob_hex and the calc then uses its own defaults
        (docs/polished/CALC.md §3).
        """
        blob_hex = detail.get("blob_hex")
        if not blob_hex:
            return None
        try:
            mon = polished_codec.decode_party_blob(bytes.fromhex(blob_hex))
        except (ValueError, TypeError):
            return None
        level = detail.get("level", 0)
        if not _integer(level, 1, 100):
            return None
        base = self._row(mon["species_id"], mon.get("form", 0))["base_stats"]
        ivs, evs, stats = {}, {}, {}
        for calc_key, pack_key in _STAT_KEYS:
            ivs[calc_key] = 2 * mon["dvs"][pack_key] + 1
            evs[calc_key] = mon["evs"][pack_key]
            stats[calc_key] = _crystal_stat(base[pack_key], mon["dvs"][pack_key],
                                            evs[calc_key], level, hp=calc_key == "hp")
        return {"ivs": ivs, "evs": evs, "stats": stats}

    def supports_abilities(self):
        return False  # P3: the ability slot is personality bits 5-6, not in the key; names need the slot

    # ── party blobs ──────────────────────────────────────────────────────────────────
    def party_blob_size(self):
        return polished_codec.BLOB_SIZE

    def decode_party_blob(self, blob, *, species_marker=None):
        """species_marker is accepted for the shared signature and ignored: Polished keeps the egg flag in
        the record (form byte bit 6) and has no species list (RAM.md §1.2 wPartySpecies absent)."""
        if isinstance(blob, str):
            _require(re.fullmatch(r"[0-9A-Fa-f]{140}", blob) is not None, "malformed 70-byte party blob")
            blob = bytes.fromhex(blob)
        mon = polished_codec.decode_party_blob(blob)
        mon["key"] = polished_codec.key(mon)
        # The species the shared state judges this mon as: a variant form's BaseData record index.
        mon["effective_species_id"] = polished_codec.effective_species(
            mon["species_id"], mon["form"])
        return mon

    def validate_party_blob(self, blob, *, key=None, species_marker=None):
        try:
            mon = self.decode_party_blob(blob)
            return (mon["species_id"] in self._species and self.is_valid_held_item(mon["held_item"])
                    and all(m == 0 or m in self._moves for m in mon["moves"])
                    and (key is None or self.is_valid_mon_key(key) and mon["key"] == key.upper()))
        except (ValueError, TypeError, KeyError):
            return False

    # ── acquisition areas ────────────────────────────────────────────────────────────
    def is_fixed_species_gift(self, area_id):
        return isinstance(area_id, str) and area_id.removeprefix("gift_") in self._fixed_gift_areas

    def gift_link_area(self, area_id, *, acquisition=None, species_id=None):
        # gen2_gsc's acquisition branch validates species 1..251; Polished species are 9-bit.
        _require(isinstance(area_id, str) and _AREA.fullmatch(area_id), "invalid acquisition area")
        if acquisition is not None:
            _require(species_id in self._species or species_id in self._variant_by_record,
                     "acquisition requires an actual species, not EGG")
            if acquisition == "egg_hatch":
                return "gift_daycare"
            if acquisition == "roamer":
                _require(species_id in self._roamers, "species is not a Polished roamer")
                return f"legend_{species_id}"
            if acquisition == "contest":
                return "national_park_contest"
            _require(acquisition == "gift", "unqualified acquisition kind; egg pickup is not capture")
        return super().gift_link_area(area_id)

    def _presentation_tables(self):
        """Maps, times and slot rows stay distinct; rates are table probabilities (gen2_gsc's shape)."""
        grouped = {}

        def emit(key, label, slots, weights, **metadata):
            area = self._areas.get(str(key))
            _require(area is not None, "encounter refers to a missing map")
            target = grouped.setdefault((area["area_id"], label, key, metadata.get("source_table")), [])
            for slot, (entry, weight) in enumerate(zip(slots, weights, strict=True)):
                species, form = entry["species"], entry.get("form", 0)
                if species == 0:
                    continue   # ponytail: engine time-of-day fish pick; the pack has no time_groups to resolve it
                _require(species in self._species, "unresolved encounter species")
                level = entry.get("level")
                target.append({"species_id": species, "form": form, "name": self.species_name(species, form),
                               "effective_species_id": polished_codec.effective_species(species, form),
                               "rate": weight, "min_level": entry.get("min_level", level),
                               "max_level": entry.get("max_level", level), "slot": slot,
                               "map_group": area["map_group"], "map_number": area["map_number"],
                               "map_name": area["map_name"], **metadata})

        wild = self._encounters["wild"]
        for kind in ("grass", "water"):
            thresholds = [row["threshold"] for row in wild[f"{kind}_probabilities"]]
            _require(thresholds == sorted(set(thresholds)) and thresholds[-1] == 100, "wild slot probabilities invalid")
            weights = [high - low for low, high in zip([0, *thresholds[:-1]], thresholds, strict=True)]
            for row in wild[kind]:
                label = "Surf" if kind == "water" else {"morning": "Morn", "day": "Day", "night": "Nite"}[row["time"]]
                emit(row["map_group"] * 256 + row["map_number"], label, row["slots"], weights,
                     encounter_rate_byte=row["rate"], time=row["time"], source_table=row["table"])
        tree = self._encounters["tree"]
        sets = {row["set_id"]: row for row in tree["sets"]}
        for kind, maps in (("Headbutt", tree["headbutt_maps"]), ("Rock Smash", tree["rock_smash_maps"])):
            for row in maps:
                source = sets[row["set_id"]]
                for rarity in ("common", "rare"):
                    if slots := source.get(rarity):
                        emit(row["map_group"] * 256 + row["map_number"],
                             kind + (f" {rarity.title()}" if kind == "Headbutt" else ""),
                             slots, [entry["weight"] for entry in slots], set_id=row["set_id"])
        groups = {row["group_id"]: row for row in self._encounters["fishing"]["groups"]}
        for key, area in self._areas.items():
            group = groups.get(area["fishing_group"])
            if group is None:
                continue
            for rod in ("old", "good", "super"):
                thresholds = [entry["threshold"] for entry in group[rod]]
                _require(thresholds == sorted(set(thresholds)) and thresholds[-1] == 255, "fish thresholds invalid")
                weights = [(high - low) * 100 / 256 for low, high in zip([-1, *thresholds[:-1]], thresholds, strict=True)]
                emit(int(key), f"{rod.title()} Rod", group[rod], weights, fish_group=group["group_id"],
                     bite_threshold=group["bite_threshold"], map_association="UNQUALIFIED")
        tables, maps_by_method, tables_by_map = {}, {}, {}
        for area, label, key, source_table in grouped:
            maps_by_method.setdefault((area, label), set()).add(key)
            tables_by_map.setdefault((area, label, key), set()).add(source_table)
        for (area, label, key, source_table), slots in grouped.items():
            method = label
            if source_table is not None and len(tables_by_map[area, method, key]) > 1:
                label += " (Swarm)" if source_table.startswith("Swarm") else " (Normal)"
            if len(maps_by_method[area, method]) > 1:
                label += f" ({self._areas[str(key)]['map_name']})"
            target = tables.setdefault(area, {})
            _require(label not in target, "encounter presentation variants collide")
            target[label] = slots
        contest = self._encounters["contest"]
        tables["national_park_contest"] = {"Contest": [
            {"species_id": row["species"], "name": self.species_name(row["species"]), "rate": row["weight"],
             "min_level": row["min_level"], "max_level": row["max_level"], "slot": index}
            for index, row in enumerate(contest["slots"])]}
        return tables

    # ── boxes, sprites, trainers ─────────────────────────────────────────────────────
    def supports_explode_mode(self):
        return False             # OPEN-EXPLODE-RIVAL: enable only with live proof and the Manager rows.
                                  # Normal plain-faint enforcement is composed independently.

    def supports_box_mon(self):
        # Party sync ON (owner 2026-10-08): deposit and withdraw are composed through O.client_boxes
        # (lua/gen2/entry.lua) and passed the live write driver on overlay cf03f53a, (b) and (d) with an
        # independently derived changed-byte subset (docs/polished/LIVE_RESULTS.md). The optional
        # three-outcome box-write contract is parked; this is the legacy two-outcome path vanilla uses.
        return True

    def reports_box_census(self):
        return True              # The composed client reports the newbox/PokeDB census (NEWBOX.md §6.1).

    @property
    def mons_per_box(self):
        return 20                # 20 entry indices per sNewBox record: `\1Entries:: ds MONS_PER_BOX`
                                  # (macros/ram.asm:143, the `newbox` macro at sram.asm:141), which
                                  # docs/polished/NEWBOX.md §1.1 tabulates as a 20-byte `Entries`
                                  # field and §1.1 (slot coordinates) puts slots at 1..20.

    @property
    def memorial_box_index(self):
        # The memorial is the LAST box: docs/polished/NEWBOX.md §1.1 has sNewBox1..20 with
        # sNewBoxEnd after sNewBox20 (data/polished/polishedcrystal.sym sNewBox1 = 01:b0e4,
        # sNewBox20 = 01:b357), and §1.1 makes box/slot coordinates 1-based, so box 20 is index 19.
        return 19                # P3: the newbox writer (NEWBOX.md §6.2) honours it.

    def sprite_src(self, species_id):
        # Gen 2 art exists only for the 251 national-dex species; newer Polished species have none pinned.
        if not _integer(species_id, 1, 251):
            return ""
        return ("https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/"
                f"generation-ii/crystal/transparent/{species_id}.png")

    def gym_badge_slugs(self, rom_type):
        # Bit order (constants/ram_constants.asm:275-295): Johto as Crystal, but Polished swaps Kanto's
        # Marsh (bit 4) and Soul (bit 5) relative to vanilla (RAM.md §3.3 calls the order identical; it is not).
        slugs = super().gym_badge_slugs(rom_type)
        slugs[12], slugs[13] = slugs[13], slugs[12]
        return slugs

    def trainer_info(self, trainer_id):
        if not _integer(trainer_id, 1, 0xFFFF) or (key := divmod(trainer_id, 256)) not in self._trainer_names:
            return "", ""
        name = self._trainer_names[key]
        # The rival's parties carry the <RIVAL> placeholder (the player names him): show him by class.
        return ("" if name == "<RIVAL>" else name), self._trainer_classes.get(key[0], "")
