"""Server facts for one pinned pokeemerald-expansion reference build.

SOURCE: expansion e8bd1cd7, extracted from ROM 28877d73 using compiler layout.
No Lua admission or runtime qualification is implied by this server adapter.
Regenerate with tools/extract_expansion_data.py --rom <reference.gba>
--source <expansion-e8bd1cd7-checkout>
--layout data/games/gen3_exp/28877d73/layout.json
--output data/games/gen3_exp/28877d73/data.json; add --check for read-only comparison.

Recorded limits: encounter-table/area/static-policy packs and ability prose are
not extracted (trainer panels ARE, since XC4/XC4b -- see below). Explicit gift_
events work; no unproved fixed-gift exemption is inherited from vanilla.
Sprites use National Dex base art, not form art. This adapter only READS
expansion data/records.

Calc: calc_profile()/calc_name()/calc_stats() (XC1-XC3,
docs/gen3_emerald/research/expansion_calc_design_2026-09-26.md §4) run this
build at the vendored calc's gen 9 mechanics. calc_profile()["sets"] points at
calc/src/js/data/sets/games/EmeraldExpansion.js (XC4a), generated by
tools/gen_gen3_exp_trainers.py from src/data/trainers.h at the pin -- full
species+level coverage of every party slot (not a curated subset). A handful
of names have no gen-9 calc equivalent at all (homebrew abilities,
Mega Stones -- Gen 9 has no Mega Evolution) and stay unresolved by design;
see tools/gen_expansion_calc_names.py's EXPECTED_UNRESOLVED.

Trainer panels (XC4b): trainer_info/trainers_for_area/trainer_party/trainer_brief lazy-load
data/games/gen3_exp/28877d73/gen3_exp_trainers.json (_load_trainers_pack(), a process-wide
functools.cache -- calc_profile()/calc_name() and a Manager render never touch this pack), the
same generator's other output -- gTrainers-indexed (wire trainer_id, no offset), key trainers
flagged for the dashboard's Upcoming Key Trainers panel (gym leaders, Elite Four, Champion, the
rival, Team Aqua/Magma leaders and admins). A Vs Seeker rematch tier's area comes from the
pinned source's own gRematchTable, never a same-(class,name) guess; trainer_brief's calc_label
is the Prep tab base name (unique per trainer id -- see tools/gen_gen3_exp_trainers.py's
compute_bases()), read by server.py's _calc_trainer_label() to label a live enemy row. See
tools/gen_gen3_exp_trainers.py's docstring for extraction rules and the remaining known gaps.

Shiny product gap: src/pokemon.c:2480-2483 at e8bd1cd7 applies
((PID_hi ^ PID_lo ^ OT_hi ^ OT_lo) < SHINY_ODDS) ^ shinyModifier;
include/constants/pokemon.h:107 pins SHINY_ODDS=8. is_shiny accepts that bit,
but shared state.py currently calls is_shiny(key) with no record. That path
can only evaluate the natural PID rule and cannot see modifier-forced shinies
(or a modifier suppressing a natural shiny). Wire integration remains OPEN.

Key contract: the same wire key Gen3Adapter uses -- two 8-hex-digit halves, "PID:OTID",
where OTID is the FULL 32-bit OT id (TID in the low 16, SID in the high 16), never a
16-bit trainer id. Any parse here, and the shiny split that reads both halves, must
keep the SID.
"""
from __future__ import annotations

import copy
import functools
import json
import re
from html import escape
from pathlib import Path

from . import gen3_codec
from .base import humanize_area_id
from .gen3_frlge import Gen3Adapter, _parse_pid_otid_key

ROM_SHA1 = "28877d733492299599f2b8fff50493109d72653c"
ROM_TYPE = "emerald_expansion_28877d73"
PACK = Path(__file__).resolve().parents[2] / "data/games/gen3_exp/28877d73/data.json"
CONFIG_PACK = Path(__file__).resolve().parents[2] / "data/games/gen3_exp/28877d73/config.json"
CALC_NAMES_PACK = Path(__file__).resolve().parents[2] / "data/games/gen3_exp/28877d73/calc_names.json"
TRAINERS_PACK = Path(__file__).resolve().parents[2] / "data/games/gen3_exp/28877d73/gen3_exp_trainers.json"
_SOURCES_LOCK = Path(__file__).resolve().parents[2] / "data/gen3_exp_sources.lock.json"


@functools.cache
def _load_trainers_pack() -> tuple[dict[int, dict], dict[str, list[int]]]:
    """Lazy, process-wide-cached load of gen3_exp_trainers.json: calc_profile()/calc_name() and
    a Manager render construct Gen3ExpansionAdapter far more often than anything touches a
    trainer panel, so __init__ must not parse this ~40k-line pack every time (OMP cx-081c78d3
    F8). Fails closed the first time anything DOES need it: a pack whose source.commit doesn't
    match the pinned data/gen3_exp_sources.lock.json is a stale/wrong pack, never served quietly
    (OMP cx-081c78d3 F7)."""
    raw = json.loads(TRAINERS_PACK.read_text(encoding="utf-8"))
    lock = json.loads(_SOURCES_LOCK.read_text(encoding="utf-8"))
    if raw.get("source", {}).get("commit") != lock["source"]["commit"]:
        raise ValueError(
            f"{TRAINERS_PACK} source.commit does not match the pin in {_SOURCES_LOCK}")
    trainers = {int(k): v for k, v in raw["trainers"].items()}
    trainers_by_area = {k: list(v) for k, v in raw["trainers_by_area"].items()}
    return trainers, trainers_by_area


# include/constants/pokemon.h:5-28 at e8bd1cd7; NOT vanilla's zero-based types.
TYPE_NAMES = ("None", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug",
              "Ghost", "Steel", "???", "Fire", "Water", "Grass", "Electric", "Psychic",
              "Ice", "Dragon", "Dark", "Fairy", "Stellar")

# The calc's gen789 mechanics module is a fixed "modern" engine with no per-config knob
# (calc.ts:20-22; docs/gen3_emerald/research/expansion_calc_design_2026-09-26.md §3 point 1):
# it always runs the Gen 9 crit/terrain/ability tables. Mapping a build to gen:9 is only
# honest when that build's own damage-mechanics config targets the same generation.
# include/config/general.h's GEN_1..GEN_9 enum is zero-indexed (GEN_9 == 8), so
# GEN_LATEST's value 8 IS "Gen 9" here, not "Gen 8" -- confirmed by reading config.json.
_CALC_CRITICAL_MACROS = ("B_CRIT_MULTIPLIER", "B_PHYSICAL_SPECIAL_SPLIT", "B_ABILITY_WEATHER")
# include/config/general.h: GEN_1 0 .. GEN_9 8 -- the calc profile below is gen 9 only.
_GEN_9 = 8

# XR-1/XR-2 party-record bit layout for this build (server/adapters/gen3_codec.py
# decode_party_mon_masked/validate_expansion_layout), verified against
# rh-hideout/pokeemerald-expansion tag expansion/1.17.0 (e8bd1cd7) include/pokemon.h and
# cross-checked byte-for-byte against this ROM's own facts.json PokemonSubstruct0/1/3
# bitfields (species mask 0x7ff, heldItem mask 0x3ff, move masks 0x7ff, experience mask
# 0x1fffff, pp masks 0x7f, pokeball word_off10/width6, abilityNum word_off8/shift29/width2)
# -- identical to tests/fixtures/gen3/expansion_layout_e8bd1cd7.json's "layout" block.
EXPANSION_PARTY_LAYOUT = {
    "MON_SPECIES_MASK": 2047,
    "MON_ITEM_MASK": 1023,
    "MON_MOVE_MASK": 2047,
    "EXPERIENCE_MASK": 2097151,
    "NICKNAME_EXTRA": {"chars": [
        {"word_off": 4, "word_size": 4, "shift": 21, "width": 8},
        {"word_off": 10, "word_size": 2, "shift": 6, "width": 8},
    ]},
    "POKEBALL_FIELD": {"word_off": 10, "word_size": 2, "shift": 0, "width": 6},
    "ABILITY_NUM_FIELD": {"word_off": 8, "word_size": 4, "shift": 29, "width": 2},
    "PP_MASK": 127,
    "MARKINGS_MASK": 15,
    "SHINY_MODIFIER_FIELD": {"shift": 14, "width": 1},
}

# data.json's id-0 rows carry sentinels, not names: SPECIES_NONE/MOVE_NONE/ITEM_NONE/
# ABILITY_NONE are "??????????", "????????", "-" and "????????" in the shipped pack.
_SENTINEL_NAME = re.compile(r"^[\s?\-]*$")


def _name(row: dict, fallback: str) -> str:
    """``row["name"]``, or `fallback` when it is missing or an id-0 sentinel.

    A sentinel is not a display name: no board may print "??????????".
    """
    name = row.get("name")
    return name if name and _SENTINEL_NAME.fullmatch(name) is None else fallback


class Gen3ExpansionAdapter(Gen3Adapter):
    def __init__(self, **kwargs):
        if kwargs.get("rom_type", ROM_TYPE) != ROM_TYPE:
            raise ValueError("expansion reference build rom_type required")
        # "emerald" here reaches only the Gen3Adapter surfaces this class overrides.
        # Expansion numbers species nationally (0..1572, NUM_SPECIES=1573) and masks
        # its record fields per layout.json, so no vanilla Emerald table is read:
        # data.json is the only source.
        super().__init__(is_rr=False, rom_type="emerald")
        self._rom_type = ROM_TYPE
        data = json.loads(PACK.read_text(encoding="utf-8"))
        if data["schema"] != 1 or data["kind"] != "expansion" or data["rom_sha1"] != ROM_SHA1:
            raise ValueError("expansion data pack identity mismatch")
        self._species = {row["id"]: row for row in data["species"]}
        self._moves = {row["id"]: row for row in data["moves"]}
        self._items = {row["id"]: row for row in data["items"]}
        self._abilities = {row["id"]: row for row in data["abilities"]}
        self._config_macros = json.loads(CONFIG_PACK.read_text(encoding="utf-8"))["macros"]
        self._calc_names = json.loads(CALC_NAMES_PACK.read_text(encoding="utf-8"))
        # Trainer pack: NOT read here -- see _load_trainers_pack()'s docstring (OMP cx-081c78d3 F8).

    @property
    def game_id(self):
        return "gen3_exp"

    def reports_box_census(self) -> bool:
        # Server data support is not an admitted client that stamps complete box scans.
        return False

    def species_name(self, species_id):
        return _name(self._species.get(species_id, {}), f"Species #{species_id}")

    def species_types(self, species_id):
        row = self._species.get(species_id)
        return tuple(row["types"]) if species_id and row else None

    def type_name(self, type_id):
        return TYPE_NAMES[type_id] if 0 <= type_id < len(TYPE_NAMES) else "???"

    def evo_family(self, species_id):
        return self._species.get(species_id, {}).get("family", species_id)

    def move_name(self, move_id):
        if not move_id:
            return ""
        return _name(self._moves.get(move_id, {}), f"Move #{move_id}")

    @staticmethod
    def pairing_kind(kind):
        # Each future build needs explicit admission; no named/companion alias.
        return kind

    @property
    def area_pack(self):
        return "gen3_exp/28877d73"

    def is_gift_area(self, area_id):
        return (area_id or "").startswith("gift_")

    def is_fixed_species_gift(self, area_id):
        return False

    def is_daycare_area(self, area_id):
        return False

    def area_display_name(self, area_id):
        # No vanilla overrides or an invented expansion area catalog -- just the same
        # words-at-every-seam fallback every other adapter with no name table falls back to
        # (OMP cx-081c78d3 F6; e.g. gen3_frlge.area_display_name).
        return humanize_area_id(area_id) if area_id else ""

    def gender_from_key(self, key, species_id):
        # src/pokemon.c:1805-1818; species.genderRatio is extracted, including forms.
        row, parsed = self._species.get(species_id), _parse_pid_otid_key(key)
        if not row or parsed is None:
            return "genderless"
        ratio = row["genderRatio"]
        if ratio == 255:
            return "genderless"
        if ratio == 254:
            return "female"
        return "female" if (parsed[0] & 255) < ratio else "male"

    def is_shiny(self, key, *, shiny_modifier=0):
        if _parse_pid_otid_key(key) is None:
            return False
        if shiny_modifier not in (0, 1):
            raise ValueError("shiny_modifier must be one bit")
        return super().is_shiny(key) ^ bool(shiny_modifier)

    def species_abilities(self, species_id):
        row = self._species.get(species_id)
        return tuple(row["abilities"]) if row else ()

    def ability_name(self, ability_id, species_id=0):
        if not ability_id:
            return ""
        return _name(self._abilities.get(ability_id, {}), f"Ability #{ability_id}")

    def ability_description(self, ability_id):
        return ""  # The extractor supplies names, not description strings.

    def item_name(self, item_id):
        if not item_id:
            return ""
        return _name(self._items.get(item_id, {}), f"Item #{item_id}")

    def move_data(self, move_id):
        row = self._moves.get(move_id)
        if not move_id or not row:
            return None
        # include/constants/pokemon.h:236-242: none=0/physical=1/special=2/status=3.
        # Display split is physical=0/special=1/status=2; never infer from type. A
        # missing or out-of-table category (0 = MOVE_STATUS_NONE is unused) takes 2:
        # the pack proves no physical/special split there, so display must not invent
        # one, and a table gap must not raise mid-page.
        return {"name": _name(row, f"Move #{move_id}"),
                "type_id": row["type"], "type_name": self.type_name(row["type"]),
                "power": row["power"], "accuracy": row["accuracy"], "pp": row["pp"],
                "split": {1: 0, 2: 1, 3: 2}.get(row.get("category"), 2)}

    def to_national_dex(self, species_id):
        return self._species.get(species_id, {}).get("national_dex", 0)

    def sprite_src(self, species_id):
        dex = self.to_national_dex(species_id)
        return f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/{dex}.png" if dex else ""

    def sprite_html(self, species_id, form=0):
        url = self.sprite_src(species_id)
        return f'<img class="mon-sprite" src="{escape(url, quote=True)}" alt="">' if url else ""

    def form_sprite_id(self, species_id):
        return None

    def encounter_table(self, area_id):
        return None

    def trainer_info(self, trainer_id):
        trainers, _ = _load_trainers_pack()
        tr = trainers.get(trainer_id)
        return (tr["name"], tr["class"]) if tr else ("", "")

    def trainers_for_area(self, area_id):
        if not area_id:
            return []
        _, trainers_by_area = _load_trainers_pack()
        return list(trainers_by_area.get(area_id, []))

    def trainer_party(self, trainer_id):
        trainers, _ = _load_trainers_pack()
        tr = trainers.get(trainer_id)
        # deepcopy: every mon dict nests further mutable structure (ivs, moves) that `dict(m)`
        # only shallow-copies -- a caller mutating out["party"][i]["ivs"]["hp"] would otherwise
        # corrupt the functools.cache-shared pack for every trainer_party()/trainer_brief() call
        # after it (card XC4c item 5; mirrors test_gen3_frlg_trainers.py's copy-isolation check,
        # extended one level deeper for this build's always-explicit ivs).
        return copy.deepcopy(tr["party"]) if tr else []

    def trainer_brief(self, trainer_id):
        trainers, _ = _load_trainers_pack()
        tr = trainers.get(trainer_id)
        if not tr or not tr["party"]:
            return None
        out = {"name": tr["name"], "class": tr["class"], "party": copy.deepcopy(tr["party"]),
               "area": tr.get("area", "")}
        if isinstance(tr.get("level_cap"), int):
            out["level_cap"] = tr["level_cap"]
        for k in ("calc_label", "fight_label"):
            if tr.get(k):
                out[k] = tr[k]
        return out

    def milestone_cap_for_fight_label(self, fight_label):
        return None

    def calc_name(self, kind, name):
        if not name:
            return name
        return self._calc_names.get(kind, {}).get(name, name)

    def calc_profile(self):
        latest = self._config_macros.get("GEN_LATEST", {}).get("value")
        if latest != _GEN_9:
            return None  # a build targeting another generation is not gen 9 (OMP cx-7cb40977 M1)
        for macro in _CALC_CRITICAL_MACROS:
            if self._config_macros.get(macro, {}).get("value") != latest:
                return None  # config targets a generation the calc can't express (XC1 doc)
        return {"gen": 9, "dex": "expansion",
                "sets": {"file": "EmeraldExpansion.js", "var": "CUSTOMSETDEX_EE"}}

    def calc_stats(self, detail):
        blob_hex = detail.get("blob_hex")
        if not blob_hex:
            return None
        try:
            blob = bytes.fromhex(blob_hex) if isinstance(blob_hex, str) else blob_hex
            mon = gen3_codec.decode_party_mon_masked(bytes(blob), rr=False,
                                                      layout=EXPANSION_PARTY_LAYOUT)
        except (ValueError, TypeError):
            return None

        def _short(d):
            return {"hp": d["hp"], "atk": d["attack"], "def": d["defense"],
                    "spa": d["sp_attack"], "spd": d["sp_defense"], "spe": d["speed"]}

        return {
            "ivs": _short(mon["ivs"]),
            "evs": _short(mon["evs"]),
            "stats": {"hp": mon["max_hp"], "atk": mon["attack"], "def": mon["defense"],
                      "spa": mon["sp_attack"], "spd": mon["sp_defense"], "spe": mon["speed"]},
        }

    def gym_badge_slugs(self, rom_type):
        return super().gym_badge_slugs("emerald")
