; GENERATED by tools/gen_polished_trade_items.py -- do not edit.
; Polished policy: allow ids $00..$f4 (NONE included); refuse mail $f5.. and the $ff sentinel.
; Indexed by the complete byte (not item-1).
SlinkTradeAllowedItems::
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $00
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $10
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $20
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $30
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $40
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $50
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $60
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $70
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $80
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $90
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $a0
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $b0
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $c0
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $d0
	db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 ; $e0
	db 1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0 ; $f0
SlinkTradeAllowedItemsEnd::
ASSERT SlinkTradeAllowedItemsEnd - SlinkTradeAllowedItems == 256
