#!/usr/bin/env python3
"""Generate Gen 2 Crystal full trainer data from pret/pokecrystal.

Reads:
    .cache/pret/pokecrystal/data/trainers/parties.asm

Writes:
    data/games/gen2_crystal/trainers.json    (extended named_trainers)
    lua/games/gen2_crystal_trainers.lua      (parallel update)

The classes dict is preserved (already complete from earlier phases). Only the
named_trainers map is extended: every instance of every class gets a personal
name. In pret each XxxGroup: section corresponds to one trainer class
(class_id N matches the Nth group in the file, 1-indexed). Inside a group the
trainer instances are listed in order; each starts with a line like
    db "NAME@", TRAINERTYPE_*

Class display names are NOT changed by this script — see the existing
"classes" map for the canonical labels. Only personal names per instance.
"""
from __future__ import annotations
import json
import os
import re
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_THIS_DIR, ".."))
_PRET = os.path.join(_REPO, ".cache", "pret", "pokecrystal")
_TRAINERS_JSON = os.path.join(_REPO, "data", "games", "gen2_crystal", "trainers.json")
_TRAINERS_LUA = os.path.join(_REPO, "lua", "games", "gen2_crystal_trainers.lua")
_PARTIES_ASM = os.path.join(_PRET, "data", "trainers", "parties.asm")

# Special-character pret names → display.
NAME_DISPLAY_OVERRIDES = {
    "FRIEDA":  "Frieda",
    "TUSCANY": "Tuscany",
    "ARTHUR":  "Arthur",
    "SUNNY":   "Sunny",
    "WESLEY":  "Wesley",
    "SANTOS":  "Santos",
    "MONICA":  "Monica",
}


def title_case_name(raw: str) -> str:
    """Convert pret all-caps trainer name to display form.

    Most names are pure alphabetic; the title-case heuristic gives "Joey",
    "Falkner", etc. Compound names with apostrophes or honorifics get
    overrides above.
    """
    if raw in NAME_DISPLAY_OVERRIDES:
        return NAME_DISPLAY_OVERRIDES[raw]
    # Special-char trainers ("MR." prefix, etc.)
    if raw.startswith("MR_"):
        return "Mr. " + raw[3:].title()
    # Default: title-case (Falkner, Joey, etc.)
    return raw.title()


def parse_parties_asm(path: str) -> dict[int, dict[int, str]]:
    """Return {class_id: {instance_id: personal_name}}.

    class_id is 1-based, matching Nth XxxGroup: label in the file.
    instance_id is 1-based within the class.
    """
    out: dict[int, dict[int, str]] = {}
    class_id = 0
    instance_id = 0
    label_re = re.compile(r"^([A-Za-z_0-9]+)Group:\s*$")
    name_re = re.compile(r'^db\s+"([^"@]+)@"\s*,\s*TRAINERTYPE')

    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.split(";", 1)[0]  # keep leading whitespace
            stripped = line.strip()
            if not stripped:
                continue
            m = label_re.match(stripped)
            if m:
                class_id += 1
                instance_id = 0
                out[class_id] = {}
                continue
            if class_id == 0:
                continue
            m = name_re.match(stripped)
            if m:
                instance_id += 1
                name = m.group(1).strip()
                out[class_id][instance_id] = title_case_name(name)
    return out


def main() -> int:
    if not os.path.exists(_PRET):
        sys.stderr.write(f"Missing pret repo at {_PRET}\n")
        return 1

    parsed = parse_parties_asm(_PARTIES_ASM)
    total_trainers = sum(len(v) for v in parsed.values())

    # Read existing trainers.json; keep its classes dict intact.
    with open(_TRAINERS_JSON, encoding="utf-8") as f:
        existing = json.load(f)

    # Build new named_trainers: every (class_id, instance_id) gets a name.
    named: dict[str, dict[str, str]] = {}
    for class_id, instances in sorted(parsed.items()):
        if not instances:
            continue
        named[str(class_id)] = {str(iid): n for iid, n in sorted(instances.items())}

    new_json = {
        "_comment": ("Gen 2 Crystal trainer data per pret/pokecrystal "
                     "constants/trainer_constants.asm and data/trainers/parties.asm. "
                     "class_id keys are the raw value held in wOtherTrainerClass "
                     "(1..67, no offset). named_trainers covers every instance of "
                     "every class — generated by tools/gen_gen2_trainers.py."),
        "classes": existing["classes"],
        "named_trainers": named,
    }

    with open(_TRAINERS_JSON, "w", encoding="utf-8") as f:
        json.dump(new_json, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Wrote {_TRAINERS_JSON}")
    print(f"  {len(named)} classes, {total_trainers} trainers total")

    # Regenerate the parallel Lua module so the client can resolve names
    # without a server roundtrip (mirrors the existing module's structure).
    write_lua_module(existing["classes"], named)
    print(f"Wrote {_TRAINERS_LUA}")
    return 0


def write_lua_module(classes: dict[str, str], named: dict[str, dict[str, str]]) -> None:
    """Write the Lua trainer module. Mirrors gen1_rby_trainers.lua format."""
    lines: list[str] = []
    lines.append("--[[")
    lines.append("  lua/games/gen2_crystal_trainers.lua — Gen 2 trainer class + named lookup.")
    lines.append("")
    lines.append("  Source: pret/pokecrystal constants/trainer_constants.asm + data/trainers/parties.asm.")
    lines.append("  Class IDs are 1-based raw values stored in wOtherTrainerClass.")
    lines.append("  Generated by tools/gen_gen2_trainers.py — every trainer instance has a name.")
    lines.append("--]]")
    lines.append("")
    lines.append("local M = {}")
    lines.append("")
    lines.append("M.CLASS_NAMES = {")
    for cid_str in sorted(classes, key=int):
        cid = int(cid_str)
        name = classes[cid_str]
        lines.append(f'    [{cid}] = {_lua_string(name)},')
    lines.append("}")
    lines.append("")
    lines.append("M.NAMED = {")
    for cid_str in sorted(named, key=int):
        cid = int(cid_str)
        instances = named[cid_str]
        entries = []
        max_iid = max(int(iid) for iid in instances)
        # Build a positional array indexed 1..max_iid; gaps get nil placeholder.
        for iid in range(1, max_iid + 1):
            name = instances.get(str(iid))
            entries.append(_lua_string(name) if name else "nil")
        lines.append(f"    [{cid}] = {{{', '.join(entries)}}},")
    lines.append("}")
    lines.append("")
    lines.append("--- Resolve a (class_id, trainer_id) pair to (class_name, trainer_name).")
    lines.append("-- trainer_id is 1-based, matching wOtherTrainerID.")
    lines.append("-- Returns empty strings if either lookup fails.")
    lines.append("function M.resolve(class_id, trainer_id)")
    lines.append("    local class_name = M.CLASS_NAMES[class_id] or \"\"")
    lines.append("    local trainer_name = \"\"")
    lines.append("    local instances = M.NAMED[class_id]")
    lines.append("    if instances then")
    lines.append("        trainer_name = instances[trainer_id] or \"\"")
    lines.append("    end")
    lines.append("    return class_name, trainer_name")
    lines.append("end")
    lines.append("")
    lines.append("return M")
    lines.append("")

    with open(_TRAINERS_LUA, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _lua_string(s: str) -> str:
    """Lua double-quoted string literal with backslash escaping."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    sys.exit(main())
