"""tools/gen_upr_polished_ini.py — the UPR ZX fork's `[Polished Crystal (U) 3.2.3]`
offsets section (docs/polished/UPR_HANDLER.md §1-§2).

Pure-python stdlib, deterministic, no ROM required: every offset comes from the
pinned `data/polished/polishedcrystal.sym` (CLEAN release build, sha1 pinned in
`data/polished_sources.lock.json`). ROMX file offsets are `bank*0x4000 + addr-0x4000`;
bank 0 uses the address as-is. The same helper pair (`flat`, `read_sym`) as
`tools/gen_upr_gen1_ini.py` is imported if that module is importable, and copied
otherwise so this tool stays standalone.

The section is offsets ONLY. Format-level facts that no INI can express (Polished's
renumbered type ids, the 2-byte `dp` species, the trainer `_tr_size`/`_tr_flags`
grammar) live in the handler class; see UPR_HANDLER.md §1.

Starter/static script sites are emitted as `Unresolved` unless the species byte is
derivable. It is NOT derivable from a `.sym`: a `.sym` gives the enclosing script
label, but the byte distance from that label to a `givepoke`/`loadwildmon` opcode
depends on how many bytes every preceding script command expands to, which only the
assembler knows. The tool emits the script label, the map file, the source line and
the species instead, so a later ROM-backed pass can resolve them without re-parsing
the sources. It never guesses an offset.

Usage:
    python tools/gen_upr_polished_ini.py                  # writes data/polished/upr_polished_entries.ini
    python tools/gen_upr_polished_ini.py --check          # exit 1 if the committed ini is stale
    python tools/gen_upr_polished_ini.py --fork <dir>     # also splice into the fork's polished_offsets.ini
    python tools/gen_upr_polished_ini.py --polished-src D  # where maps/*.asm lives
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SYM = REPO / "data" / "polished" / "polishedcrystal.sym"
LOCK = REPO / "data" / "polished_sources.lock.json"
OUT = REPO / "data" / "polished" / "upr_polished_entries.ini"
FORK_INI = "src/com/dabomstew/pkrandom/config/polished_offsets.ini"
FORK_BEGIN = ("// ---- BEGIN slink polished entries "
              "(generated by tools/gen_upr_polished_ini.py; do not edit) ----")
FORK_END = "// ---- END slink polished entries ----"

# Where the pinned Polished sources were unpacked. The maps are only needed for the
# script-site list, never for an offset.
DEFAULT_SRC_CANDIDATES = (
    pathlib.Path("F:/slink-work/cache/polished/src"),
    REPO / ".cache" / "polished" / "src",
)

SECTION = "[Polished Crystal (U) 3.2.3]"
ROM_SIZE = 2 * 1024 * 1024          # polishedcrystal-3.2.3.gbc, GBConstants.maxRomSize

# Header constants, read off the released .gbc and restated here so the section is
# self-describing. Game is the 4-byte header code at 0x13F (GBConstants.romCodeOffset).
GAME_CODE = "PKPC"
VERSION = 50                         # header 0x14C (mask ROM version) = $32; found by P6a, the Version=0 here was wrong
CRC_IN_HEADER = 0xA36C               # header 0x14E-0x14F read big-endian ($A3 $6C), as UPR reads it
VARIANT_FORM_COUNT = 46              # variant forms with their own BaseData row (P6a: 337 records = 291 + 46)
CRC32 = 0xF98367E4
NON_JAPANESE = 1
TITLE = "PKPCRYSTAL"

# Derived structural constants (not in the .sym); sources are cited in the key comments.
SPECIES_COUNT = 291        # constants/pokemon_constants.asm:317 NUM_SPECIES = $123
NUM_POKEMON = 289           # constants/pokemon_constants.asm:318 (differs from SPECIES_COUNT)
BASE_STATS_ENTRY_SIZE = 34  # constants/pokemon_data_constants.asm:35 BASE_DATA_SIZE
MOVE_LENGTH = 8             # constants/battle_constants.asm:52 MOVE_LENGTH
NUM_TMS = 74                # constants/tmhm_constants.asm:100
NUM_HMS = 6                 # constants/tmhm_constants.asm:116
NUM_TUTORS = 31             # constants/tmhm_constants.asm:156
NUM_TM_HM_TUTOR = NUM_TMS + NUM_HMS + NUM_TUTORS      # :158
TMHM_BIT_BYTES = (NUM_TM_HM_TUTOR + 7) // 8           # constants/pokemon_data_constants.asm:34

# INI key -> .sym label. Only labels the §3 capability table actually reads.
SYMBOL_KEYS: dict[str, str] = {
    "PokemonStatsOffset": "BaseData",            # data/pokemon/base_stats.asm:36
    "PokemonNamesOffset": "PokemonNames",        # data/pokemon/names.asm:1
    "MoveNamesOffset": "MoveNames",              # data/moves/names.asm
    "MoveDataOffset": "Moves",                   # data/moves/moves.asm:11
    "PokemonMovesetsTableOffset": "EvosAttacksPointers",   # data/pokemon/evos_attacks_pointers.asm
    "EvolutionMovesOffset": "EvolutionMoves",     # data/pokemon/evolution_moves.asm
    "EggMovesTableOffset": "EggSpeciesMoves",    # data/pokemon/egg_moves.asm:6
    "TrainerDataTableOffset": "TrainerGroups",    # data/trainers/party_pointers.asm:3
    "FishingWildsOffset": "FishGroups",          # data/wild/fish.asm:7
    "BCCWildsOffset": "ContestMons",             # data/wild/bug_contest_mons.asm
    "TradeTableOffset": "NPCTrades",             # data/events/npc_trades.asm:1
    "TMMovesOffset": "TMHMMoves",                # constants/tmhm_constants.asm
    "BadgeBaseLevelsOffset": "BadgeBaseLevels",  # data/wild/badge_base_levels.asm
    "TypeEffectivenessOffset": "TypeMatchups",   # data/types/type_matchups.asm
    "PokemonPicPointers": "PokemonPicPointers",  # data/pokemon/pic_pointers.asm
    "ValidPokemonLevelsOffset": "ValidPokemonLevels",   # data/pokemon/valid_levels.asm
    "TreemonWildsOffset": "TreeMons",           # data/wild/treemons.asm
    "RoamMonsterMapsOffset": "RoamMaps",        # data/wild/roammon_maps.asm
}

# The eight wild tables. Polished keeps grass and water in separate symbol-backed
# tables (unlike GSC's single blob at Gen2RomHandler.java:877), each keyed by a map id.
WILD_TABLE_LABELS = (
    "JohtoGrassWildMons", "JohtoWaterWildMons",
    "KantoGrassWildMons", "KantoWaterWildMons",
    "OrangeGrassWildMons", "OrangeWaterWildMons",
    "SwarmGrassWildMons", "SwarmWaterWildMons",
)

# Labels every section must carry. A missing one is a hard error, never a silent skip.
REQUIRED_LABELS = tuple(sorted(set(SYMBOL_KEYS.values()) | set(WILD_TABLE_LABELS) | {"VariantSpeciesAndFormTable"}))

def _load_helpers():
    """Reuse `flat`/`read_sym` from the Gen 1 generator when it is importable."""
    try:
        sys.path.insert(0, str(REPO / "tools"))
        from gen_upr_gen1_ini import flat, read_sym  # type: ignore
        return flat, read_sym, "tools/gen_upr_gen1_ini.py"
    except Exception:  # pragma: no cover - standalone fallback
        return _flat, _read_sym, "copied"


def _flat(bank: int, addr: int) -> int:
    """`bank:addr` -> flat file offset. Identical to tools/gen_upr_gen1_ini.py:142-143."""
    return addr if bank == 0 else bank * 0x4000 + (addr - 0x4000)


def _read_sym(path: pathlib.Path) -> dict[str, int]:
    """First definition wins. Identical to tools/gen_upr_gen1_ini.py:146-152."""
    out: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^([0-9a-f]{2}):([0-9a-f]{4}) (\S+)$", line)
        if m and m.group(3) not in out:
            out[m.group(3)] = _flat(int(m.group(1), 16), int(m.group(2), 16))
    return out


flat, read_sym, HELPER_SOURCE = _load_helpers()


SYM_LINE_RE = re.compile(r"^([0-9a-f]{2}):([0-9a-f]{4}) (\S+)$")


def sym_sha256(sym_path: pathlib.Path = SYM) -> str:
    return hashlib.sha256(sym_path.read_bytes()).hexdigest()


def resolve_sym(sym_path: pathlib.Path = SYM) -> dict[str, int]:
    """Load the `.sym` and hard-fail on any REQUIRED_LABELS entry that is absent."""
    sym = read_sym(sym_path)
    missing = [label for label in REQUIRED_LABELS if label not in sym]
    if missing:
        raise SystemExit(f"{sym_path}: required labels missing: " + ", ".join(sorted(missing)))
    return sym


def check_offset(offs: int) -> str:
    if not 0 <= offs < ROM_SIZE:
        raise SystemExit(f"offset 0x{offs:X} is outside the {ROM_SIZE}-byte ROM")
    return f"0x{offs:X}"


def default_src() -> pathlib.Path | None:
    for cand in DEFAULT_SRC_CANDIDATES:
        if (cand / "maps").is_dir():
            return cand
    return None


# A script-site line: `   givepoke SPECIES, FORM, LEVEL[, ...]` or `loadwildmon SPECIES[, FORM], LEVEL`
# The form argument may be a bare constant OR an OR-expression -- maps/Route35GoldenrodGate.asm:41
# is `givepoke SPEAROW, FEMALE | PLAIN_FORM, ...`. The optional group used to be a single
# [A-Z_0-9]+, so the regex BACKTRACKED past it (skipping the group entirely) whenever a `|` followed,
# and the site silently recorded Arg2=NONE. The alternation below is greedy and cannot backtrack
# into "no group", because a `,` must follow the whole expression.
SITE_RE = re.compile(
    r"^\s*(givepoke|loadwildmon)\s+([A-Z_0-9]+)\s*(?:,\s*([A-Z_0-9]+(?:\s*\|\s*[A-Z_0-9]+)*))?\s*,(?P<rest>.*)$")
LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z_0-9]*):")


def scan_script_sites(src: pathlib.Path | None, sym: dict[str, int]) -> list[dict]:
    """Every `givepoke`/`loadwildmon` call in `maps/*.asm`, with its enclosing script label.

    The label is whatever the .sym says that script starts at. The species BYTE offset is
    not derivable: the byte distance from that label to the opcode depends on how many
    bytes every preceding script command expands to, which only the assembler knows. So
    the record carries `resolved=False` and no offset is emitted.
    """
    if src is None or not (src / "maps").is_dir():
        return []
    sites: list[dict] = []
    for path in sorted((src / "maps").glob("*.asm")):
        current: str | None = None
        for lineno, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            m = LABEL_RE.match(line)
            if m:
                current = m.group(1)
                continue
            sm = SITE_RE.match(line)
            if not sm:
                continue
            sites.append({
                "kind": "GivePoke" if sm.group(1) == "givepoke" else "LoadWildMon",
                "script": current,
                "symbol_known": bool(current and current in sym),
                "sym_offset": sym.get(current) if current else None,
                "species": sm.group(2),
                "arg2": sm.group(3),
                "map": path.stem,
                "file": f"maps/{path.name}",
                "line": lineno,
                "text": line.strip(),
            })
    return sites


def render_ini(sym: dict[str, int], sites: list[dict], sym_path: pathlib.Path = SYM) -> str:
    """Deterministic INI text. Byte-identical for a given `.sym` + maps tree."""
    lock_ref = LOCK.relative_to(REPO).as_posix()
    header = [
        "// Polished Crystal 3.2.3 offsets section for the SLink fork of UPR ZX 4.6.1.",
        "// Generated by tools/gen_upr_polished_ini.py; do not edit by hand.",
        f"// sym sha256 {sym_sha256(sym_path)}  (data/polished/polishedcrystal.sym, CLEAN release build)",
        f"// Source pin: {lock_ref} (tag v3.2.3, rom sha1 6930b48af5844d373e3c9130f26d6dd1084cf4ed)",
        "// Offsets only. Format facts (renumbered type ids, 2-byte dp species, the trainer",
        "// _tr_size/_tr_flags grammar) live in PolishedCrystalRomHandler; see docs/polished/UPR_HANDLER.md.",
        "// Wild grass/water are eight separate symbol-backed tables, not GSC's single blob.",
    ]
    lines = [*header, "", SECTION]
    lines += [f"Game={GAME_CODE}", f"Title={TITLE}", f"Version={VERSION}",
              f"NonJapanese={NON_JAPANESE}", f"CRCInHeader=0x{CRC_IN_HEADER:X}",
              f"CRC32=0x{CRC32:X}"]
    lines += [f"VariantFormTableOffset={check_offset(sym['VariantSpeciesAndFormTable'])}  // VariantSpeciesAndFormTable",
              f"VariantFormCount={VARIANT_FORM_COUNT}"]
    lines += ["Polished=1", "LosslessMode=1", f"RomSize={ROM_SIZE}",
              f"SpeciesCount={SPECIES_COUNT}", f"NumPokemon={NUM_POKEMON}",
              f"BaseStatsEntrySize={BASE_STATS_ENTRY_SIZE}", f"MoveLength={MOVE_LENGTH}",
              f"TmCount={NUM_TMS}", f"HmCount={NUM_HMS}", f"TutorCount={NUM_TUTORS}",
              f"TmhmBitBytes={TMHM_BIT_BYTES}"]
    lines += ["", "// symbol-backed offsets"]
    for key, label in SYMBOL_KEYS.items():
        lines.append(f"{key}={check_offset(sym[label])}  // {label}")
    lines += ["", "// wild tables (grass/water are separate tables, keyed like UPR's WildPokemonOffset)"]
    for label in WILD_TABLE_LABELS:
        lines.append(f"{label}Offset={check_offset(sym[label])}")
    per_map = sorted(k for k in sym if re.match(
        r"^(Johto|Kanto|Orange|Swarm)(Grass|Water)WildMons\._def_(grass|water)_wildmons_", k))
    lines += ["", f"// per-map wild sub-tables ({len(per_map)} labels)"]
    for label in per_map:
        lines.append(f"WildMonSite<{label}>={check_offset(sym[label])}")
    lines += ["", "// starter/static script sites; the species BYTE offset is NOT derivable from a .sym"]
    if not sites:
        lines.append("// no maps/*.asm tree found; pass --polished-src to emit sites")
    for i, site in enumerate(sites):
        tag = f"{site['kind']}Site{i}"
        lines.append(f"{tag}=Unresolved")
        lines.append(f"{tag}Label={site['script'] or 'Unresolved'}")
        lines.append(f"{tag}ScriptOffset="
                     f"{check_offset(site['sym_offset']) if site['symbol_known'] else 'Unresolved'}")
        lines.append(f"{tag}Species={site['species']}")
        lines.append(f"{tag}Arg2={site['arg2'] or 'NONE'}")
        lines.append(f"{tag}Source={site['file']}:{site['line']}")
    return "\n".join(lines) + "\n"


def generate(src: pathlib.Path | None = None, sym_path: pathlib.Path = SYM) -> str:
    """The one entry point tests call. No subprocess, no ROM, no network."""
    sym = resolve_sym(sym_path)
    return render_ini(sym, scan_script_sites(src if src is not None else default_src(), sym), sym_path)


def splice_into_fork(fork: pathlib.Path, text: str) -> pathlib.Path:
    ini = fork / FORK_INI
    body = ini.read_text(encoding="utf-8") if ini.exists() else ""
    block = FORK_BEGIN + "\n" + text.rstrip("\n") + "\n" + FORK_END + "\n"
    if FORK_BEGIN in body:
        pre = body[:body.index(FORK_BEGIN)]
        post = body[body.index(FORK_END) + len(FORK_END) + 1:]
        body = pre + block + post
    else:
        body = body.rstrip("\n") + "\n\n" + block
    ini.write_text(body, encoding="utf-8", newline="\n")
    return ini


def check(out: pathlib.Path = OUT, src: pathlib.Path | None = None) -> int:
    """0 when the committed ini is exactly what would be generated, else 1."""
    text = generate(src)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        print(f"{out} is stale; rerun tools/gen_upr_polished_ini.py", file=sys.stderr)
        return 1
    print(f"{out} is current")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--sym", default=str(SYM))
    ap.add_argument("--polished-src", default=None, help="unpacked Polished source (for maps/*.asm)")
    ap.add_argument("--fork", default=None, help="fork checkout; splice into its polished_offsets.ini")
    ap.add_argument("--check", action="store_true", help="fail if --out is not what would be generated")
    args = ap.parse_args()
    sym_path = pathlib.Path(args.sym)
    src = pathlib.Path(args.polished_src) if args.polished_src else default_src()
    if src is None:
        print("warning: no maps/*.asm tree found; site list will be empty (pass --polished-src)",
              file=sys.stderr)
    if args.check:
        return check(pathlib.Path(args.out), src)
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = generate(src, sym_path)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    if args.fork:
        print(f"spliced into {splice_into_fork(pathlib.Path(args.fork), text)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
