#!/usr/bin/env python3
"""Generate the Gen 1 charmap pack (glyphs + text shortcuts) from source.

Today `lua/gen1/reads.lua` and `server/adapters/gen1_codec.py` each hand-transcribe
their own copy of the 256-entry glyph table (docs/purergb/research/d3/PACK_SCHEMAS.md
S10.3 / A10). pureRGB changes several of those bytes ($9E/$9F -> curly quotes,
$E9-$EB -> arrow/plus/percent, $33-$4D text shortcuts) so a second hand copy would be
a third place to get it wrong. This generator reads `constants/charmap.asm` instead.

RGBDS `charmap "STR", $XX` declares an ENCODE mapping (string -> byte); multiple
strings may target the same byte (e.g. ASCII "0" and fullwidth doubled-byte "0" both
encode to $F6 for two different display contexts). For our DECODE table (byte ->
display string) we take the last declaration in the primary (English/UI) section,
which is everything before the "; Japanese kana" section header; a kana-only
declaration only fills a byte the primary section never touched (A10: "$C0-$DF have
only Japanese aliases").

Raw bytes are authoritative for identity and round-trip (A10); this file is
strictly "how do I print these bytes for a human", never the reverse.
"""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen1_foundation as fnd  # noqa: E402

_CHARMAP_RE = re.compile(r'^\s*charmap\s+"((?:\\.|[^"\\])*)"\s*,\s*(\$[0-9A-Fa-f]+|\d+)')
_KANA_MARKER = "Japanese kana"


def _value(tok: str) -> int:
    return int(tok[1:], 16) if tok.startswith("$") else int(tok)


def parse_charmap(text: str) -> tuple[dict[int, str], int]:
    """Returns (byte -> display string for all 256 bytes, terminator byte)."""
    primary: dict[int, str] = {}
    kana: dict[int, str] = {}
    in_kana = False
    terminator = None
    for line in text.splitlines():
        if _KANA_MARKER in line:
            in_kana = True
        m = _CHARMAP_RE.match(line)
        if not m:
            continue
        text_, val = m.group(1), _value(m.group(2))
        (kana if in_kana else primary)[val] = text_
        if text_ == "@":
            terminator = val
    if terminator is None:
        raise SystemExit("charmap.asm: no '@' terminator declaration found")
    glyphs = dict(kana)
    glyphs.update(primary)  # primary/English wins wherever both exist
    for b in range(256):
        glyphs.setdefault(b, f"<${b:02X}>")
    return glyphs, terminator


def parse_text_lengths(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for key, const in (
        ("name_length", "NAME_LENGTH"),
        ("player_name_length", "PLAYER_NAME_LENGTH"),
        ("box_name_length", "BOX_NAME_LENGTH"),
    ):
        m = re.search(rf"DEF\s+{const}\s+EQU\s+(\d+)", text)
        if not m:
            raise SystemExit(f"text_constants.asm: {const} not found")
        out[key] = int(m.group(1))
    return out


def _lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_lua(glyphs: dict[int, str], shortcuts: dict[int, str], terminator: int) -> str:
    lines = [
        "-- GENERATED by tools/gen_gen1_charmap.py from pureRGB constants/charmap.asm.",
        "-- Do not hand-edit. Byte -> display text; raw bytes stay authoritative for identity.",
        "return {",
        f"    terminator = {terminator},",
        "    glyphs = {",
    ]
    for b in sorted(glyphs):
        lines.append(f'        [0x{b:02X}] = "{_lua_escape(glyphs[b])}",')
    lines.append("    },")
    lines.append("    shortcuts = {")
    for b in sorted(shortcuts):
        lines.append(f'        [0x{b:02X}] = "{_lua_escape(shortcuts[b])}",')
    lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build(foundation: str) -> dict:
    charmap_text = fnd.read_source(foundation, "constants/charmap.asm")
    text_consts = fnd.read_source(foundation, "constants/text_constants.asm")
    glyphs, terminator = parse_charmap(charmap_text)
    shortcuts = {b: glyphs[b] for b in range(0x33, 0x4E) if not glyphs[b].startswith("<$")}
    lengths = parse_text_lengths(text_consts)
    fnd.assert_source(foundation, "constants/charmap.asm", 'charmap "@",         $50')
    if terminator != 0x50:
        raise SystemExit(f"charmap terminator changed to ${terminator:02X}, expected $50")
    doc = {
        "schema": "gen1-charmap-v1",
        "terminator": terminator,
        "glyphs": {str(b): glyphs[b] for b in sorted(glyphs)},
        "shortcuts": {str(b): shortcuts[b] for b in sorted(shortcuts)},
    }
    doc.update(lengths)
    return doc


def main() -> int:
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--foundation", default="purergb")
    args = p.parse_args()

    doc = build(args.foundation)
    out_dir = fnd.data_dir(args.foundation)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "charmap.json").write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8")

    glyphs = {int(k): v for k, v in doc["glyphs"].items()}
    shortcuts = {int(k): v for k, v in doc["shortcuts"].items()}
    lua = render_lua(glyphs, shortcuts, doc["terminator"])
    (out_dir / "charmap.lua").write_text(lua, encoding="utf-8", newline="\n")

    print(f"[gen1-charmap:{args.foundation}] {len(glyphs)} glyphs, {len(shortcuts)} shortcuts "
          f"-> {out_dir / 'charmap.json'}, {out_dir / 'charmap.lua'}", file=sys.stderr)

    # Vanilla charmap.json only if a pret checkout is on hand (B3: today's vanilla
    # tables in reads.lua/gen1_codec.py are hand-transcribed, out of scope to edit).
    # pret's text_constants.asm has no BOX_NAME_LENGTH (a pureRGB addition), so a
    # missing constant is treated the same as a missing checkout: skip, don't crash.
    try:
        pret_charmap = fnd.read_source("pret", "constants/charmap.asm")
        pret_glyphs, pret_terminator = parse_charmap(pret_charmap)
        pret_lengths = parse_text_lengths(fnd.read_source("pret", "constants/text_constants.asm"))
    except SystemExit as exc:
        print(f"[gen1-charmap:pret] skipping vanilla charmap.json ({exc}) -- "
              "reads.lua / gen1_codec.py are untouched", file=sys.stderr)
        return 0
    pret_doc = {
        "schema": "gen1-charmap-v1",
        "terminator": pret_terminator,
        "glyphs": {str(b): pret_glyphs[b] for b in sorted(pret_glyphs)},
        "shortcuts": {},
    }
    pret_doc.update(pret_lengths)
    pret_out = fnd.data_dir("pret") / "charmap.json"
    pret_out.write_text(json.dumps(pret_doc, indent=1) + "\n", encoding="utf-8")
    print(f"[gen1-charmap:pret] {len(pret_glyphs)} glyphs -> {pret_out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
