"""
tools/gen_gen5_area_map.py
Generate data/games/gen5_bw/gen5_bw_areas.lua and
 data/games/gen5_bw/gen5_bw_locations.lua from
data/games/gen5_bw/area_map_bw.json  (BW1, 57 entries) and
data/games/gen5_bw/area_map_bw2.json (BW2, 73 entries, superset of BW1).

The two files are merged: BW2 adds 16 exclusive zones (Routes 19-23,
Virbank Complex, Floccesy Ranch, etc.) that never fire in BW1 ROMs.
The combined Lua table therefore serves all 4 variants correctly.

Usage:
    python tools/gen_gen5_area_map.py
"""

import json
import pathlib

ROOT      = pathlib.Path(__file__).parent.parent
DATA_DIR  = ROOT / "data" / "games" / "gen5_bw"
DATA_BW   = DATA_DIR / "area_map_bw.json"
DATA_BW2  = DATA_DIR / "area_map_bw2.json"
OUT_AREAS = DATA_DIR / "gen5_bw_areas.lua"
OUT_LOCS  = DATA_DIR / "gen5_bw_locations.lua"


def load(path: pathlib.Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def merge(bw1: list[dict], bw2: list[dict]) -> list[dict]:
    """Merge BW1 and BW2 entries; zone_id appears once (first occurrence wins)."""
    seen: dict[int, dict] = {}
    for e in bw1 + bw2:
        zid = int(e["zone_id"])
        if zid not in seen:
            seen[zid] = e
    return [seen[z] for z in sorted(seen)]


def gen_areas(entries: list[dict], bw1_count: int, bw2_count: int) -> str:
    lines = [
        "--[[ AUTO-GENERATED by tools/gen_gen5_area_map.py — DO NOT EDIT MANUALLY",
        f"     Sources: area_map_bw.json ({bw1_count} BW1 zones) +"
        f" area_map_bw2.json ({bw2_count} BW2 zones)",
        "",
        "     BW1 and BW2 share zone IDs; BW2-only zones (437+) never fire in BW1.",
        "     Single table serves all 4 variants (Black / White / Black 2 / White 2).",
        "     zone_id (u16) → area_id string used by server/state.py",
        "--]]",
        "local M = {}",
        "",
    ]

    # Deduplicate zone_id → area_id (keep first occurrence)
    seen: dict[int, str] = {}
    for e in entries:
        zid = int(e["zone_id"])
        if zid not in seen:
            seen[zid] = e["area_id"]

    for zid in sorted(seen):
        lines.append(f'M[{zid}] = "{seen[zid]}"')

    lines += ["", "return M", ""]
    return "\n".join(lines)


def gen_locations(entries: list[dict]) -> str:
    lines = [
        "--[[ AUTO-GENERATED by tools/gen_gen5_area_map.py — DO NOT EDIT MANUALLY",
        "     Sources: area_map_bw.json + area_map_bw2.json",
        "--]]",
        "local M = {}",
        "",
    ]

    # area_id → display name (longest name wins on duplicate area_ids)
    names: dict[str, str] = {}
    for e in entries:
        aid = e["area_id"]
        name = e["name"]
        if aid not in names or len(name) > len(names[aid]):
            names[aid] = name

    for aid in sorted(names):
        escaped = names[aid].replace('"', '\\"')
        lines.append(f'M["{aid}"] = "{escaped}"')

    lines += ["", "return M", ""]
    return "\n".join(lines)


def main():
    bw1 = load(DATA_BW)
    bw2 = load(DATA_BW2)
    entries = merge(bw1, bw2)

    unique_zones = len({e["zone_id"] for e in entries})
    areas_lua = gen_areas(entries, len(bw1), len(bw2))
    OUT_AREAS.write_text(areas_lua, encoding="utf-8")
    print(f"Wrote {OUT_AREAS}  ({unique_zones} unique zones)")

    locs_lua = gen_locations(entries)
    OUT_LOCS.write_text(locs_lua, encoding="utf-8")
    unique_areas = len({e["area_id"] for e in entries})
    print(f"Wrote {OUT_LOCS}  ({unique_areas} unique areas)")


if __name__ == "__main__":
    main()
