#!/usr/bin/env python3
"""Generate the Gen 1 item-name table from pret/pokered raw asm.

Reads:
    .cache/pret/pokered/data/items/names.asm    (ItemNames, in item-id order)

Writes:
    server/data/items/gen1.py

WHY THIS EXISTS. The table was hand-written and 17 of its 45 entries were wrong --
every id from $2D upward was shifted by one, so `X Accuracy` named the Bike Voucher,
`Poké Doll` named a Full Heal, and `X Special` named Oak's Parcel. The Gen 1 adapter
uses this table for held-item and bag rendering, so the player was shown a plausible
wrong item rather than a blank.

Hand-editing 17 constants would fix today's table and leave tomorrow's to luck. The
names are in the decomp in id order; read them.

`ItemNames` is a flat `li "..."` list starting at item id $01 (id $00 is NO_ITEM and
has no entry). Unused ids carry the placeholder "?????" and are skipped -- naming them
would be worse than leaving them unknown. TMs and HMs are NOT in this list: the engine
formats those names at runtime from the id (`GetItemName` special-cases
`item >= HM01`), so they are generated here the same way.
"""
from __future__ import annotations

import os
import re

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_THIS_DIR, ".."))


def _find_pret() -> str:
    """Locate the pokered checkout, searching upward from the repo.

    A git WORKTREE has no .cache of its own -- it lives under the main repo's
    .claude/worktrees/, so the decomp is several directories up.
    """
    env = os.environ.get("SLINK_PRET_DIR")
    if env:
        return env
    d = _REPO
    for _ in range(6):
        cand = os.path.join(d, ".cache", "pret", "pokered")
        if os.path.isdir(cand):
            return cand
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    return os.path.join(_REPO, ".cache", "pret", "pokered")


_PRET = _find_pret()
_OUT = os.path.join(_REPO, "server", "data", "items", "gen1.py")

_LI_RE = re.compile(r'^\s*li\s+"([^"]*)"')

# The charset stores é as its own tile; the decomp writes it lowercase inside
# otherwise-uppercase names. Present them the way the rest of the UI spells them.
_PRETTY = {
    "POKé BALL": "Poké Ball", "POKéDEX": "Pokédex", "POKé DOLL": "Poké Doll",
    "PP UP": "PP Up", "OAK's PARCEL": "Oak's Parcel", "S.S.TICKET": "S.S. Ticket",
    "TM01": "TM01",
}


def _title(name: str) -> str:
    if name in _PRETTY:
        return _PRETTY[name]
    return " ".join(w.capitalize() if w.isalpha() else w for w in name.split(" "))


def parse_item_names(path: str) -> dict[int, str]:
    """`item id → display name`, in the decomp's own order. $01 is the first entry."""
    names: dict[int, str] = {}
    item_id = 0
    with open(path, encoding="utf-8") as f:
        for raw in f:
            m = _LI_RE.match(raw)
            if not m:
                continue
            item_id += 1
            name = m.group(1)
            if name.strip("?") == "":       # "?????" — an unused id
                continue
            names[item_id] = _title(name)
    return names


def build() -> dict[int, str]:
    names = parse_item_names(os.path.join(_PRET, "data", "items", "names.asm"))
    if len(names) < 40:
        raise SystemExit(f"only parsed {len(names)} item names — is names.asm intact?")
    # TM01-TM50 = $C9-$FA, HM01-HM05 = $C4-$C8 (constants/item_constants.asm).
    for i in range(1, 6):
        names[0xC3 + i] = f"HM{i:02d}"
    for i in range(1, 51):
        names[0xC8 + i] = f"TM{i:02d}"
    return names


def render(names: dict[int, str]) -> str:
    lines = [
        '"""server/data/items/gen1.py — Gen 1 (Red/Blue/Yellow) item name table.',
        "",
        "GENERATED by tools/gen_gen1_items.py from pret/pokered data/items/names.asm.",
        "Do not hand-edit: the hand-written version had every id from $2D up shifted by one.",
        '"""',
        "",
        "",
        "ITEM_NAMES = {",
    ]
    row: list[str] = []
    for item_id in sorted(names):
        row.append(f'0x{item_id:02X}: "{names[item_id]}",')
        if len(row) == 4:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    out = render(build())
    with open(_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print(f"wrote {_OUT}")
