"""Generate SPECIES_TYPES dict for server/pokemon_data.py from RR Base_Stats.c.

Parses Base_Stats.c and species.h from funnotbun/funnotbun.github.io to build
a mapping of every RR species internal ID to its (type1, type2) tuple using
Gen III type byte values.

Usage:
    python tools/gen_rr_types.py

Outputs data/rr_types.json and prints a Python dict literal for pasting into
pokemon_data.py as SPECIES_TYPES.
"""

import json
import os
import re
import urllib.request

BASE_STATS_URL = (
    "https://raw.githubusercontent.com/funnotbun/funnotbun.github.io"
    "/main/data/species/Base_Stats.c"
)
SPECIES_H_URL = (
    "https://raw.githubusercontent.com/funnotbun/funnotbun.github.io"
    "/main/data/species/species.h"
)
OUTPUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "data", "rr_types.json")

# Gen III type constants (from pret/pokefirered include/constants/pokemon.h)
# CFRU adds TYPE_FAIRY = 0x12 (18)
TYPE_MAP = {
    "TYPE_NORMAL":   0,  "TYPE_FIGHTING": 1,  "TYPE_FLYING":   2,
    "TYPE_POISON":   3,  "TYPE_GROUND":   4,  "TYPE_ROCK":     5,
    "TYPE_BUG":      6,  "TYPE_GHOST":    7,  "TYPE_STEEL":    8,
    "TYPE_MYSTERY":  9,  "TYPE_FIRE":    10,  "TYPE_WATER":   11,
    "TYPE_GRASS":   12,  "TYPE_ELECTRIC":13,  "TYPE_PSYCHIC": 14,
    "TYPE_ICE":     15,  "TYPE_DRAGON":  16,  "TYPE_DARK":    17,
    "TYPE_FAIRY":   18,  "TYPE_ROOSTLESS": 19,  "TYPE_STELLAR": 20,
}


def main():
    print("Fetching species.h ...")
    data_h = urllib.request.urlopen(SPECIES_H_URL).read().decode()
    name_to_id: dict[str, int] = {}
    for m in re.finditer(r"#define\s+(SPECIES_\w+)\s+0x([0-9A-Fa-f]+)", data_h):
        name, num = m.group(1), int(m.group(2), 16)
        if name not in ("SPECIES_NONE", "SPECIES_EGG") and num > 0:
            name_to_id[name] = num
    print(f"  Parsed {len(name_to_id)} species IDs from species.h")

    print("Fetching Base_Stats.c (1MB+, may take a moment) ...")
    data_bs = urllib.request.urlopen(BASE_STATS_URL).read().decode()
    print(f"  Downloaded {len(data_bs)} bytes")

    # Parse each [SPECIES_XXX] block for .type1 and .type2
    species_types: dict[int, tuple[int, int]] = {}
    # Split by species blocks
    blocks = re.split(r'\[SPECIES_', data_bs)
    for block in blocks[1:]:  # skip header before first species
        # Get species name
        name_m = re.match(r'(\w+)\]', block)
        if not name_m:
            continue
        sname = "SPECIES_" + name_m.group(1)
        sid = name_to_id.get(sname)
        if sid is None:
            continue

        # Extract type1 and type2
        t1_m = re.search(r'\.type1\s*=\s*(TYPE_\w+)', block)
        t2_m = re.search(r'\.type2\s*=\s*(TYPE_\w+)', block)
        if not t1_m:
            continue
        t1_str = t1_m.group(1).strip()
        t2_str = t2_m.group(1).strip() if t2_m else t1_str

        t1 = TYPE_MAP.get(t1_str)
        t2 = TYPE_MAP.get(t2_str)
        if t1 is None or t2 is None:
            print(f"  WARNING: Unknown type for {sname}: {t1_str}={t1}, {t2_str}={t2}")
            continue
        species_types[sid] = (t1, t2)

    print(f"  Parsed types for {len(species_types)} species")

    # Write JSON
    json_out = {str(k): list(v) for k, v in sorted(species_types.items())}
    with open(OUTPUT, "w") as f:
        json.dump(json_out, f, separators=(",", ":"))
    print(f"Wrote {len(json_out)} entries to {OUTPUT} "
          f"({os.path.getsize(OUTPUT)} bytes)")

    # Print a few samples for verification
    print("\nSample entries:")
    samples = [
        ("Teddiursa-Sevii", 1278),
        ("Ursaring-Sevii", 1279),
        ("Vulpix-Alola", 1025),
        ("Zorua-Hisui", 1280),
        ("Kingambit", 936),
        ("Bulbasaur", 1),
    ]
    type_names = {v: k.replace("TYPE_", "") for k, v in TYPE_MAP.items()}
    for label, sid in samples:
        pair = species_types.get(sid)
        if pair:
            print(f"  {sid:>5} {label:25s} → {type_names.get(pair[0],'?')}/{type_names.get(pair[1],'?')} {pair}")
        else:
            print(f"  {sid:>5} {label:25s} → NOT FOUND")

    # Generate Python dict literal for SPECIES_TYPES
    py_out = os.path.join(os.path.dirname(OUTPUT), "rr_types_dict.txt")
    with open(py_out, "w") as f:
        f.write("# Auto-generated by tools/gen_rr_types.py — do not edit manually.\n")
        f.write("# Maps RR internal species ID -> (type1, type2) using Gen III type byte values.\n")
        f.write("SPECIES_TYPES: dict[int, tuple[int, int]] = {\n")
        items = sorted(species_types.items())
        for i, (sid, (t1, t2)) in enumerate(items):
            sep = "," if i < len(items) - 1 else ""
            f.write(f"    {sid}:({t1},{t2}){sep}\n")
        f.write("}\n")
    print(f"\nPython dict written to {py_out}")


if __name__ == "__main__":
    main()
