"""Generate clean-cartridge admission profiles from verified canonical binaries.

A complete clean-ROM hash proves every ROM domain canonical. This catalog does
not authorize randomized, companion-patched, external, or AP cartridges.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.gen_gen1_codec_data import digest, lua_value  # noqa: E402
from tools.verify_canonical_sources import verify  # noqa: E402

OUTPUT = ROOT / "data/games/gen1_rby/admission_profiles.json"
LUA_OUTPUT = OUTPUT.with_name("gen1_admission_profiles.lua")


def build_profiles():
    evidence = verify(rom_dir=ROOT)
    if evidence["status"] != "pass":
        raise ValueError("canonical source gate failed: " + "; ".join(evidence["failures"]))
    lock = json.loads((ROOT / "data/pret_sources.lock.json").read_text(encoding="utf-8"))
    codec = json.loads((ROOT / "data/games/gen1_rby/party_codec.json").read_text(encoding="utf-8"))
    profiles = {}
    for variant, target in (("red", "pokered"), ("blue", "pokeblue"), ("yellow", "pokeyellow")):
        pin = lock["clean_roms"][target]
        profile = {
            "schema": "gen1-rby-clean-content-v1", "variant": variant,
            "final_rom_sha1": pin["sha1"], "source_commit": lock["sources"][pin["source"]]["commit"],
            "rom_sha256": hashlib.sha256((ROOT / pin["filename"]).read_bytes()).hexdigest(),
            "party_codec": "gen1-rby-party-v1", "codec_data_sha256": codec["content_sha256"],
            "patch_version": 0, "capabilities": {"panel": False, "sfx": False, "pc_trade": False},
            "provenance": "canonical-whole-rom",
        }
        profile["content_profile_hash"] = digest(profile)
        profiles[variant] = profile
    return {"schema": "gen1-rby-admission-catalog-v1", "profiles": profiles}


def outputs(data):
    lua = lua_value(data)
    return {OUTPUT: json.dumps(data, indent=2, sort_keys=True) + "\n",
            LUA_OUTPUT: "-- Generated by tools/gen_gen1_admission_profiles.py; do not edit.\nreturn " + lua + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs(build_profiles()).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit("FAIL: admission profile drift: " + str(path.relative_to(ROOT)))
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    print("Clean RBY admission profiles: PASS (three complete canonical ROM hashes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
