"""Derive wild encounter witnesses from the already source-verified battle sites.

InitWildBattle+5 is before LoadEnemyMonData but after wIsInBattle=1; species and
level are wEnemyMonSpecies2/wCurEnemyLevel, never the stale enemy battle struct.
EndOfBattle entry precedes evolution and resetting battle variables. Both normal
and Safari battles traverse these sites. The existing static generator verifies
their unique StartBattle/EndOfBattle ordering and the engine's ghost predicates.
"""

import argparse
import copy
import hashlib
import json
from pathlib import Path

from gen_gen1_acquisition_sources import TITLES, symbols
from gen_gen1_grant_sites import lua
from gen_gen1_static_sites import build as static_sites

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data/games/gen1_rby/wild_encounter_sites.json"
LUA = OUTPUT.with_name("gen1_wild_encounter_sites.lua")


def build():
    base = static_sites()
    result = {
        "schema": "rby-wild-encounter-sites-v1",
        "static_source_sha256": base["sha256"],
        "titles": {},
    }
    for variant, (source, target) in TITLES.items():
        old = base["titles"][variant]
        syms = symbols(ROOT / ".cache/pret" / source / (target + ".sym"))
        safari_path = ROOT / ".cache/pret" / source / "engine/battle/init_battle_variables.asm"
        safari = safari_path.read_text(encoding="utf-8")
        assert (
            "cp SAFARI_ZONE_EAST\n\tjr c, .notSafariBattle\n\tcp SAFARI_ZONE_CENTER_REST_HOUSE\n"
            "\tjr nc, .notSafariBattle\n\tld a, BATTLE_TYPE_SAFARI\n\tld [wBattleType], a"
        ) in safari
        result["titles"][variant] = {
            "source_commit": old["source_commit"],
            "clean_sha1": old["clean_sha1"],
            "addresses": {**old["addresses"], "wNumBagItems": syms["wNumBagItems"][1]},
            "sites": {
                "begin": copy.deepcopy(old["began"]),
                "end": copy.deepcopy(old["battle_end"]),
            },
            "battle_types": old["battle_types"],
            "tower_maps": old["tower_map_ids"],
            "silph_scope": 0x48,
            "ghost_script_map": 0x93,
            "safari_init_source_sha256": hashlib.sha256(safari_path.read_bytes()).hexdigest(),
        }
    result["sha256"] = hashlib.sha256(
        json.dumps(result, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    value = build()
    outputs = {
        OUTPUT: json.dumps(value, sort_keys=True, indent=2) + "\n",
        LUA: "-- Generated by tools/gen_gen1_wild_encounter_sites.py.\nreturn " + lua(value) + "\n",
    }
    for path, text in outputs.items():
        if args.check:
            assert path.read_text(encoding="utf-8") == text, str(path) + " differs"
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
    print("Verified normal/Safari begin and EndOfBattle sites for Red, Blue and Yellow")


if __name__ == "__main__":
    main()
