"""tools/gen_upr_gen1_ini.py — the UPR ZX fork's `[PureRed (U)]`/`[PureBlue (U)]`/
`[PureGreen (U)]` entries (docs/purergb/PLAN.md §6 M5).

Every symbol-backed offset comes from the pinned `.sym` (data/purergb/poke<title>.sym,
bank:addr -> flat); every raw immediate (statics, starters) is located by pattern in
each title's ROM and verified there, so a title-specific shift (MissingNo's immediates
sit one byte later in Blue and two in Green) is found rather than assumed. Class counts
come from data/games/gen1_purergb/trainers.json, statics from static_encounters.json,
CRCs from admission.json. The six INI corrections of the 2026-09-18 fact-check are
applied (key names, MapBanks/MapAddresses, movesets bound, per-title immediates, merged
double-encoded statics, OldRodOffset = the first `lb bc` site).

Usage:
    python tools/gen_upr_gen1_ini.py                 # writes data/purergb/upr_pure_entries.ini
    python tools/gen_upr_gen1_ini.py --fork .cache/slink-upr   # also splices it into the fork's gen1_offsets.ini
    python tools/gen_upr_gen1_ini.py --check         # exit 1 if the committed copy is stale

ROMs are read from .cache/purergb/poke<title>.gbc (--roms DIR) and the overlay builds from
.cache/purergb-overlay/poke<title>.gbc (--overlay-roms DIR).
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
PACK = REPO / "data" / "games" / "gen1_purergb"
SYMS = REPO / "data" / "purergb"
OUT = REPO / "data" / "purergb" / "upr_pure_entries.ini"
FORK_INI = "src/com/dabomstew/pkrandom/config/gen1_offsets.ini"
FORK_BEGIN = "// ---- BEGIN slink pureRGB entries (generated by tools/gen_upr_gen1_ini.py; do not edit) ----"
FORK_END = "// ---- END slink pureRGB entries ----"

TITLES = {"purered": "PureRed", "pureblue": "PureBlue", "puregreen": "PureGreen"}
GAME_NAME = {"purered": "POKEMON RED", "pureblue": "POKEMON BLUE", "puregreen": "POKEMON GREEN"}
# One entry per (kind, title): the clean pureRGB builds and the SLink companion-overlay builds
# (tools/gen1_foundation.py `purergb` / `purergb_overlay`). The overlay shifts code in banks
# 0/1/3 and carries its own header CRC, so it needs its own entry or Gen1RomHandler's generic
# header fallback would hand it the VANILLA Red/Blue offsets.
KINDS = {
    "clean": {"roms": REPO / ".cache" / "purergb", "sym": "poke{x}.sym",
              "admission": "admission.json", "section": "{name} (U)"},
    "overlay": {"roms": REPO / ".cache" / "purergb-overlay", "sym": "pure{x}_slink.sym",
                "admission": "admission_overlay.json", "section": "{name} overlay (U)"},
}

# Symbol-backed scalar keys: INI key -> (.sym label, delta).
SYMBOL_KEYS: dict[str, tuple[str, int]] = {
    "PokedexOrder": ("PokedexOrder", 0),
    "PokemonNamesOffset": ("MonsterNames", 0),
    "PokemonStatsOffset": ("BaseStats", 0),
    "MewStatsOffset": ("BaseStats", 150 * 35),          # Mew is inline in pureRGB: record 151 of a 35-byte table
    "NonDexStatsOffset": ("NonDexMonsBaseStats", 0),    # documentary: the fork never reads or writes these 13 records
    "WildPokemonTableOffset": ("WildDataPointers", 0),  # correction 1: UPR's key name, not the label
    "OldRodOffset": ("ItemUseOldRod", 13),              # correction 6: the FIRST `lb bc, level, species` site (verified below)
    "GoodRodOffset": ("GoodRodMons", 0),
    "GoodRodMonsOcean": ("GoodRodMonsOcean", 0),
    "SuperRodTableOffset": ("SuperRodData", 0),
    "MapNameTableOffset": ("ExternalMapEntries", 0),
    "MapBanks": ("MapHeaderBanks", 0),                  # correction 2
    "MapAddresses": ("MapHeaderPointers", 0),
    "MoveDataOffset": ("Moves", 0),
    "MoveNamesOffset": ("MoveNameJumpTable", 0),        # pointer table (NameTablesArePointerTables=1)
    "ItemNamesOffset": ("ItemNameJumpTable", 0),
    "TypeEffectivenessOffset": ("TypeEffects", 0),
    "PokemonMovesetsTableOffset": ("EvosMovesPointerTable", 0),
    "TrainerDataTableOffset": ("TrainerDataPointers", 0),
    "ExtraTrainerMovesTableOffset": ("TeamMoves", 0),   # never written on a lossless entry (documentary)
    "GymLeaderMovesTableOffset": ("LoneMoves", 1),      # never written on a lossless entry (documentary)
    "TMMovesOffset": ("TechnicalMachines", 0),
    "SpecialMapList": ("HiddenEventMaps", 0),
    "SpecialMapPointerTable": ("HiddenEventPointers", 0),
    "HiddenItemRoutine": ("HiddenItems", 0),
    "TradeTableOffset": ("TradeMons", 0),               # correction 1
}
SYMBOL_ARRAY_KEYS: dict[str, list[tuple[str, int]]] = {
    "TrainerClassNamesOffsets": [("TrainerNames", 0)],
    "HiddenItemRoutineEntries": [("HiddenItems", 0), ("HiddenItems2", 0), ("HiddenItems3", 0), ("HiddenItems5", 0)],
    "OldRodOffsets": [("ItemUseOldRod", 13), ("ItemUseOldRod", 18)],
}
# Fixed scalars (same for every title). Absent on purpose, and why:
#   IntroPokemonOffset/IntroCryOffset  - pureRGB has no intro site; absence is what stops the rom[0] write
#   TextDelayFunctionOffset/PCPotionOffset/PikachuEvoJumpOffset/CatchingTutorialMonOffset - tweaks; a
#       lossless entry offers none (miscTweaksAvailable() == 0) so the sites are not published
#   PatchPokedex/StarterPokedex*/CanChangeStarterText/StarterTextOffsets/CanChangeTrainerText - code or
#       text injection on starter/trainer randomization; never on a lossless entry
#   PokemonMovesetsExtraSpaceOffset=0 - no free tail after the evos block (BaseStats follows it)
#   *Tweak files - the IPS tweaks are vanilla-only
#   TMText[] - pureRGB's TM description text is not mapped; TM randomization leaves it stale
FIXED_KEYS: dict[str, str] = {
    "Version": "0",
    "NonJapanese": "1",
    "Type": "RB",
    "ExtraTableFile": "rby_english",   # display only: names are never re-encoded on a lossless entry
    "LosslessMode": "1",
    "InternalPokemonCount": "190",
    "PokemonNamesLength": "10",
    "BaseStatsEntrySize": "35",
    "MoveCount": "165",
    "ItemNameCount": "83",
    "NameTablesArePointerTables": "1",
    "PokemonMovesetsExtraSpaceOffset": "0",
    "MapNameInternalRowSize": "5",
    "OldRodPairCount": "2",
    "GoodRodPairCount": "4",
    "TrainerClassCount": "56",
    "TrainerRecordGrammars": "1",
    "TrainerTaggingDisabled": "1",
    "TradeTableSize": "10",
    "TradeNameLength": "11",
    "TradesUnused": "[]",
    "StaticPokemonSupport": "1",
    # pureRGB type ids UPR has no name for, mapped onto its hack-only slots so a byte round-trips
    # (TYPELESS $06, CRYSTAL $09, BONEMERANG $0A, TRI $11, FLOATING $12, MAGMA $13)
    "ExtraTypes": "[06=GAS,09=WOOD,0A=ABNORMAL,11=TRI,12=WIND,13=SOUND]",
}
NON_DEX_CLASSES = ("spirit", "form", "missingno")
STARTER_BYTES = (0xB0, 0xB1, 0x99)   # STARTER1/2/3 = CHARMANDER/SQUIRTLE/BULBASAUR EQUs, inlined
# Gameplay-critical starter sites (W2), symbol-relative so the overlay build (bank 0 shifts)
# resolves them too: OaksLab pick logic + StarterToPartyID + the postgame ball-hide branch
# (HallOfFame.asm `cp STARTER1` / `cp STARTER2`; review cx-795d1423 #4), plus StarterDexArray.
STARTER_SITES: dict[int, list[tuple[str, int]]] = {
    1: [("OaksLabChoseStarterScript", 4), ("OaksLabCharmanderPokeBallText", 5),
        ("OaksLabBulbasaurPokeBallText", 2), ("StarterToPartyID", 3),
        ("HallOfFameOakCongratulationsScript", 0x30)],
    2: [("OaksLabChoseStarterScript", 8), ("OaksLabSquirtlePokeBallText", 5),
        ("OaksLabCharmanderPokeBallText", 2), ("StarterToPartyID", 8),
        ("HallOfFameOakCongratulationsScript", 0x36)],
    3: [("OaksLabBulbasaurPokeBallText", 5), ("OaksLabSquirtlePokeBallText", 2)],
}
WCUROPPONENT, WCURENEMYLEVEL = b"\x59\xd0", b"\x2f\xd1"
WENGAGEDCLASS, WENGAGEDSET = b"\x2d\xcd", b"\x2e\xcd"


def flat(bank: int, addr: int) -> int:
    return addr if bank == 0 else bank * 0x4000 + (addr - 0x4000)


def read_sym(path: pathlib.Path) -> dict[str, int]:
    out = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^([0-9a-f]{2}):([0-9a-f]{4}) (\S+)$", line)
        if m and m.group(3) not in out:
            out[m.group(3)] = flat(int(m.group(1), 16), int(m.group(2), 16))
    return out


def script_static_sites(rom: bytes, species: int, level: int) -> list[tuple[int, int]]:
    """(species_offset, level_offset) for every immediate-write site of a scripted static."""
    pats = [
        (b"\x3e" + bytes([species]) + b"\xea" + WCUROPPONENT + b"\x3e" + bytes([level]) + b"\xea" + WCURENEMYLEVEL, 1, 6),
        (b"\x3e" + bytes([level]) + b"\xea" + WCURENEMYLEVEL + b"\x3e" + bytes([species]) + b"\xea" + WCUROPPONENT, 6, 1),
        (b"\x3e" + bytes([species]) + b"\xea" + WENGAGEDCLASS + b"\x3e" + bytes([level]) + b"\xea" + WENGAGEDSET, 1, 6),
    ]
    hits = []
    for pat, s_off, l_off in pats:
        start = 0
        while (i := rom.find(pat, start)) != -1:
            hits.append((i + s_off, i + l_off))
            start = i + 1
    return sorted(hits)


def object_rows(rom: bytes, sym: dict[str, int], map_id: int) -> list[int]:
    """Offsets of every 8-byte trainer/pokemon object_event row of a map (species at +6)."""
    bank = rom[sym["MapHeaderBanks"] + map_id]
    hdr = flat(bank, rom[sym["MapHeaderPointers"] + map_id * 2] | rom[sym["MapHeaderPointers"] + map_id * 2 + 1] << 8)
    cb = rom[hdr + 9]
    ncons = bin(cb & 0xF).count("1")
    obj_ptr = hdr + 10 + ncons * 11
    obj = flat(bank, rom[obj_ptr] | rom[obj_ptr + 1] << 8)
    offs = obj + 2 + rom[obj + 1] * 4          # border byte, warp count, warps
    offs += 1 + rom[offs] * 3                  # bg events
    n = rom[offs]
    offs += 1
    rows = []
    for _ in range(n):
        tid = rom[offs + 5]
        if tid & 0x40:
            rows.append(offs)
            offs += 8
        elif tid & 0x80 and rom[offs + 6] != 0:
            offs += 7
        else:
            offs += 6
    return rows


def statics_for(rom: bytes, sym: dict[str, int], records: list[dict]) -> list[dict]:
    """One StaticPokemon record per encounter; sites sharing (species, event_flag) are merged
    (correction 5: the roof Zapdos, the two Moltres) so every copy of one encounter is
    written together."""
    merged: dict = {}
    order: list = []
    used_script: set[tuple[int, int]] = set()
    used_rows: set[int] = set()
    for rec in records:
        sp, lv = rec["species"], rec["level"]
        if rec["kind"] == "script":
            cands = [h for h in script_static_sites(rom, sp, lv) if h not in used_script]
            if not cands:
                raise SystemExit(f"no immediate-write site for {rec}")
            site = cands[0]
            used_script.add(site)
        elif rec["kind"] == "object_event":
            cands = [r for r in object_rows(rom, sym, rec["map_id"])
                     if r not in used_rows and rom[r + 6] == sp and rom[r + 7] == lv]
            if not cands:
                raise SystemExit(f"no object_event row for {rec}")
            used_rows.add(cands[0])
            site = (cands[0] + 6, cands[0] + 7)
        else:
            raise SystemExit(f"unknown static kind {rec}")
        key = (sp, rec["event_flag"]) if rec["event_flag"] else (sp, rec["cite"])
        if key not in merged:
            merged[key] = {"name": rec["species_const"], "maps": [], "species": [], "level": []}
            order.append(key)
        merged[key]["maps"].append(rec["map_const"])
        merged[key]["species"].append(site[0])
        merged[key]["level"].append(site[1])
    # an encounter encoded as an object row may ALSO be written inline by its script (the
    # roof Zapdos: object row + `wEngagedTrainerClass` immediates); every unclaimed inline
    # site of a flagged encounter's (species, level) belongs to that record
    for key in order:
        sp, flag = key
        if not (isinstance(flag, str) and flag.startswith("EVENT_")):
            continue
        lv = rom[merged[key]["level"][0]]
        for site in script_static_sites(rom, sp, lv):
            if site not in used_script:
                used_script.add(site)
                merged[key]["species"].append(site[0])
                merged[key]["level"].append(site[1])
                merged[key]["maps"].append("inline")
    return [merged[k] for k in order]


def build_entry(title: str, rom: bytes, sym: dict[str, int], pack: dict, kind: str = "clean") -> tuple[str, dict]:
    keys: dict[str, str] = {}
    keys["Game"] = GAME_NAME[title]
    for k in ("Version", "NonJapanese", "Type", "ExtraTableFile"):
        keys[k] = FIXED_KEYS[k]
    adm = pack["admission"]
    keys["CRCInHeader"] = "0x" + adm["header_crc"]
    keys["CRC32"] = adm["crc32"]
    for k, v in FIXED_KEYS.items():
        keys.setdefault(k, v)
    for k, (label, delta) in SYMBOL_KEYS.items():
        keys[k] = f"0x{sym[label] + delta:X}"
    for k, parts in SYMBOL_ARRAY_KEYS.items():
        keys[k] = "[" + ", ".join(f"0x{sym[label] + d:X}" for label, d in parts) + "]"
    # correction 3 (re-measured): the repackable evos/moves block runs from the byte after
    # the 190-entry pointer table up to BaseStats, which shares the section
    keys["PokemonMovesetsDataSize"] = f"0x{sym['BaseStats'] - (sym['EvosMovesPointerTable'] + 190 * 2):X}"
    # class counts: index 0 is UPR's pad, then one count per class in id order
    classes = pack["trainers"]["classes"]
    ids = sorted(int(i) for i in classes)
    assert ids == list(range(ids[0], ids[0] + len(ids))), "trainer class ids are not contiguous"
    keys["TrainerDataClassCounts"] = "[" + ", ".join(["0"] + [str(classes[str(i)]["party_count"]) for i in ids]) + "]"
    assert len(ids) == int(FIXED_KEYS["TrainerClassCount"])
    # non-dex internal ids (spirits, forms, MissingNo): kept opaque and verbatim by the fork
    nondex = sorted(int(i) for i, s in pack["species"].items() if s["classification"] in NON_DEX_CLASSES)
    keys["NonDexSpecies"] = "[" + ", ".join(f"0x{i:02X}" for i in nondex) + "]"
    # starters: every site must hold the expected EQU byte in this title
    for n, sites in STARTER_SITES.items():
        sites = [sym[label] + d for label, d in sites] + [sym["StarterDexArray"] + n - 1]
        for o in sites:
            if rom[o] != STARTER_BYTES[n - 1]:
                raise SystemExit(f"{title}: starter{n} site 0x{o:X} holds 0x{rom[o]:02X}, not 0x{STARTER_BYTES[n-1]:02X}")
        keys[f"StarterOffsets{n}"] = "[" + ", ".join(f"0x{o:X}" for o in sites) + "]"
    # fishing immediates: the two `lb bc, level, species` sites (01 ss ll)
    for o in (sym["ItemUseOldRod"] + 13, sym["ItemUseOldRod"] + 18):
        if rom[o] != 0x01 or rom[o + 2] != 10:
            raise SystemExit(f"{title}: old rod site 0x{o:X} is {rom[o:o+3].hex()}, not `lb bc, 10, species`")
    for o in (sym["GoodRodMons"], sym["GoodRodMonsOcean"]):
        if rom[o + 8:o + 10] != b"\xff\xff":
            raise SystemExit(f"{title}: good rod table 0x{o:X} lacks the -1,-1 terminator after 4 pairs")
    statics = statics_for(rom, sym, pack["statics"]["records"])
    ghost = [s for s in statics if s["name"] == "RESTLESS_SOUL"]
    lines = ["[" + KINDS[kind]["section"].format(name=TITLES[title]) + "]"]
    for k, v in keys.items():
        lines.append(f"{k}={v}")
    for s in statics:
        tag = "StaticPokemonGhostMarowak{}" if s in ghost else "StaticPokemon{}"
        sp = ", ".join(f"0x{o:X}" for o in s["species"])
        lv = ", ".join(f"0x{o:X}" for o in s["level"])
        lines.append(f"{tag}={{Species=[{sp}], Level=[{lv}]}} // {s['name']} @ {', '.join(s['maps'])}")
    return "\n".join(lines) + "\n", keys


def generate(rom_dir: pathlib.Path, overlay_dir: pathlib.Path | None = None) -> str:
    import hashlib
    pack = {
        "trainers": json.loads((PACK / "trainers.json").read_text(encoding="utf-8")),
        "statics": json.loads((PACK / "static_encounters.json").read_text(encoding="utf-8")),
        "species": json.loads((PACK / "species_index.json").read_text(encoding="utf-8"))["species"],
    }
    sections = []
    for kind, spec in KINDS.items():
        roms = {"clean": rom_dir, "overlay": overlay_dir or KINDS["overlay"]["roms"]}[kind]
        admission = json.loads((PACK / spec["admission"]).read_text(encoding="utf-8"))
        by_title = {v["title"]: dict(v, sha1=k) for k, v in admission.items()}
        symbol_view = {}
        for title in TITLES:
            rom_path = roms / f"poke{title[4:]}.gbc"
            rom = rom_path.read_bytes()
            if hashlib.sha1(rom).hexdigest() != by_title[title]["sha1"]:
                raise SystemExit(f"{rom_path} is not the admitted {kind} {title} ROM")
            sym = read_sym(SYMS / spec["sym"].format(x=title[4:]))
            text, keys = build_entry(title, rom, sym, dict(pack, admission=by_title[title]), kind)
            sections.append(text)
            symbol_view[title] = {k: keys[k] for k in list(SYMBOL_KEYS) + list(SYMBOL_ARRAY_KEYS)}
        # the three builds share one layout except where bank $1D code shifts by a byte per
        # title (HiddenItems* and MissingNo's immediates); report what differs, per title is right
        differing = sorted(k for k in symbol_view["purered"]
                           if len({v[k] for v in symbol_view.values()}) != 1)
        print(f"{kind}: title-specific symbol-backed keys: " + (", ".join(differing) or "none"), file=sys.stderr)
    header = (
        "// pureRGB entries for the SLink fork of UPR ZX 4.6.1 (generated by tools/gen_upr_gen1_ini.py).\n"
        "// Symbol-backed offsets from data/purergb/*.sym; immediates located and verified per title.\n"
        "// LosslessMode=1: load->save is byte-identical with every setting off; writes are field-scoped.\n"
        "// The `overlay` entries are the SLink companion-overlay builds (own header CRC, banks 0/1/3 shifted).\n"
    )
    return header + "\n" + "\n".join(sections)


def splice_into_fork(fork: pathlib.Path, text: str) -> pathlib.Path:
    ini = fork / FORK_INI
    body = ini.read_text(encoding="utf-8")
    block = FORK_BEGIN + "\n" + text.rstrip("\n") + "\n" + FORK_END + "\n"
    if FORK_BEGIN in body:
        pre = body[:body.index(FORK_BEGIN)]
        post = body[body.index(FORK_END) + len(FORK_END) + 1:]
        body = pre + block + post
    else:
        body = body.rstrip("\n") + "\n\n" + block
    ini.write_text(body, encoding="utf-8", newline="\n")
    return ini


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roms", default=str(KINDS["clean"]["roms"]))
    ap.add_argument("--overlay-roms", default=str(KINDS["overlay"]["roms"]))
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--fork", default=None, help="fork checkout; splice the entries into its gen1_offsets.ini")
    ap.add_argument("--check", action="store_true", help="fail if --out is not what would be generated")
    args = ap.parse_args()
    text = generate(pathlib.Path(args.roms), pathlib.Path(args.overlay_roms))
    out = pathlib.Path(args.out)
    if args.check:
        if not out.exists() or out.read_text(encoding="utf-8") != text:
            print(f"{out} is stale; rerun tools/gen_upr_gen1_ini.py", file=sys.stderr)
            return 1
        print(f"{out} is current")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    if args.fork:
        print(f"spliced into {splice_into_fork(pathlib.Path(args.fork), text)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
