#!/usr/bin/env python3
"""Draw the SLink logo for the Gen 1 title screen and write patch/gen1/tools/title_art.py.

The title's "Red Version" line sits in a 16-pixel band under the Pokemon logo. The band keeps that
line and gains an SoulLink logo in the Pokemon logo's own style: grey letters, black outline, a darker
extrusion. 9x2 tiles.

    python tools/gen_gen1_title.py             # rewrite title_art.py, preview -> patch/build/gen1_title_logo.png

Needs Pillow (dev only). The patcher imports the generated title_art.py, which is plain bytes.
"""
import pathlib
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_PY = ROOT / "patch/gen1/tools/title_art.py"
PREVIEW = ROOT / "patch/build/gen1_title_logo.png"

WHITE, LIGHT, DARK, BLACK = 0, 1, 2, 3
SHADES = (255, 170, 85, 0)
COLS, ROWS = 9, 2
FIRST_ID = 0x6A                                                 # free BG tile ids on the vanilla title: $6A-$7E

# "SoulLink" at 9 rows tall with 2 pixel strokes: the Pokemon logo's style needs room for an outline and an
# extrusion, and a 16 pixel band has none to spare. Lowercase letters sit on the baseline (rows 3-8).
_GLYPHS = {
    "S": (".####.", "##..##", "##....", "##....", ".####.", "....##", "....##", "##..##", ".####."),
    "o": (".####.", "##..##", "##..##", "##..##", "##..##", ".####."),
    "u": ("##..##", "##..##", "##..##", "##..##", "##..##", ".#####"),
    "l": ("##",) * 9,
    "L": ("##...", "##...", "##...", "##...", "##...", "##...", "##...", "#####", "#####"),
    "i": ("##", "##", "..", "##", "##", "##", "##", "##", "##"),
    "n": ("#####.", "##..##", "##..##", "##..##", "##..##", "##..##"),
    "k": ("##....", "##....", "##..##", "##.##.", "####..", "####..", "##.##.", "##..##", "##..##"),
}
WORD, GAP, HEIGHT = "SoulLink", 3, 9


# 5x7 glyphs for the version line, rendered at patch time by patch/gen1/tools/title_screen.py
_SMALL = """
v 00000 00000 10001 10001 10001 01010 00100
d 00001 00001 01101 10011 10001 10011 01101
e 00000 00000 01110 10001 11111 10000 01110
0 01110 10001 10011 10101 11001 10001 01110
1 00100 01100 00100 00100 00100 00100 01110
2 01110 10001 00001 00010 00100 01000 11111
3 11110 00001 00001 01110 00001 00001 11110
4 00010 00110 01010 10010 11111 00010 00010
5 11111 10000 11110 00001 00001 10001 01110
6 00110 01000 10000 11110 10001 10001 01110
7 11111 00001 00010 00100 01000 01000 01000
8 01110 10001 10001 01110 10001 10001 01110
9 01110 10001 10001 01111 00001 00010 01100
. 00000 00000 00000 00000 00000 01100 01100
- 00000 00000 00000 11111 00000 00000 00000
"""
SMALL = {ln.split()[0]: bytes(int(r, 2) for r in ln.split()[1:]) for ln in _SMALL.strip().splitlines()}


def word_mask(size, x, y):
    m = Image.new("L", size, 0)
    d = ImageDraw.Draw(m)
    for c in WORD:
        rows = _GLYPHS[c]
        for ry, row in enumerate(rows):
            for rx, bit in enumerate(row):
                if bit == "#":
                    d.point((x + rx, y + HEIGHT - len(rows) + ry), fill=255)
        x += len(rows[0]) + GAP
    return m


def paint(img, mask, shade):
    img.paste(shade, mask=mask.point(lambda v: 255 if v else 0))


def dilate(mask):
    return mask.filter(ImageFilter.MaxFilter(3))


def draw() -> Image.Image:
    img = Image.new("L", (COLS * 8, ROWS * 8), WHITE)
    m = word_mask(img.size, 5, 2)
    paint(img, ImageChops.offset(dilate(m), 1, 1), DARK)             # extrusion, down-right
    paint(img, dilate(m), BLACK)                                      # outline
    paint(img, m, LIGHT)
    return img


def main() -> int:
    img = draw()
    tiles, ids, order = [], {}, []
    for ty in range(ROWS):
        for tx in range(COLS):
            cell = img.crop((tx * 8, ty * 8, tx * 8 + 8, ty * 8 + 8))
            key = cell.tobytes()
            if key not in ids:
                ids[key] = len(tiles)
                tiles.append(cell)
            order.append(ids[key])
    data = bytearray()
    for t in tiles:
        p = t.load()
        for y in range(8):
            lo = hi = 0
            for x in range(8):
                v = p[x, y]
                lo |= (v & 1) << (7 - x)
                hi |= (v >> 1) << (7 - x)
            data += bytes((lo, hi))
    rows = [bytes(FIRST_ID + k for k in order[r * COLS:(r + 1) * COLS]) for r in range(ROWS)]
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    prev = Image.new("RGB", img.size)
    prev.putdata([(SHADES[v],) * 3 for v in img.getdata()])
    prev.resize((img.width * 8, img.height * 8), Image.NEAREST).save(PREVIEW)
    h = bytes(data).hex()
    OUT_PY.write_text(
        '"""GENERATED by tools/gen_gen1_title.py -- do not edit. The SoulLink logo for the Gen 1 title screen:\n'
        '2bpp tiles and the two rows of tile ids that place them."""\n\n'
        f"FIRST_ID = {FIRST_ID:#04x}\nTILE_COUNT = {len(tiles)}\n"
        f"SMALL = {SMALL!r}\n"
        f"ROW0 = bytes.fromhex({rows[0].hex()!r})\nROW1 = bytes.fromhex({rows[1].hex()!r})\n"
        "TILES = bytes.fromhex(\n" + "\n".join(f'    "{h[i:i + 96]}"' for i in range(0, len(h), 96)) + "\n)\n",
        encoding="utf-8")
    print(f"{len(tiles)} tiles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
