"""Generate patch/polished/src/trade_items_table.asm, the Polished SLink trade item-allow table.

Policy (docs/polished/TRADE.md): the only Polished-native refusal is mail -- every id >= FIRST_MAIL
(home/header.asm ItemIsMail_a is `cp FIRST_MAIL`), which also covers the $FF sentinel.  FIRST_MAIL is
read from the pinned constants/item_constants.asm through gen_polished_pack's constant evaluator.
Run with --check to compare the committed file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_polished_pack as pack  # noqa: E402

OUT = pack.ROOT / "patch/polished/src/trade_items_table.asm"


def first_mail() -> int:
    consts = pack.parse_consts("constants/item_constants.asm")
    # ItemIsMail asserts the mail run is the tail of the item list
    pack.require(consts["FIRST_MAIL"] + consts["NUM_MAILS"] - 1 == consts["NUM_ITEMS"], "mail is not the item tail")
    return consts["FIRST_MAIL"]


def render(first: int) -> str:
    rows = [f"\tdb {','.join('1' if i < first else '0' for i in range(r, r + 16))} ; ${r:02x}"
            for r in range(0, 256, 16)]
    return ("; GENERATED by tools/gen_polished_trade_items.py -- do not edit.\n"
            f"; Polished policy: allow ids $00..${first - 1:02x} (NONE included); refuse mail ${first:02x}.. and the $ff sentinel.\n"
            "; Indexed by the complete byte (not item-1).\n"
            "SlinkTradeAllowedItems::\n" + "\n".join(rows) + "\n"
            "SlinkTradeAllowedItemsEnd::\n"
            "ASSERT SlinkTradeAllowedItemsEnd - SlinkTradeAllowedItems == 256\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    text = render(first_mail())
    if ap.parse_args().check:
        if OUT.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            print(f"{OUT} is stale; rerun tools/gen_polished_trade_items.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
