#!/usr/bin/env python3
"""gen_gen4_area_map.py -- HGSS area map + location table from pinned pret/pokeheartgold.

Writes (both from the same parse, one provenance block each):
  data/games/gen4_hgss/area_map.json   area_id -> display/maps, plus map_id -> area_id and gift_areas
  data/games/gen4_hgss/locations.json  map_id -> const/token/mapsec/region/type/area
  data/games/gen4_hge/area_map.json    the SAME map for the hg-engine pack, PROVEN equal to HGSS's on the
  data/games/gen4_hge/locations.json   two pinned ROMs (see HGE_PROOF below), not assumed

`gift_areas` (the `ids` list) is derived from the PACK's own acquisition inventory
(data/games/<pack>/acquisition.json, each generated by tools/gen_gen4_acquisition.py from the same pin):
the areas a scripted starter/gift/egg/loan reaches where NO map in the area owns a
wildEncounterBank. The client drops `no_catch` for an area in that list (lua/gen4/poll_events.lua:
415-418), so a list that covered a route would swallow a real failed encounter -- hence the split is
on the map's own wildEncounterBank, a `static` site is excluded (a static IS a WildBattle; Gen 3 makes
the same call at tools/gen_area_map.py:736-742), and a contradiction raises instead of picking a side.

gen4_hge gets the same two files, from the same parse, with the derivation unchanged -- and the generator
PROVES they are valid for the fork instead of assuming it. The fork's own SOURCE still cannot supply an
area (no MAPSEC_*, no src/data/map_headers.h, no `// MAP_<token>` comments, no files/msgdata/msg tree),
but its ROM carries the finished table: `sMapHeaders` (540 MapHeader records -- wildEncounterBank,
areaDataBank, mapsec, regionNo, mapType) and msg 279 (the area names, indexed by mapsec). Both are read
from BOTH pinned ROMs on every run and must be byte-identical; a present-but-different span is a FAIL and
nothing is written, an absent ROM is an OPEN skip (exit 2). So hge needs no pret oracle BEYOND the HGSS
map it is proven to be -- the file it ships records that proof (full sha256 of both spans, both ROM sha1s,
the address and the size) beside the pret provenance. `gift_areas` reads the hge pack's OWN
acquisition.json, never gen4_hgss's.

Source (pokeheartgold @ the commit pinned in data/gen4_sources.lock.json, never a ROM text dump):
  include/constants/maps.h          MAP_* id and the MAP_<token> comment
  src/data/map_headers.h            .mapsec .regionNo .mapType .wildEncounterBank per map
  include/constants/map_sections.h  MAPSEC_* ids
  files/msgdata/msg/msg_0279.gmm    area names, indexed by mapsec (src/field/draw_map_name.c)
  include/constants/safari.h        the 12 Safari areas (D10: Safari counts per area)

Area rule: an area is a map section (mapsec) -- every map sharing a mapsec shares a Soul Link area
(Union Cave 1F/B1F/B2F, Elm's Lab inside New Bark Town, ...). The area_id is the slug of the English
name in msg 0279. D10 overrides: the Bug-Catching Contest map is its own area, and the Safari Zone
gets one sub-area per Safari area (the area a position falls in is chosen at runtime from the
player's coordinates and area set, so those sub-areas own no static map).

This module is also the shared helper layer for gen_gen4_{encounters,trainers,acquisition}.py.

Usage:
  python tools/gen_gen4_area_map.py            # write both packs
  python tools/gen_gen4_area_map.py --check    # regenerate in memory, diff vs committed (exit 1 on drift)
  python tools/gen_gen4_area_map.py --path heartgold_hge=<rom>   # point the hge proof at another build
Exit: 0 ok, 1 drift / wrong pret commit / hge map data that is NOT the HGSS map, 2 the pret clone or a
pinned ROM is absent (OPEN, nothing written -- the hge pair is never written unproven).
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen4_pins  # noqa: E402
import gen_gen4_pack as pack  # noqa: E402  (the ROM image loader + input resolver; it imports nothing from this family)

PIN = gen4_pins.SOURCE_COMMITS["pokeheartgold_citation"]
OUT_DIR = REPO / "data" / "games" / "gen4_hgss"
ENV_CLONE = "SLINK_PRET_HGSS"

# The gift-area list is derived from the pack's own acquisition inventory, not re-scanned from the
# clone: acquisition.json is generated from the SAME pin by tools/gen_gen4_acquisition.py, so reading
# the committed file keeps ONE place where "what is a catch" is answered. REPO-relative, exactly as
# tools/gen_area_map.py:743-744 reads statics.json -- --out-dir is a destination choice, not a source.
ACQUISITION = REPO / "data" / "games" / "gen4_hgss" / "acquisition.json"

# gen4_hge ships the SAME two files, from the same parse, and the generator PROVES they are valid for the
# fork instead of assuming it. The fork's own SOURCE cannot supply an area (no MAPSEC_* anywhere, no
# src/data/map_headers.h, no `// MAP_<token>` comments, no files/msgdata/msg tree), but its ROM carries the
# finished table, and two reads decide the question on every run, both against the PINNED ROMs:
#   * sMapHeaders -- 540 MapHeader records; an area's mapsec (its identity) and the wildEncounterBank the
#     gift-area split reads both live here;
#   * msg 279 -- the area names, indexed by mapsec (src/field/draw_map_name.c).
# A present-but-different span is a FAIL and nothing is written; an absent ROM is an OPEN skip (exit 2),
# never a silent success. So hge needs no pret oracle beyond the HGSS map it is proven to be: the emitted
# file records the proof (full sha256 of both spans, both ROM sha1s, address and size) beside the pret
# provenance, and `gift_areas` reads the hge pack's OWN acquisition.json, never gen4_hgss's.
HGE_OUT_DIR = REPO / "data" / "games" / "gen4_hge"
HGE_ACQUISITION = REPO / "data" / "games" / "gen4_hge" / "acquisition.json"

# ONE place for the table's identity. Address and size are the pret build's own -- the xMAP entry and the C
# declaration it comes from. 540 records x 24 B is also the MAP_* range build_model() parses (Maps asserts
# 540), and build_hge() re-checks that against MAP_HEADER_COUNT, so a pin change that moved either end of
# the table fails instead of silently comparing the wrong span.
MAP_HEADERS_SYMBOL = "sMapHeaders"
MAP_HEADERS_IMAGE = "arm9"
MAP_HEADERS_ADDR = 0x020F6BE0
MAP_HEADERS_SIZE = 0x32A0
MAP_HEADER_SIZE = MAP_HEADERS_SIZE // 540
MAP_HEADER_COUNT = MAP_HEADERS_SIZE // MAP_HEADER_SIZE
MAP_HEADERS_CITE = ("pret/pokeheartgold src/map_header.c:15 (include/map_header.h:13-42), "
                    ".cache/gen4/xmap/heartgoldus.xMAP:49069-49070")
AREA_NAMES_NARC = "a/0/2/7"
AREA_NAMES_MSG = 279  # msg 0279, indexed by mapsec -- the ROM twin of files/msgdata/msg/msg_0279.gmm
HGE_PROOF = ("gen4_hge's area map IS the HGSS area map: the fork's ROM holds byte-identical map headers and "
             "byte-identical area names, so the pret-derived table below is valid for hg-engine as it stands. "
             "Re-run this generator after any hge rebuild -- a changed span is a FAIL, not a warning.")
GENERATOR = "tools/gen_gen4_area_map.py"
NOTE = "GENERATED by " + GENERATOR + " from pinned pret/pokeheartgold -- do not edit."


class PretAbsent(Exception):
    """The pinned pokeheartgold clone is not on this machine (exit 2 / test skip)."""


class PretMismatch(Exception):
    """The clone exists but is not the pinned, clean checkout (exit 1 / test FAIL)."""


class AcquisitionAbsent(Exception):
    """The generated acquisition inventory is missing (exit 1): the gift-area list cannot be derived."""


class GiftAreaOnWildMap(Exception):
    """A gift site resolved to an area that owns a wild-encounter map (exit 1, fail closed)."""


class HgeRomAbsent(Exception):
    """A pinned ROM the hge proof reads is not on this machine (exit 2 / test skip)."""


class HgeMapDrift(Exception):
    """The hge ROM is present but its map data is NOT the HGSS map (exit 1, fail closed)."""


# --------------------------------------------------------------------------- clone + provenance


def locate_clone(arg: str | None = None) -> Path:
    path = Path(arg or os.environ.get(ENV_CLONE) or gen4_pins.default_locations().sources["pokeheartgold_citation"])
    if not (path / "include" / "constants" / "maps.h").is_file():
        raise PretAbsent(f"pret/pokeheartgold clone not found at {path} (set {ENV_CLONE} or pass --pret)")
    return path


def _git(clone: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(clone), *args], capture_output=True, text=True, check=True).stdout.strip()


def verify_clone(clone: Path) -> None:
    try:
        head = _git(clone, "rev-parse", "HEAD")
        dirty = _git(clone, "status", "--porcelain", "--untracked-files=no")
    except (OSError, subprocess.CalledProcessError) as exc:
        raise PretMismatch(f"cannot read git state of {clone}: {exc}") from exc
    if head != PIN:
        raise PretMismatch(f"pokeheartgold clone {clone} is at {head}, pinned {PIN}")
    if dirty:
        raise PretMismatch(f"pokeheartgold clone {clone} has tracked modifications; pin {PIN} requires a clean tree")


def provenance(clone: Path, generator: str, inputs: list[str]) -> dict:
    """Source identity for a generated file: pinned commit + sha256 of every input actually read."""
    return {
        "repo": "pret/pokeheartgold",
        "commit": PIN,
        "generator": generator,
        "inputs": {rel: hashlib.sha256((clone / rel).read_bytes()).hexdigest() for rel in sorted(inputs)},
    }


def dumps(obj, depth: int, level: int = 0) -> str:
    """Pretty-print the top `depth` container levels, compact below (keeps diffs and size sane)."""
    if depth <= 0 or not isinstance(obj, (dict, list)) or not obj or (isinstance(obj, list) and not any(isinstance(v, (dict, list)) for v in obj)):
        return json.dumps(obj, ensure_ascii=False)
    pad, end = "  " * (level + 1), "  " * level
    if isinstance(obj, dict):
        body = ",\n".join(f"{pad}{json.dumps(k, ensure_ascii=False)}: {dumps(v, depth - 1, level + 1)}" for k, v in obj.items())
        return "{\n" + body + "\n" + end + "}"
    return "[\n" + ",\n".join(pad + dumps(v, depth - 1, level + 1) for v in obj) + "\n" + end + "]"


def _shown(path: Path) -> str:
    try:
        return str(path.relative_to(REPO))
    except ValueError:  # --out-dir outside the repo
        return str(path)


def finish(out: Path, text: str, check: bool) -> bool:
    """Write `text` (or, with check, diff it against the committed file). True when in sync."""
    text += "\n"
    if check:
        have = out.read_bytes().replace(b"\r\n", b"\n").decode("utf-8") if out.is_file() else None
        if have != text:
            print(f"DRIFT: {_shown(out)} differs from a fresh regeneration", file=sys.stderr)
            return False
        print(f"ok: {_shown(out)}")
        return True
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {_shown(out)}")
    return True


def cli(build, description: str, extra=None) -> int:
    """Shared entry point: build(clone) -> {name: text}; --pret/--check/--out-dir/exit codes.

    `extra(clone, path_overrides)` returns further (out_dir, {name: text}) groups built from the SAME
    verified clone and checked/written by the same rule, so one run keeps every pack in step. It is what
    lets this module emit gen4_hge next to gen4_hgss -- and it is also what --path is for (gen4_hgge's
    proof reads the ROMs); with no `extra` the flag is not offered at all.
    """
    ap = argparse.ArgumentParser(description=description)
    ap.add_argument("--pret", help=f"pokeheartgold clone (default ${ENV_CLONE} or the gen4_pins location)")
    ap.add_argument("--check", action="store_true", help="regenerate in memory and diff vs the committed JSON")
    ap.add_argument("--out-dir", default=str(OUT_DIR),
                    help="destination for the gen4_hgss pair (default: data/games/gen4_hgss); the gen4_hge "
                         "pair always lands in its own pack directory")
    if extra is not None:
        ap.add_argument("--path", action="append", default=[], metavar="KEY=PATH",
                        help="override a Gen 4 ROM input path (heartgold, heartgold_hge); the same keys and "
                             "SLINK_GEN4_<KEY> environment as tools/gen_gen4_pack.py")
    args = ap.parse_args()
    try:
        clone = locate_clone(args.pret)
        verify_clone(clone)
        groups = [(Path(args.out_dir), build(clone))]
        if extra is not None:
            groups.extend(extra(clone, dict(p.split("=", 1) for p in args.path)))
    except (PretAbsent, HgeRomAbsent) as exc:
        print(f"OPEN: {exc}", file=sys.stderr)
        return 2
    except (PretMismatch, HgeMapDrift) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if not any(files for _, files in groups):  # an empty file set would make all([]) pass vacuously
        print("FAIL: the generator produced no files", file=sys.stderr)
        return 1
    # no short-circuit: report every file, every pack
    results = [finish(out / name, text, args.check) for out, files in groups for name, text in files.items()]
    return 0 if all(results) else 1


# --------------------------------------------------------------------------- pret readers


def read(clone: Path, rel: str) -> str:
    return (clone / rel).read_text(encoding="utf-8")


def gmm(clone: Path, bank: int) -> dict[int, str]:
    """English rows of files/msgdata/msg/msg_<bank>.gmm as {index: text}."""
    text = read(clone, f"files/msgdata/msg/msg_{bank:04d}.gmm")
    rows = re.findall(r'<row id="[^"]*" index="(\d+)">.*?<language name="English">(.*?)</language>', text, re.S)
    return {int(i): html.unescape(s) for i, s in rows}


def defines(clone: Path, rel: str, prefix: str) -> dict[str, int]:
    return {n: int(v) for n, v in re.findall(rf"^#define ({prefix}\w+)\s+(\d+)\b", read(clone, rel), re.M)}


def slug(text: str) -> str:
    s = text.replace("’", "").replace("'", "")
    s = s.replace("é", "e")
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def titled(name: str) -> str:
    """msg names are upper-case (BULBASAUR, MR. MIME, HO-OH, FARFETCH'D): Capitalise each word/hyphen part;
    a letter after an apostrophe stays lower-case (Farfetch'd)."""
    return re.sub(r"[A-Za-z]+(?:['’][A-Za-z]+)*", lambda m: m.group(0)[0].upper() + m.group(0)[1:].lower(), name)


def _field(body: str, name: str) -> str:
    return re.search(r"\." + name + r"\s*=\s*(\w+)", body)[1]


class Maps:
    """Everything keyed by map: id, const, header token, mapsec, region, type, encounter bank."""

    def __init__(self, clone: Path):
        self.rows: dict[int, dict] = {}
        for const, mid, token in re.findall(r"^#define (MAP_\w+)\s+(\d+)\s*//\s*MAP_(\w+)", read(clone, "include/constants/maps.h"), re.M):
            self.rows[int(mid)] = {"const": const, "token": token}
        hdr = read(clone, "src/data/map_headers.h")
        blocks = re.split(r"\n    \[(MAP_\w+)\] = \{", hdr)
        by_const = {r["const"]: mid for mid, r in self.rows.items()}
        for i in range(1, len(blocks), 2):
            body = blocks[i + 1]
            row = self.rows[by_const[blocks[i]]]
            row["mapsec"] = _field(body, "mapsec")
            row["region"] = _field(body, "regionNo").removeprefix("MAP_REGION_")
            row["map_type"] = _field(body, "mapType").removeprefix("MAP_TYPE_")
            bank = _field(body, "wildEncounterBank").removeprefix("ENCDATA_")
            row["enc_bank"] = None if bank == "NA" else bank
        assert len(self.rows) == 540 and all("mapsec" in r for r in self.rows.values()), "map header parse drifted"
        assert len({r["token"] for r in self.rows.values()}) == 540, "map tokens are no longer unique"
        self.by_token = {r["token"]: mid for mid, r in self.rows.items()}
        # `.eventsBank` binds a zone_event NARC member to the map header that loads it. A zone_event FILE NAME's
        # numeric prefix IS that member number and is NOT a map id (035_R34.json is map 38; 302_R34R0101.json is
        # map 331), so every lookup from a zone_event file to a map must come through here.
        self.by_events_bank: dict[int, tuple[int, str]] = {}   # zone_event member -> (map id, map_headers.h cite)
        self.events_bank_token: dict[int, str] = {}            # zone_event member -> the token the file is named for
        self.ambiguous_events_bank: set[int] = set()           # members two headers both claim
        cur = None
        for n, ln in enumerate(hdr.splitlines(), 1):
            if m := re.match(r"^\s*\[(MAP_\w+)\] = \{", ln):
                cur = by_const[m[1]]
            elif cur is not None and (m := re.match(r"^\s*\.eventsBank\s*=\s*NARC_zone_event_(\d+)_(\w+)_bin\b", ln)):
                bank = int(m[1])
                if bank in self.by_events_bank:
                    self.ambiguous_events_bank.add(bank)   # not fatal here: a map that binds nothing is still a valid header
                else:
                    self.by_events_bank[bank] = (cur, f"src/data/map_headers.h:{n}")
                    self.events_bank_token[bank] = m[2]
                self.rows[cur]["events_bank"] = bank


SAFARI_AREAS = ("PLAINS", "MEADOW", "SAVANNAH", "PEAK", "ROCKY_BEACH", "WETLAND", "FOREST", "SWAMP", "MARSHLAND", "WASTELAND", "MOUNTAIN", "DESERT")
BUG_CONTEST_MAP = "MAP_NATIONAL_PARK_BUG_CATCHING_CONTEST"
SAFARI_MAPSEC = "MAPSEC_SAFARI_ZONE"
SAFARI_RESOLUTION = "runtime: src/field/encounter_check.c FieldSystem_GenerateSafariEncounter picks the area from the player coordinates (ov02_0224E340) through the save's SafariZoneAreaSet; no static map owns it"


def build_model(clone: Path) -> dict:
    maps = Maps(clone)
    sec_ids = defines(clone, "include/constants/map_sections.h", "MAPSEC_")
    sec_name = gmm(clone, 279)
    safari_ids = defines(clone, "include/constants/safari.h", "SAFARI_ZONE_AREA_")
    assert [f"SAFARI_ZONE_AREA_{n}" for n in SAFARI_AREAS] == [k for k in safari_ids if k.startswith("SAFARI_ZONE_AREA_") and k[17:] in SAFARI_AREAS], "Safari area list drifted"

    areas: dict[str, dict] = {}
    map_area: dict[int, str | None] = {}
    unmapped: dict[int, str] = {}
    slug_owner: dict[str, str] = {}
    for mid, row in sorted(maps.rows.items()):
        sec = row["mapsec"]
        if sec == "MAPSEC_MYSTERY_ZONE":
            unmapped[mid] = "system map (mapsec 0)"
            continue
        if row["const"] == BUG_CONTEST_MAP:
            aid, disp, special = "bug_catching_contest", "Bug-Catching Contest", "bug_contest"
            sec_for_area = sec  # shares the National Park mapsec; the area split is ours (D10)
        else:
            disp = sec_name[sec_ids[sec]]
            aid = slug(disp)
            if slug_owner.setdefault(aid, sec) != sec:
                aid = f"{aid}_{sec_ids[sec]}"
            special = "safari" if sec == SAFARI_MAPSEC else None
            sec_for_area = sec
        area = areas.setdefault(aid, {"display": disp, "mapsec": sec_for_area, "region": row["region"], "special": special, "parent": None, "maps": []})
        area["maps"].append(mid)
        map_area[mid] = aid

    # An area whose maps are all *_UNUSED_* dummies is not a place the player can be.
    for aid in [a for a, v in areas.items() if all("UNUSED" in maps.rows[m]["const"] for m in v["maps"])]:
        for mid in areas.pop(aid)["maps"]:
            unmapped[mid] = f"unused-only map section ({aid})"
            map_area[mid] = None

    # `_UNUSED_` dummy maps stay in the maps->area table (map_area) but are not listed as a place in the area:
    # they live in the separate `unused_maps` field.
    for v in areas.values():
        v["unused_maps"] = [m for m in v["maps"] if "UNUSED" in maps.rows[m]["const"]]
        v["maps"] = [m for m in v["maps"] if m not in v["unused_maps"]]

    # D10: Safari sub-areas. They own no static map; the parent owns the 15 Safari maps.
    areas["safari_zone"]["safari_area_resolution"] = SAFARI_RESOLUTION
    for name in SAFARI_AREAS:
        areas[f"safari_{name.lower()}"] = {
            "display": f"Safari Zone ({titled(name.replace('_', ' '))})",
            "mapsec": None,
            "region": areas["safari_zone"]["region"],
            "special": "safari",
            "parent": "safari_zone",
            "safari_area_const": f"SAFARI_ZONE_AREA_{name}",
            "safari_area_id": safari_ids[f"SAFARI_ZONE_AREA_{name}"],
            "maps": [],
            "unused_maps": [],
        }
    return {"maps": maps, "areas": areas, "map_area": map_area, "unmapped": unmapped, "sec_ids": sec_ids, "sec_name": sec_name}


# The client's gift-area predicate only answers one question -- "is a wild encounter here the reason
# this area is still open?" -- so the list is a statement about AREAS, and the rule is written in
# terms of the map's own wildEncounterBank rather than in terms of any kind of site.
GIFT_RULE = (
    "An area_id in `ids` is one a scripted catch reaches where NO map in the area owns a wildEncounterBank: "
    "the only way a mon enters it is the starter / a gift / an egg / a loan. The client's gift_area "
    "predicate drops no_catch for such an area (lua/gen4/poll_events.lua:415-418), so a list covering a "
    "route would swallow a genuine failed encounter -- every candidate whose area DOES own a wild map is "
    "named in `on_wild_area` instead, and a contradiction raises rather than picking a side. `static` is "
    "excluded on purpose: the pack maps it to the gift zone for LINKING, but a static IS a WildBattle, so "
    "exempting its area would suppress a real failure (tools/gen_area_map.py:736-742 makes the same call "
    "for Gen 3). `sites` is every candidate map; `ids` is the set of areas `sites` resolves to that are not "
    "in `on_wild_area`."
)


def load_acquisition(path: Path = ACQUISITION) -> dict:
    """The pack's acquisition inventory (tools/gen_gen4_acquisition.py). Absent is a FAIL, not a skip:
    without it there is no evidence for which areas a scripted catch reaches."""
    if not path.is_file():
        raise AcquisitionAbsent(
            f"{_shown(path)} is missing: it is the pack's acquisition inventory, and the gift-area list "
            "is derived from it (run tools/gen_gen4_acquisition.py against the pinned clone first)"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def gift_kinds(acq: dict) -> set[str]:
    """The site kinds whose zone_policy zone is `gift`, minus `static` (see GIFT_RULE). Read from the
    pack's own table so a new acquisition kind cannot be silently skipped by this generator."""
    policy = acq.get("zone_policy")
    if not isinstance(policy, dict):
        raise AcquisitionAbsent("acquisition.json has no zone_policy table: nothing says what is a gift")
    kinds = {k for k, v in policy.items() if isinstance(v, dict) and v.get("zone") == "gift" and k != "static"}
    if not kinds:
        raise AcquisitionAbsent("acquisition.json zone_policy ships no gift-zone kind: the gift list would be empty")
    return kinds


def check_gift_ids(m: dict, ids) -> None:
    """Fail closed: no area in the list may own a wild-encounter map. The split above and this guard
    read the two halves of the fact from different places -- acquisition.json says a scripted catch
    reaches the area, map_headers.h says whether that area has wild grass -- so a disagreement is a
    real defect, not a restatement. Kept callable on its own so the invariant is testable directly."""
    maps, areas = m["maps"], m["areas"]
    for aid in sorted(ids):
        bad = [x for x in areas[aid]["maps"] + areas[aid]["unused_maps"] if maps.rows[x]["enc_bank"] is not None]
        if bad:
            raise GiftAreaOnWildMap(
                f"area {aid!r} is in gift_areas.ids but owns wild-encounter maps {bad}; the client would "
                "drop a real no_catch there (lua/gen4/poll_events.lua:415-418)"
            )


def gift_areas(m: dict, acq: dict, acq_path: Path = ACQUISITION) -> dict:
    """The pack's gift-area block: area ids exempt from no_catch, plus the evidence for the split.

    `acq_path` is the inventory the block is derived from, so the emitted `acquisition.file`/sha256 name
    the file this generator actually read. gen4_hge passes its OWN inventory (default: gen4_hgss's); the
    derivation below is identical either way, which is the point -- the list moves with the inventory.
    """
    maps, areas = m["maps"], m["areas"]
    kinds = gift_kinds(acq)

    def wild(mid: int) -> bool:
        return maps.rows[mid]["enc_bank"] is not None

    sites: dict[str, str] = {}          # map_id -> area, every candidate the pack places on a map
    on_wild: dict[str, str] = {}        # map_id -> area, the candidates the wild-encounter rule removed
    ids: set[str] = set()
    for site in acq.get("script_sites", []):
        if site.get("kind") not in kinds:
            continue
        mid, aid = site.get("map_id"), site.get("area")
        if not isinstance(mid, int) or not isinstance(aid, str) or aid not in areas:
            # A gift catch the pack could not place: name it rather than drop it, so the gap is visible in
            # the file instead of being an absence nobody notices.
            raise AcquisitionAbsent(f"acquisition site {site.get('id')!r} has no mappable area ({mid!r}, {aid!r})")
        # Idempotent: the split is a property of the AREA, so a second site in the same area re-lands on
        # the same side instead of flipping the answer.
        sites[str(mid)] = aid
        if any(wild(x) for x in areas[aid]["maps"] + areas[aid]["unused_maps"]):
            on_wild[str(mid)] = aid
        else:
            ids.add(aid)

    check_gift_ids(m, ids)
    missing = set(sites.values()) - ids - set(on_wild.values())
    if missing:
        raise GiftAreaOnWildMap(f"gift sites resolved to areas in neither ids nor on_wild_area: {sorted(missing)}")

    # The commands acquisition.json parks under out_of_scope_commands are not script_sites, so they carry no map
    # and cannot put an area in `ids`. What is left there genuinely has no map of its own: an externally driven
    # grant (MysteryGift), a record the LoadNPCTrade site already owns (NPCTradeExec), a variable fill a GiveMon
    # site consumes (GetFossilPokemon) and a withdrawal of a mon that already has a Soul Link key
    # (RetrieveDaycareMon). A scripted catch inside a COMMON (std) script is NOT one of these: the acquisition
    # generator resolves the object that RUNS the member holding the command, so the Day-Care Man's
    # GiveDaycareEgg is a real script_site on the map that object stands on (Route 34) and takes the ordinary
    # sites / on_wild_area path -- its area owns a wild-encounter map, so it is NEVER exempted.
    no_map = {
        cmd: {"sites": row.get("sites", []), "why": row.get("why", "")}
        for cmd, row in sorted((acq.get("out_of_scope_commands") or {}).items())
        if isinstance(row, dict)
    }
    return {
        "ids": sorted(ids),
        "source": "tools/gen_gen4_area_map.py gift_areas(), over acquisition.json script_sites; the rule is rules.gift_areas",
        "acquisition": {
            "file": _shown(acq_path).replace("\\", "/"),   # a pack fact, not a host path: posix on every OS
            "sha256": hashlib.sha256(acq_path.read_bytes()).hexdigest() if acq_path.is_file() else None,
            "generator": "tools/gen_gen4_acquisition.py",
            "kinds": sorted(kinds),
        },
        "sites": dict(sorted(sites.items(), key=lambda kv: int(kv[0]))),
        "on_wild_area": dict(sorted(on_wild.items(), key=lambda kv: int(kv[0]))),
        "no_map_commands": no_map,
    }


INPUTS = [
    "include/constants/maps.h",
    "src/data/map_headers.h",
    "include/constants/map_sections.h",
    "include/constants/safari.h",
    "files/msgdata/msg/msg_0279.gmm",
]


def documents(m: dict, *, note: str, prov: dict, acq_path: Path, depth: int = 2) -> dict[str, str]:
    """The two emitted documents, from ONE model. Both packs come through here, so gen4_hge cannot
    differ from gen4_hgss in any field except the provenance the caller hands in."""
    maps, areas = m["maps"], m["areas"]

    area_doc = {
        "_note": note + " areas: area_id -> display/maps (map ids). maps: map_id -> area_id (null = not a Soul Link place, see unmapped_maps).",
        "_schema": "gen4-hgss-area-map-v1",
        "source": prov,
        "rules": {
            "area": "one area per map section (mapsec); display = msg 0279[mapsec]",
            "bug_contest": f"{BUG_CONTEST_MAP} is its own area (D10); a kept bug is the catch, awarded at the result",
            "safari": "Safari Zone is one sub-area per Safari area (D10); area resolved at runtime, sub-areas own no static map",
            "gift_areas": GIFT_RULE,
        },
        "areas": {aid: areas[aid] for aid in sorted(areas)},
        "maps": {str(mid): m["map_area"].get(mid) for mid in sorted(maps.rows)},
        "unmapped_maps": {str(mid): why for mid, why in sorted(m["unmapped"].items())},
        "gift_areas": gift_areas(m, load_acquisition(acq_path), acq_path),
    }
    loc_doc = {
        "_note": note + " Per-map location facts (HUD/status page): the name shown in game is the mapsec name.",
        "_schema": "gen4-hgss-locations-v1",
        "source": prov,
        "locations": {
            str(mid): {
                "const": row["const"],
                "token": row["token"],
                "mapsec": row["mapsec"],
                "name": m["sec_name"][m["sec_ids"][row["mapsec"]]],
                "region": row["region"],
                "map_type": row["map_type"],
                "enc_bank": row["enc_bank"],
                "area": m["map_area"].get(mid),
            }
            for mid, row in sorted(maps.rows.items())
        },
    }
    return {"area_map.json": dumps(area_doc, depth), "locations.json": dumps(loc_doc, depth)}


def build(clone: Path) -> dict[str, str]:
    return documents(build_model(clone), note=NOTE, prov=provenance(clone, GENERATOR, INPUTS), acq_path=ACQUISITION)


# --------------------------------------------------------------------------- the hge proof
def hge_inputs(overrides: dict[str, str] | None = None):
    """The ROM paths exactly as tools/gen_gen4_pack.py resolves them (gen4_pins locations, then
    SLINK_GEN4_<KEY>, then --path), so both Gen 4 generators have ONE input resolver."""
    return pack.default_inputs(overrides or {})


def area_name_member(rom: Path, member: int = AREA_NAMES_MSG) -> bytes:
    """The raw bytes of one message-NARC member (ndspy), read whole: equality is decided on the bytes."""
    import ndspy.narc
    import ndspy.rom

    narc = ndspy.narc.NARC(ndspy.rom.NintendoDSRom.fromFile(str(rom)).getFileByName(AREA_NAMES_NARC))
    if member >= len(narc.files):
        raise HgeMapDrift(f"{AREA_NAMES_NARC} in {rom} holds {len(narc.files)} members, not {member + 1}: "
                          "the area-name bank is not where this generator reads it")
    return bytes(narc.files[member])


def map_header_spans(images: dict) -> dict[str, bytes]:
    """The sMapHeaders span out of each ROM's ARM9 image, addressed BY IMAGE (never by address alone)."""
    return {key: img.read(MAP_HEADERS_IMAGE, MAP_HEADERS_ADDR, MAP_HEADERS_SIZE) for key, img in sorted(images.items())}


def _sha(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def require_identical(blobs: dict[str, bytes], what: str) -> None:
    """Fail closed: two ROMs must agree byte for byte. Full digests, no prefixes, in the message."""
    rows = [(key, blob, _sha(blob)) for key, blob in sorted(blobs.items())]
    if len({digest for _, _, digest in rows}) != 1:
        detail = ", ".join(f"{key} {len(blob)} B sha256 {digest}" for key, blob, digest in rows)
        raise HgeMapDrift(f"{what} is NOT byte-identical between the vanilla HG and the hge ROM -- {detail}")


def hge_proof(inputs=None) -> dict:
    """Read both spans out of BOTH pinned ROMs, require byte equality, and return the provenance block.

    Fail closed on a present-but-different span (HgeMapDrift, exit 1); an absent input is a named OPEN
    skip (HgeRomAbsent, exit 2). There is no path that emits the hge files without this passing."""
    inputs = hge_inputs() if inputs is None else inputs
    try:
        lock = pack.load_lock(inputs)
        roms = {key: pack.verify_rom(inputs, lock, key) for key in ("heartgold", "heartgold_hge")}
        images = {
            # the two sources tools/gen_gen4_pack.py uses (Images.from_rom / ARM9_BYTES_NOTE): HG through
            # ndspy's DECOMPRESSED static image, hge through the raw uncompressed rom.arm9.
            "heartgold": pack.load_images(inputs.paths["heartgold"]),
            "heartgold_hge": pack.load_images(inputs.paths["heartgold_hge"], raw_arm9=True),
        }
        spans = map_header_spans(images)
        names = {key: area_name_member(inputs.paths[key], AREA_NAMES_MSG) for key in sorted(images)}
    except pack.Skip as exc:
        raise HgeRomAbsent(str(exc)) from exc
    except pack.Fail as exc:
        raise HgeMapDrift(str(exc)) from exc
    except (OSError, ValueError, KeyError) as exc:
        raise HgeMapDrift(f"cannot read the map data out of the pinned ROMs: {exc}") from exc
    require_identical(spans, f"{MAP_HEADERS_SYMBOL} ({MAP_HEADERS_ADDR:#010x}+{MAP_HEADERS_SIZE:#x})")
    require_identical(names, f"{AREA_NAMES_NARC} member {AREA_NAMES_MSG} (area names)")
    return {
        "claim": HGE_PROOF,
        "identical": True,
        "map_headers": {
            "symbol": MAP_HEADERS_SYMBOL,
            "image": MAP_HEADERS_IMAGE,
            "address": f"{MAP_HEADERS_ADDR:#010x}",
            "size": MAP_HEADERS_SIZE,
            "struct_size": MAP_HEADER_SIZE,
            "count": MAP_HEADER_COUNT,
            "sha256": {key: _sha(blob) for key, blob in sorted(spans.items())},
            "cite": MAP_HEADERS_CITE,
        },
        "area_names": {
            "narc": AREA_NAMES_NARC,
            "member": AREA_NAMES_MSG,
            "size": len(names["heartgold"]),
            "sha256": {key: _sha(blob) for key, blob in sorted(names.items())},
            "cite": "msg 0279 = area names, indexed by mapsec (pokeheartgold src/field/draw_map_name.c)",
        },
        "roms": {key: {"sha1": row["sha1"], "sha256": row["sha256"], "size_bytes": row["size_bytes"]}
                 for key, row in sorted(roms.items())},
        "method": ("both spans are read from both ROMs on every run and compared whole; HG through ndspy "
                   "loadArm9().sections[0] (the DECOMPRESSED static image, never the compressed rom.arm9), "
                   "hge through the raw uncompressed rom.arm9 -- the two sources tools/gen_gen4_pack.py "
                   "uses. Each ROM's identity is checked against data/gen4_sources.lock.json before either "
                   "is read, so a rebuilt or substituted ROM cannot pass as the pinned one."),
    }


def build_hge(clone: Path, inputs=None) -> dict[str, str]:
    """The same two documents for gen4_hge: same parse, same derivation, recorded proof, own inventory.

    Fails before anything is written -- a map-id range that no longer matches the table, a ROM that is not
    the pinned one, or a fork whose map data has drifted from HGSS's all raise instead of emitting a
    plausible file. depth 3 keeps the provenance block readable (the HGSS files stay at 2, unchanged)."""
    m = build_model(clone)
    if len(m["maps"].rows) != MAP_HEADER_COUNT:
        raise HgeMapDrift(f"the pinned clone parses {len(m['maps'].rows)} maps but {MAP_HEADERS_SYMBOL} holds "
                          f"{MAP_HEADER_COUNT} records; MAP_HEADERS_ADDR/SIZE no longer describe this pin")
    note = NOTE + (" Areas and names are the HGSS ones, proven byte-identical in the fork's ROM -- see "
                   "source.hge_proof, which records the full sha256 of both spans and both ROM sha1s.")
    prov = {**provenance(clone, GENERATOR, INPUTS), "hge_proof": hge_proof(inputs)}
    return documents(m, note=note, prov=prov, acq_path=HGE_ACQUISITION, depth=3)


def main() -> int:
    # The failures this file owns are exit 1, not the clone's: a missing inventory, a gift area covering a
    # wild map, and hge map data that is not the HGSS map. So cli()'s codes hold: 2 = a pinned input is
    # absent (OPEN, nothing written), 1 = drift or a FAIL.
    try:
        return cli(build, __doc__.splitlines()[0],
                   extra=lambda clone, overrides: [(HGE_OUT_DIR, build_hge(clone, hge_inputs(overrides)))])
    except (AcquisitionAbsent, GiftAreaOnWildMap) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
