"""Export the battle_init checkpoint profile for the replace_rival_team executor and verifier.

P5-rival-team-executor.md section 2: the write is safe at every VBlank boundary with
wIsInBattle == 2 and wEnemyMonPartyPos == $FF while the main thread halts in DelayFrame.
WRAM symbols come from the pinned pret build (data/pret_syms.json, pokered for Red/Blue,
pokeyellow for Yellow); the ROM anchors and stack window are the already source-verified
write_safe profile of lua/games/gen1_rby.lua (the same bytes write_checkpoint.json exports).
Both artifacts (JSON for the server, Lua twin for the client) are written together.
"""
import argparse
import json
from pathlib import Path

from lupa.lua54 import LuaRuntime

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data/games/gen1_rby/rival_team_checkpoint.json"
LUA = ROOT / "data/games/gen1_rby/gen1_rival_team_checkpoint.lua"
SOURCES = {"red": "pokered", "blue": "pokered", "yellow": "pokeyellow"}
SYMBOLS = {"is_in_battle": "wIsInBattle", "enemy_mon_party_pos": "wEnemyMonPartyPos",
           "enemy_party_count": "wEnemyPartyCount", "cur_opponent": "wCurOpponent",
           "link_state": "wLinkState", "battle_type": "wBattleType"}
ANCHORS = ("irq_vector", "vblank_entry", "delay_frame", "vblank_flag", "stack_min", "stack_end", "link_none")


def build():
    syms = json.loads((ROOT / "data/pret_syms.json").read_text(encoding="utf-8"))
    lua = LuaRuntime(unpack_returned_tuples=True)
    game = lua.execute((ROOT / "lua/games/gen1_rby.lua").read_text(encoding="utf-8"))
    result = {"schema": "rby-battle-init-checkpoint-v1", "symbols": dict(SYMBOLS), "titles": {}}
    for variant, source in SOURCES.items():
        profile = game.PROFILES[variant]
        safe = profile.write_safe
        block = {name: syms[source][symbol] for name, symbol in SYMBOLS.items()}
        # The client memory module reads the same bytes through its own profile names.
        assert block["is_in_battle"] == profile.BATTLE_FLAG_ADDR, variant
        assert block["cur_opponent"] == profile.CUR_OPPONENT_ADDR, variant
        assert block["enemy_party_count"] == profile.ENEMY_COUNT_ADDR, variant
        block.update({name: safe[name] for name in ANCHORS})
        block.update(source=source, trainer_battle=2, version="gen1-battle-init-v1")
        result["titles"][variant] = block
    return result


def lua_literal(value):
    if isinstance(value, dict):
        return "{" + ",".join("[" + json.dumps(k) + "]=" + lua_literal(v) for k, v in sorted(value.items())) + "}"
    if isinstance(value, str):
        return json.dumps(value)
    if type(value) is int:
        return str(value)
    raise TypeError(value)


def generate():
    value = build()
    encoded = json.dumps(value, indent=2, sort_keys=True) + "\n"
    text = ("-- Generated by tools/gen_gen1_rival_team_checkpoint.py from data/pret_syms.json"
            " and lua/games/gen1_rby.lua.\nreturn " + lua_literal(value) + "\n")
    return encoded, text


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    encoded, text = generate()
    if args.check:
        assert OUTPUT.read_text(encoding="utf-8") == encoded and LUA.read_text(encoding="utf-8") == text, \
            "rival team checkpoint data is stale"
    else:
        OUTPUT.write_text(encoded, encoding="utf-8", newline="\n")
        LUA.write_text(text, encoding="utf-8", newline="\n")
