/* Generated by patch/tools/native_layout.py. Do not edit. Ownership UNRESOLVED. */
#ifndef SLINK_NATIVE_LAYOUT_GENERATED_H
#define SLINK_NATIVE_LAYOUT_GENERATED_H
#include <stddef.h>
#define SLINK_NATIVE_LAYOUT_SHA256 "3c10dcd8af7e5dc91684a6a14bc888f66f348464e463ab11db70b2b6d299885d"
#define SLINK_ARENA_ADDR 0x203F800
#define SLINK_ARENA_SIZE 0x800
#define SLINK_CODE_BASE 0x8378F70
#define SLINK_CODE_SIZE 0x14000
#define SLINK_CAPABILITY_MASK 0x1F
#define SLINK_ABI 0x2
#define SLINK_ARGUMENT_BYTES 0xE
#define SLINK_CONTEXT_GUARD_TAG 0xC2
#define SLINK_CONTEXT_OFFSET 0xE
#define SLINK_DESCRIPTOR_MAGIC 0x32444C53
#define SLINK_DESCRIPTOR_VERSION 0x1
#define SLINK_RECEIPT_RESERVATION_OFFSET 0x8
#define SLINK_RESERVATION_BYTES 0x8
#define SLINK_RESERVATION_OFFSET 0x18
#define SLINK_SIGNATURE 0x4B4E4C53
#define SLINK_STORAGE_GUARD 0xA2
#define SLINK_CONTEXT_CALLBACK2_OFFSET 0x10
#define SLINK_CONTEXT_GUARD_OFFSET 0x17
#define SLINK_CONTEXT_MAP_GROUP_OFFSET 0xE
#define SLINK_CONTEXT_MAP_NUM_OFFSET 0xF
#define SLINK_CONTEXT_PLAYER_ID_OFFSET 0x16
#define SLINK_CONTEXT_SCRIPT_LOCK_OFFSET 0x14
#define SLINK_CONTEXT_SWAP_ACTIVE_OFFSET 0x15
#define SLINK_MAILBOX_ADDR 0x203F800
#define SLINK_MAILBOX_SIZE 0x40
#define SLINK_SWAP_ADDR 0x203F840
#define SLINK_SWAP_SIZE 0x8
#define SLINK_GHOST_ADDR 0x203F850
#define SLINK_GHOST_SIZE 0x2C
#define SLINK_ARMED_MOVE_ADDR 0x203F8C0
#define SLINK_ARMED_MOVE_SIZE 0x8
#define SLINK_PEER_INTERACT_ADDR 0x203F8D0
#define SLINK_PEER_INTERACT_SIZE 0x4
#define SLINK_TRADE_NPC_ADDR 0x203F8D4
#define SLINK_TRADE_NPC_SIZE 0x4
#define SLINK_CALC_OFF_ADDR 0x203F8D8
#define SLINK_CALC_OFF_SIZE 0x1
#define SLINK_SCRIPT_ADDR 0x203F8E0
#define SLINK_SCRIPT_SIZE 0x20
#define SLINK_TEXT_ADDR 0x203F900
#define SLINK_TEXT_SIZE 0x100
#define SLINK_BLOB_ADDR 0x203FA00
#define SLINK_BLOB_SIZE 0x258
#define SLINK_GHOST_PALETTE_ADDR 0x203FC60
#define SLINK_GHOST_PALETTE_SIZE 0x20
#define SLINK_UI_ADDR 0x203FC80
#define SLINK_UI_SIZE 0xC
#define SLINK_CHOICES_ADDR 0x203FC90
#define SLINK_CHOICES_SIZE 0x70
#define SLINK_BATTLE_NOTIF_ADDR 0x203FD00
#define SLINK_BATTLE_NOTIF_SIZE 0x8
#define SLINK_EVENTS_ADDR 0x203FD10
#define SLINK_EVENTS_SIZE 0x34
#define SLINK_INFO_ADDR 0x203FD44
#define SLINK_INFO_SIZE 0x108
#define SLINK_ASSERT_ARMED_MOVE(T) \
_Static_assert(sizeof(T) == 8, "ArmedMove size drift"); \
_Static_assert(_Alignof(T) == 2, "ArmedMove alignment drift"); \
_Static_assert(offsetof(T, armed) == 0, "ArmedMove.armed offset drift"); \
_Static_assert(sizeof(((T *)0)->armed) == 1, "ArmedMove.armed width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->armed), volatile u8), "ArmedMove.armed type/shape drift"); \
_Static_assert(offsetof(T, battler) == 1, "ArmedMove.battler offset drift"); \
_Static_assert(sizeof(((T *)0)->battler) == 1, "ArmedMove.battler width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->battler), volatile u8), "ArmedMove.battler type/shape drift"); \
_Static_assert(offsetof(T, move_pos) == 2, "ArmedMove.move_pos offset drift"); \
_Static_assert(sizeof(((T *)0)->move_pos) == 1, "ArmedMove.move_pos width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->move_pos), volatile u8), "ArmedMove.move_pos type/shape drift"); \
_Static_assert(offsetof(T, target) == 3, "ArmedMove.target offset drift"); \
_Static_assert(sizeof(((T *)0)->target) == 1, "ArmedMove.target width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->target), volatile u8), "ArmedMove.target type/shape drift"); \
_Static_assert(offsetof(T, seq) == 4, "ArmedMove.seq offset drift"); \
_Static_assert(sizeof(((T *)0)->seq) == 2, "ArmedMove.seq width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->seq), volatile u16), "ArmedMove.seq type/shape drift"); \
_Static_assert(offsetof(T, frames) == 6, "ArmedMove.frames offset drift"); \
_Static_assert(sizeof(((T *)0)->frames) == 2, "ArmedMove.frames width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->frames), volatile u16), "ArmedMove.frames type/shape drift")
#define SLINK_ASSERT_BATTLE_NOTIF(T) \
_Static_assert(sizeof(T) == 8, "BattleNotif size drift"); \
_Static_assert(_Alignof(T) == 2, "BattleNotif alignment drift"); \
_Static_assert(offsetof(T, active) == 0, "BattleNotif.active offset drift"); \
_Static_assert(sizeof(((T *)0)->active) == 1, "BattleNotif.active width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->active), volatile u8), "BattleNotif.active type/shape drift"); \
_Static_assert(offsetof(T, win) == 1, "BattleNotif.win offset drift"); \
_Static_assert(sizeof(((T *)0)->win) == 1, "BattleNotif.win width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->win), volatile u8), "BattleNotif.win type/shape drift"); \
_Static_assert(offsetof(T, task) == 2, "BattleNotif.task offset drift"); \
_Static_assert(sizeof(((T *)0)->task) == 1, "BattleNotif.task width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->task), volatile u8), "BattleNotif.task type/shape drift"); \
_Static_assert(offsetof(T, phase) == 3, "BattleNotif.phase offset drift"); \
_Static_assert(sizeof(((T *)0)->phase) == 1, "BattleNotif.phase width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->phase), volatile u8), "BattleNotif.phase type/shape drift"); \
_Static_assert(offsetof(T, frames) == 4, "BattleNotif.frames offset drift"); \
_Static_assert(sizeof(((T *)0)->frames) == 2, "BattleNotif.frames width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->frames), volatile u16), "BattleNotif.frames type/shape drift"); \
_Static_assert(offsetof(T, _pad2) == 6, "BattleNotif._pad2 offset drift"); \
_Static_assert(sizeof(((T *)0)->_pad2) == 2, "BattleNotif._pad2 width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->_pad2), volatile u16), "BattleNotif._pad2 type/shape drift")
#define SLINK_ASSERT_EV_RING(T) \
_Static_assert(sizeof(T) == 52, "EvRing size drift"); \
_Static_assert(_Alignof(T) == 4, "EvRing alignment drift"); \
_Static_assert(offsetof(T, wr) == 0, "EvRing.wr offset drift"); \
_Static_assert(sizeof(((T *)0)->wr) == 1, "EvRing.wr width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->wr), volatile u8), "EvRing.wr type/shape drift"); \
_Static_assert(offsetof(T, rd) == 1, "EvRing.rd offset drift"); \
_Static_assert(sizeof(((T *)0)->rd) == 1, "EvRing.rd width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->rd), volatile u8), "EvRing.rd type/shape drift"); \
_Static_assert(offsetof(T, overflow) == 2, "EvRing.overflow offset drift"); \
_Static_assert(sizeof(((T *)0)->overflow) == 1, "EvRing.overflow width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->overflow), volatile u8), "EvRing.overflow type/shape drift"); \
_Static_assert(offsetof(T, inb) == 3, "EvRing.inb offset drift"); \
_Static_assert(sizeof(((T *)0)->inb) == 1, "EvRing.inb width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->inb), volatile u8), "EvRing.inb type/shape drift"); \
_Static_assert(offsetof(T, pfc) == 4, "EvRing.pfc offset drift"); \
_Static_assert(sizeof(((T *)0)->pfc) == 1, "EvRing.pfc width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pfc), volatile u8), "EvRing.pfc type/shape drift"); \
_Static_assert(offsetof(T, ofc) == 5, "EvRing.ofc offset drift"); \
_Static_assert(sizeof(((T *)0)->ofc) == 1, "EvRing.ofc width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->ofc), volatile u8), "EvRing.ofc type/shape drift"); \
_Static_assert(offsetof(T, prim) == 6, "EvRing.prim offset drift"); \
_Static_assert(sizeof(((T *)0)->prim) == 1, "EvRing.prim width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->prim), volatile u8), "EvRing.prim type/shape drift"); \
_Static_assert(offsetof(T, pcnt) == 7, "EvRing.pcnt offset drift"); \
_Static_assert(sizeof(((T *)0)->pcnt) == 1, "EvRing.pcnt width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pcnt), volatile u8), "EvRing.pcnt type/shape drift"); \
_Static_assert(offsetof(T, ev) == 8, "EvRing.ev offset drift"); \
_Static_assert(sizeof(((T *)0)->ev) == 32, "EvRing.ev width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->ev), volatile u32[8]), "EvRing.ev type/shape drift"); \
_Static_assert(offsetof(T, spc) == 40, "EvRing.spc offset drift"); \
_Static_assert(sizeof(((T *)0)->spc) == 12, "EvRing.spc width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->spc), volatile u16[6]), "EvRing.spc type/shape drift")
#define SLINK_ASSERT_GHOST_STATE(T) \
_Static_assert(sizeof(T) == 44, "GhostState size drift"); \
_Static_assert(_Alignof(T) == 4, "GhostState alignment drift"); \
_Static_assert(offsetof(T, active) == 0, "GhostState.active offset drift"); \
_Static_assert(sizeof(((T *)0)->active) == 1, "GhostState.active width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->active), volatile u8), "GhostState.active type/shape drift"); \
_Static_assert(offsetof(T, oeId) == 1, "GhostState.oeId offset drift"); \
_Static_assert(sizeof(((T *)0)->oeId) == 1, "GhostState.oeId width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->oeId), volatile u8), "GhostState.oeId type/shape drift"); \
_Static_assert(offsetof(T, gfxId) == 2, "GhostState.gfxId offset drift"); \
_Static_assert(sizeof(((T *)0)->gfxId) == 1, "GhostState.gfxId width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->gfxId), volatile u8), "GhostState.gfxId type/shape drift"); \
_Static_assert(offsetof(T, curGfx) == 3, "GhostState.curGfx offset drift"); \
_Static_assert(sizeof(((T *)0)->curGfx) == 1, "GhostState.curGfx width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->curGfx), volatile u8), "GhostState.curGfx type/shape drift"); \
_Static_assert(offsetof(T, localId) == 4, "GhostState.localId offset drift"); \
_Static_assert(sizeof(((T *)0)->localId) == 1, "GhostState.localId width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->localId), volatile u8), "GhostState.localId type/shape drift"); \
_Static_assert(offsetof(T, flags) == 5, "GhostState.flags offset drift"); \
_Static_assert(sizeof(((T *)0)->flags) == 1, "GhostState.flags width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->flags), volatile u8), "GhostState.flags type/shape drift"); \
_Static_assert(offsetof(T, wx) == 6, "GhostState.wx offset drift"); \
_Static_assert(sizeof(((T *)0)->wx) == 2, "GhostState.wx width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->wx), volatile s16), "GhostState.wx type/shape drift"); \
_Static_assert(offsetof(T, wy) == 8, "GhostState.wy offset drift"); \
_Static_assert(sizeof(((T *)0)->wy) == 2, "GhostState.wy width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->wy), volatile s16), "GhostState.wy type/shape drift"); \
_Static_assert(offsetof(T, face) == 10, "GhostState.face offset drift"); \
_Static_assert(sizeof(((T *)0)->face) == 1, "GhostState.face width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->face), volatile u8), "GhostState.face type/shape drift"); \
_Static_assert(offsetof(T, mv) == 11, "GhostState.mv offset drift"); \
_Static_assert(sizeof(((T *)0)->mv) == 1, "GhostState.mv width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->mv), volatile u8), "GhostState.mv type/shape drift"); \
_Static_assert(offsetof(T, pmapGroup) == 12, "GhostState.pmapGroup offset drift"); \
_Static_assert(sizeof(((T *)0)->pmapGroup) == 1, "GhostState.pmapGroup width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pmapGroup), volatile u8), "GhostState.pmapGroup type/shape drift"); \
_Static_assert(offsetof(T, pmapNum) == 13, "GhostState.pmapNum offset drift"); \
_Static_assert(sizeof(((T *)0)->pmapNum) == 1, "GhostState.pmapNum width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pmapNum), volatile u8), "GhostState.pmapNum type/shape drift"); \
_Static_assert(offsetof(T, snap) == 14, "GhostState.snap offset drift"); \
_Static_assert(sizeof(((T *)0)->snap) == 1, "GhostState.snap width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->snap), volatile u8), "GhostState.snap type/shape drift"); \
_Static_assert(offsetof(T, an) == 15, "GhostState.an offset drift"); \
_Static_assert(sizeof(((T *)0)->an) == 1, "GhostState.an width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->an), volatile u8), "GhostState.an type/shape drift"); \
_Static_assert(offsetof(T, run) == 16, "GhostState.run offset drift"); \
_Static_assert(sizeof(((T *)0)->run) == 1, "GhostState.run width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->run), volatile u8), "GhostState.run type/shape drift"); \
_Static_assert(offsetof(T, avatarDirty) == 17, "GhostState.avatarDirty offset drift"); \
_Static_assert(sizeof(((T *)0)->avatarDirty) == 1, "GhostState.avatarDirty width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->avatarDirty), volatile u8), "GhostState.avatarDirty type/shape drift"); \
_Static_assert(offsetof(T, gfxHi) == 18, "GhostState.gfxHi offset drift"); \
_Static_assert(sizeof(((T *)0)->gfxHi) == 1, "GhostState.gfxHi width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->gfxHi), volatile u8), "GhostState.gfxHi type/shape drift"); \
_Static_assert(offsetof(T, curGfxHi) == 19, "GhostState.curGfxHi offset drift"); \
_Static_assert(sizeof(((T *)0)->curGfxHi) == 1, "GhostState.curGfxHi width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->curGfxHi), volatile u8), "GhostState.curGfxHi type/shape drift"); \
_Static_assert(offsetof(T, imgs) == 20, "GhostState.imgs offset drift"); \
_Static_assert(sizeof(((T *)0)->imgs) == 4, "GhostState.imgs width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->imgs), volatile u32), "GhostState.imgs type/shape drift"); \
_Static_assert(offsetof(T, anims) == 24, "GhostState.anims offset drift"); \
_Static_assert(sizeof(((T *)0)->anims) == 4, "GhostState.anims width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->anims), volatile u32), "GhostState.anims type/shape drift"); \
_Static_assert(offsetof(T, dispx) == 28, "GhostState.dispx offset drift"); \
_Static_assert(sizeof(((T *)0)->dispx) == 4, "GhostState.dispx width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->dispx), volatile s32), "GhostState.dispx type/shape drift"); \
_Static_assert(offsetof(T, dispy) == 32, "GhostState.dispy offset drift"); \
_Static_assert(sizeof(((T *)0)->dispy) == 4, "GhostState.dispy width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->dispy), volatile s32), "GhostState.dispy type/shape drift"); \
_Static_assert(offsetof(T, cx) == 36, "GhostState.cx offset drift"); \
_Static_assert(sizeof(((T *)0)->cx) == 2, "GhostState.cx width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->cx), volatile s16), "GhostState.cx type/shape drift"); \
_Static_assert(offsetof(T, cy) == 38, "GhostState.cy offset drift"); \
_Static_assert(sizeof(((T *)0)->cy) == 2, "GhostState.cy width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->cy), volatile s16), "GhostState.cy type/shape drift"); \
_Static_assert(offsetof(T, leadpx) == 40, "GhostState.leadpx offset drift"); \
_Static_assert(sizeof(((T *)0)->leadpx) == 1, "GhostState.leadpx width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->leadpx), volatile u8), "GhostState.leadpx type/shape drift"); \
_Static_assert(offsetof(T, paletteSlot) == 41, "GhostState.paletteSlot offset drift"); \
_Static_assert(sizeof(((T *)0)->paletteSlot) == 1, "GhostState.paletteSlot width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->paletteSlot), volatile u8), "GhostState.paletteSlot type/shape drift"); \
_Static_assert(offsetof(T, ownedSprite) == 42, "GhostState.ownedSprite offset drift"); \
_Static_assert(sizeof(((T *)0)->ownedSprite) == 1, "GhostState.ownedSprite width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->ownedSprite), volatile u8), "GhostState.ownedSprite type/shape drift"); \
_Static_assert(offsetof(T, lifecycle) == 43, "GhostState.lifecycle offset drift"); \
_Static_assert(sizeof(((T *)0)->lifecycle) == 1, "GhostState.lifecycle width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->lifecycle), volatile u8), "GhostState.lifecycle type/shape drift")
#define SLINK_ASSERT_MAILBOX(T) \
_Static_assert(sizeof(T) == 64, "Mailbox size drift"); \
_Static_assert(_Alignof(T) == 4, "Mailbox alignment drift"); \
_Static_assert(offsetof(T, signature) == 0, "Mailbox.signature offset drift"); \
_Static_assert(sizeof(((T *)0)->signature) == 4, "Mailbox.signature width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->signature), volatile u32), "Mailbox.signature type/shape drift"); \
_Static_assert(offsetof(T, abi_version) == 4, "Mailbox.abi_version offset drift"); \
_Static_assert(sizeof(((T *)0)->abi_version) == 2, "Mailbox.abi_version width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->abi_version), volatile u16), "Mailbox.abi_version type/shape drift"); \
_Static_assert(offsetof(T, opcode) == 6, "Mailbox.opcode offset drift"); \
_Static_assert(sizeof(((T *)0)->opcode) == 2, "Mailbox.opcode width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->opcode), volatile u16), "Mailbox.opcode type/shape drift"); \
_Static_assert(offsetof(T, seq) == 8, "Mailbox.seq offset drift"); \
_Static_assert(sizeof(((T *)0)->seq) == 2, "Mailbox.seq width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->seq), volatile u16), "Mailbox.seq type/shape drift"); \
_Static_assert(offsetof(T, status) == 10, "Mailbox.status offset drift"); \
_Static_assert(sizeof(((T *)0)->status) == 2, "Mailbox.status width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->status), volatile u16), "Mailbox.status type/shape drift"); \
_Static_assert(offsetof(T, ack_seq) == 12, "Mailbox.ack_seq offset drift"); \
_Static_assert(sizeof(((T *)0)->ack_seq) == 2, "Mailbox.ack_seq width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->ack_seq), volatile u16), "Mailbox.ack_seq type/shape drift"); \
_Static_assert(offsetof(T, reason) == 14, "Mailbox.reason offset drift"); \
_Static_assert(sizeof(((T *)0)->reason) == 2, "Mailbox.reason width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->reason), volatile u16), "Mailbox.reason type/shape drift"); \
_Static_assert(offsetof(T, args) == 16, "Mailbox.args offset drift"); \
_Static_assert(sizeof(((T *)0)->args) == 32, "Mailbox.args width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->args), volatile u8[32]), "Mailbox.args type/shape drift"); \
_Static_assert(offsetof(T, result) == 48, "Mailbox.result offset drift"); \
_Static_assert(sizeof(((T *)0)->result) == 16, "Mailbox.result width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->result), volatile u8[16]), "Mailbox.result type/shape drift")
#define SLINK_ASSERT_NATIVE_DESCRIPTOR(T) \
_Static_assert(sizeof(T) == 156, "NativeDescriptor size drift"); \
_Static_assert(_Alignof(T) == 4, "NativeDescriptor alignment drift"); \
_Static_assert(offsetof(T, magic) == 0, "NativeDescriptor.magic offset drift"); \
_Static_assert(sizeof(((T *)0)->magic) == 4, "NativeDescriptor.magic width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->magic), volatile u32), "NativeDescriptor.magic type/shape drift"); \
_Static_assert(offsetof(T, descriptor_version) == 4, "NativeDescriptor.descriptor_version offset drift"); \
_Static_assert(sizeof(((T *)0)->descriptor_version) == 2, "NativeDescriptor.descriptor_version width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->descriptor_version), volatile u16), "NativeDescriptor.descriptor_version type/shape drift"); \
_Static_assert(offsetof(T, abi) == 6, "NativeDescriptor.abi offset drift"); \
_Static_assert(sizeof(((T *)0)->abi) == 2, "NativeDescriptor.abi width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->abi), volatile u16), "NativeDescriptor.abi type/shape drift"); \
_Static_assert(offsetof(T, size) == 8, "NativeDescriptor.size offset drift"); \
_Static_assert(sizeof(((T *)0)->size) == 4, "NativeDescriptor.size width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->size), volatile u32), "NativeDescriptor.size type/shape drift"); \
_Static_assert(offsetof(T, capability_mask) == 12, "NativeDescriptor.capability_mask offset drift"); \
_Static_assert(sizeof(((T *)0)->capability_mask) == 4, "NativeDescriptor.capability_mask width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->capability_mask), volatile u32), "NativeDescriptor.capability_mask type/shape drift"); \
_Static_assert(offsetof(T, mailbox_address) == 16, "NativeDescriptor.mailbox_address offset drift"); \
_Static_assert(sizeof(((T *)0)->mailbox_address) == 4, "NativeDescriptor.mailbox_address width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->mailbox_address), volatile u32), "NativeDescriptor.mailbox_address type/shape drift"); \
_Static_assert(offsetof(T, mailbox_size) == 20, "NativeDescriptor.mailbox_size offset drift"); \
_Static_assert(sizeof(((T *)0)->mailbox_size) == 2, "NativeDescriptor.mailbox_size width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->mailbox_size), volatile u16), "NativeDescriptor.mailbox_size type/shape drift"); \
_Static_assert(offsetof(T, storage_guard) == 22, "NativeDescriptor.storage_guard offset drift"); \
_Static_assert(sizeof(((T *)0)->storage_guard) == 2, "NativeDescriptor.storage_guard width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->storage_guard), volatile u16), "NativeDescriptor.storage_guard type/shape drift"); \
_Static_assert(offsetof(T, build_id) == 24, "NativeDescriptor.build_id offset drift"); \
_Static_assert(sizeof(((T *)0)->build_id) == 65, "NativeDescriptor.build_id width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->build_id), volatile char[65]), "NativeDescriptor.build_id type/shape drift"); \
_Static_assert(offsetof(T, layout_sha256) == 89, "NativeDescriptor.layout_sha256 offset drift"); \
_Static_assert(sizeof(((T *)0)->layout_sha256) == 65, "NativeDescriptor.layout_sha256 width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->layout_sha256), volatile char[65]), "NativeDescriptor.layout_sha256 type/shape drift")
#define SLINK_ASSERT_SLINK_INFO(T) \
_Static_assert(sizeof(T) == 264, "SlinkInfo size drift"); \
_Static_assert(_Alignof(T) == 1, "SlinkInfo alignment drift"); \
_Static_assert(offsetof(T, enable) == 0, "SlinkInfo.enable offset drift"); \
_Static_assert(sizeof(((T *)0)->enable) == 1, "SlinkInfo.enable width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->enable), volatile u8), "SlinkInfo.enable type/shape drift"); \
_Static_assert(offsetof(T, opened) == 1, "SlinkInfo.opened offset drift"); \
_Static_assert(sizeof(((T *)0)->opened) == 1, "SlinkInfo.opened width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->opened), volatile u8), "SlinkInfo.opened type/shape drift"); \
_Static_assert(offsetof(T, drawn) == 2, "SlinkInfo.drawn offset drift"); \
_Static_assert(sizeof(((T *)0)->drawn) == 1, "SlinkInfo.drawn width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->drawn), volatile u8), "SlinkInfo.drawn type/shape drift"); \
_Static_assert(offsetof(T, lines) == 3, "SlinkInfo.lines offset drift"); \
_Static_assert(sizeof(((T *)0)->lines) == 1, "SlinkInfo.lines width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->lines), volatile u8), "SlinkInfo.lines type/shape drift"); \
_Static_assert(offsetof(T, page) == 4, "SlinkInfo.page offset drift"); \
_Static_assert(sizeof(((T *)0)->page) == 1, "SlinkInfo.page width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->page), volatile u8), "SlinkInfo.page type/shape drift"); \
_Static_assert(offsetof(T, pages) == 5, "SlinkInfo.pages offset drift"); \
_Static_assert(sizeof(((T *)0)->pages) == 1, "SlinkInfo.pages width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pages), volatile u8), "SlinkInfo.pages type/shape drift"); \
_Static_assert(offsetof(T, gen) == 6, "SlinkInfo.gen offset drift"); \
_Static_assert(sizeof(((T *)0)->gen) == 1, "SlinkInfo.gen width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->gen), volatile u8), "SlinkInfo.gen type/shape drift"); \
_Static_assert(offsetof(T, fadephase) == 7, "SlinkInfo.fadephase offset drift"); \
_Static_assert(sizeof(((T *)0)->fadephase) == 1, "SlinkInfo.fadephase width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->fadephase), volatile u8), "SlinkInfo.fadephase type/shape drift"); \
_Static_assert(offsetof(T, line) == 8, "SlinkInfo.line offset drift"); \
_Static_assert(sizeof(((T *)0)->line) == 256, "SlinkInfo.line width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->line), volatile u8[8][32]), "SlinkInfo.line type/shape drift")
#define SLINK_ASSERT_SLINK_STATE(T) \
_Static_assert(sizeof(T) == 4, "SlinkState size drift"); \
_Static_assert(_Alignof(T) == 1, "SlinkState alignment drift"); \
_Static_assert(offsetof(T, _rsvd0) == 0, "SlinkState._rsvd0 offset drift"); \
_Static_assert(sizeof(((T *)0)->_rsvd0) == 1, "SlinkState._rsvd0 width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->_rsvd0), volatile u8), "SlinkState._rsvd0 type/shape drift"); \
_Static_assert(offsetof(T, pi_armed) == 1, "SlinkState.pi_armed offset drift"); \
_Static_assert(sizeof(((T *)0)->pi_armed) == 1, "SlinkState.pi_armed width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pi_armed), volatile u8), "SlinkState.pi_armed type/shape drift"); \
_Static_assert(offsetof(T, pi_oe) == 2, "SlinkState.pi_oe offset drift"); \
_Static_assert(sizeof(((T *)0)->pi_oe) == 1, "SlinkState.pi_oe width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pi_oe), volatile u8), "SlinkState.pi_oe type/shape drift"); \
_Static_assert(offsetof(T, pi_count) == 3, "SlinkState.pi_count offset drift"); \
_Static_assert(sizeof(((T *)0)->pi_count) == 1, "SlinkState.pi_count width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pi_count), volatile u8), "SlinkState.pi_count type/shape drift")
#define SLINK_ASSERT_SWAP_STATE(T) \
_Static_assert(sizeof(T) == 8, "SwapState size drift"); \
_Static_assert(_Alignof(T) == 4, "SwapState alignment drift"); \
_Static_assert(offsetof(T, active) == 0, "SwapState.active offset drift"); \
_Static_assert(sizeof(((T *)0)->active) == 1, "SwapState.active width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->active), volatile u8), "SwapState.active type/shape drift"); \
_Static_assert(offsetof(T, seq) == 1, "SwapState.seq offset drift"); \
_Static_assert(sizeof(((T *)0)->seq) == 1, "SwapState.seq width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->seq), volatile u8), "SwapState.seq type/shape drift"); \
_Static_assert(offsetof(T, diverged) == 2, "SwapState.diverged offset drift"); \
_Static_assert(sizeof(((T *)0)->diverged) == 1, "SwapState.diverged width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->diverged), volatile u8), "SwapState.diverged type/shape drift"); \
_Static_assert(offsetof(T, _pad) == 3, "SwapState._pad offset drift"); \
_Static_assert(sizeof(((T *)0)->_pad) == 1, "SwapState._pad width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->_pad), volatile u8), "SwapState._pad type/shape drift"); \
_Static_assert(offsetof(T, real_pid) == 4, "SwapState.real_pid offset drift"); \
_Static_assert(sizeof(((T *)0)->real_pid) == 4, "SwapState.real_pid width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->real_pid), volatile u32), "SwapState.real_pid type/shape drift")
#define SLINK_ASSERT_TRADE_NPC_STATE(T) \
_Static_assert(sizeof(T) == 4, "TradeNpcState size drift"); \
_Static_assert(_Alignof(T) == 1, "TradeNpcState alignment drift"); \
_Static_assert(offsetof(T, enable) == 0, "TradeNpcState.enable offset drift"); \
_Static_assert(sizeof(((T *)0)->enable) == 1, "TradeNpcState.enable width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->enable), volatile u8), "TradeNpcState.enable type/shape drift"); \
_Static_assert(offsetof(T, oeId) == 1, "TradeNpcState.oeId offset drift"); \
_Static_assert(sizeof(((T *)0)->oeId) == 1, "TradeNpcState.oeId width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->oeId), volatile u8), "TradeNpcState.oeId type/shape drift"); \
_Static_assert(offsetof(T, mapG) == 2, "TradeNpcState.mapG offset drift"); \
_Static_assert(sizeof(((T *)0)->mapG) == 1, "TradeNpcState.mapG width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->mapG), volatile u8), "TradeNpcState.mapG type/shape drift"); \
_Static_assert(offsetof(T, mapN) == 3, "TradeNpcState.mapN offset drift"); \
_Static_assert(sizeof(((T *)0)->mapN) == 1, "TradeNpcState.mapN width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->mapN), volatile u8), "TradeNpcState.mapN type/shape drift")
#define SLINK_ASSERT_UI_STATE(T) \
_Static_assert(sizeof(T) == 12, "UiState size drift"); \
_Static_assert(_Alignof(T) == 4, "UiState alignment drift"); \
_Static_assert(offsetof(T, pending) == 0, "UiState.pending offset drift"); \
_Static_assert(sizeof(((T *)0)->pending) == 1, "UiState.pending width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->pending), volatile u8), "UiState.pending type/shape drift"); \
_Static_assert(offsetof(T, kind) == 1, "UiState.kind offset drift"); \
_Static_assert(sizeof(((T *)0)->kind) == 1, "UiState.kind width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->kind), volatile u8), "UiState.kind type/shape drift"); \
_Static_assert(offsetof(T, seq) == 2, "UiState.seq offset drift"); \
_Static_assert(sizeof(((T *)0)->seq) == 2, "UiState.seq width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->seq), volatile u16), "UiState.seq type/shape drift"); \
_Static_assert(offsetof(T, frames) == 4, "UiState.frames offset drift"); \
_Static_assert(sizeof(((T *)0)->frames) == 2, "UiState.frames width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->frames), volatile u16), "UiState.frames type/shape drift"); \
_Static_assert(offsetof(T, phase) == 6, "UiState.phase offset drift"); \
_Static_assert(sizeof(((T *)0)->phase) == 1, "UiState.phase width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->phase), volatile u8), "UiState.phase type/shape drift"); \
_Static_assert(offsetof(T, _pad) == 7, "UiState._pad offset drift"); \
_Static_assert(sizeof(((T *)0)->_pad) == 1, "UiState._pad width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->_pad), volatile u8), "UiState._pad type/shape drift"); \
_Static_assert(offsetof(T, fieldCb) == 8, "UiState.fieldCb offset drift"); \
_Static_assert(sizeof(((T *)0)->fieldCb) == 4, "UiState.fieldCb width drift"); \
_Static_assert(__builtin_types_compatible_p(__typeof__(((T *)0)->fieldCb), volatile u32), "UiState.fieldCb type/shape drift")
#define SLINK_STRINGIFY_(x) #x
#define SLINK_STRINGIFY(x) SLINK_STRINGIFY_(x)
#endif
