"""Falsifier for the pokeemerald-expansion trainer sets (card XC4).

Mirrors tests/unit/test_calc_trainer_sets.py's species+level whole-file multiset check: parses
the PINNED expansion source directly (independent of tools/gen_gen3_exp_trainers.py's own
block-based parser -- a flat regex scan is the "ground truth from the decomp, not from a second
copy" this repo's other trainer-set tests already use) and checks it against both generated
outputs: the vendored calc setdex (calc/src/js/data/sets/games/EmeraldExpansion.js) and the
trainer-panel data pack (data/games/gen3_exp/28877d73/gen3_exp_trainers.json).

OMP cx-081c78d3 F3 extended this beyond species+level: held item, nature and IVs are always
explicit in this build (checked full-equality, whole-file multiset, same style as species+level);
explicit .moves are checked too, but only as a SUBSET (a mon with no .moves gets the level-up
learnset default instead, and the JSON pack doesn't record which branch produced its "moves" list,
so a full-multiset equality on moves would conflate the two) -- see
test_explicit_moves_in_source_all_appear_in_the_json_pack and, for the default branch,
test_default_derived_moves_match_a_learnset_sample. Ponytail note: this does not repeat the
full-fidelity comparison a second time for the JS setdex (calc/src/js/...); that file is derived
from the exact same in-process `trainers` dict as the JSON pack in one tools/gen_gen3_exp_trainers.py
run, so a JSON-pack fidelity bug would already be visible here -- add a JS-side copy only if the
two outputs are ever generated by separate passes.

The pinned source (data/gen3_exp_sources.lock.json: tag expansion/1.17.0, commit
e8bd1cd7b03fc032ea37e3ecd38b379b5d01a1e7) lives only on the build host (ssh hgbox, ~/slink-exp)
-- never checked into this repo -- so most runs of this file hit the "source not found" skip.
Point SLINK_EXPANSION_SRC at a local copy (or a `.cache/expansion/<commit>` checkout under the
repo, same walk-up convention as pret) to run the source-comparison tests for real: an absent
source is a named skip, but a PRESENT source at the wrong commit is a hard failure, never a
silent pass -- the whole point of pinning.

The adapter tests at the bottom need no pinned source: they exercise the shipped data pack
directly. Only test_trainer_info_and_party_for_a_gym_leader is a literal (hardcoded) check; the
rest are derived-data oracles (OMP cx-081c78d3 F4 -- the previous trio just re-read the pack and
asserted it against itself, which can't fail when the generator itself is wrong).
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO))

from server.adapters import gen3_expansion as _gen3_expansion_mod  # noqa: E402
from server.adapters.gen3_expansion import ROM_TYPE, Gen3ExpansionAdapter  # noqa: E402
from server.adapters.gen3_frlge import default_moves  # noqa: E402
from tools.gen_area_map import _expansion_source_sha256  # noqa: E402
from tools.gen_gen3_exp_trainers import (  # noqa: E402
    AREA_MAP,
    KEY_CLASSES,
    UNBATTLED_KEY_CANDIDATES,
    _check_area_map_digest,
    enum_values,
    parse_learnset_tables,
    parse_species_learnset_symbols,
    pretty,
)
from tools.gen_gen3_trainers import area_of_map, map_jsons, map_keys, read as _read  # noqa: E402

_LOCK = json.loads((_REPO / "data/gen3_exp_sources.lock.json").read_text(encoding="utf-8"))
_PIN = _LOCK["source"]["commit"]
_JSON_PACK = _REPO / "data/games/gen3_exp/28877d73/gen3_exp_trainers.json"
_JS_SETDEX = _REPO / "calc/src/js/data/sets/games/EmeraldExpansion.js"
_AREAS_LUA = _REPO / "data/games/gen3_exp/28877d73/gen3_exp_areas.lua"


def _canon(s: str) -> str:
    """Fold a species name down to bare lowercase alnum -- sidesteps SPECIES_MR_MIME vs
    "Mr. Mime" / "Nidoran-F" vs SPECIES_NIDORAN_F without a per-name exceptions table."""
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _find_expansion_src() -> Path | None:
    env = os.environ.get("SLINK_EXPANSION_SRC")
    if env:
        return Path(env)
    d = _REPO
    for _ in range(6):
        cand = d / ".cache" / "expansion" / _PIN
        if cand.is_dir():
            return cand
        parent = d.parent
        if parent == d:
            break
        d = parent
    return None


def _git_head(path: Path) -> str | None:
    r = subprocess.run(["git", "-C", str(path), "rev-parse", "HEAD"], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else None


def _need_source() -> Path:
    src = _find_expansion_src()
    if src is None:
        pytest.skip(f"pokeemerald-expansion checkout not found (set SLINK_EXPANSION_SRC; pin {_PIN})")
    head = _git_head(src)
    assert head == _PIN, f"{src} is at {head}, not the pin {_PIN} (data/gen3_exp_sources.lock.json)"
    return src


def _source_full_records(src: Path) -> list[dict]:
    """Independent (not tools/gen_gen3_exp_trainers.py's block parser) flat scan of every mon in
    src/data/trainers.h: species+level (as before), plus whichever of .heldItem/.nature/.iv/
    .moves appear anywhere in that mon's block before the NEXT mon's .species begins -- the
    window spans from THIS mon's own .species (field order varies per mon: .iv sometimes comes
    before .lvl, sometimes after) up to the next ".species", so a later mon's fields are never
    misattributed to an earlier one and an earlier field is never missed. "moves" is None when
    the source has no explicit .moves for that mon (the level-up-learnset default applies
    instead -- see test_default_derived_moves_match_a_learnset_sample)."""
    text = re.sub(r"#line \d+\n\s*", "", (src / "src/data/trainers.h").read_text(encoding="utf-8"))
    species_ids = enum_values((src / "include/constants/species.h").read_text(encoding="utf-8"), "SPECIES_")
    move_ids = enum_values((src / "include/constants/moves.h").read_text(encoding="utf-8"), "MOVE_")
    item_ids = enum_values((src / "include/constants/items.h").read_text(encoding="utf-8"), "ITEM_")
    adapter = Gen3ExpansionAdapter(rom_type=ROM_TYPE)
    records = []
    for m in re.finditer(r"\.species\s*=\s*(SPECIES_\w+),.{1,300}?\.lvl\s*=\s*(\d+),", text, re.S):
        sid = species_ids.get(m[1])
        if sid is None:
            continue
        window = text[m.start():m.start() + 700]
        nxt = window.find(".species", len(".species"))
        if nxt != -1:
            window = window[:nxt]
        item_m = re.search(r"\.heldItem\s*=\s*(ITEM_\w+)", window)
        item = None
        if item_m and item_m[1] != "ITEM_NONE":
            iid = item_ids.get(item_m[1])
            item = adapter.calc_name("item", adapter.item_name(iid)) if iid else item_m[1]
        nat_m = re.search(r"\.nature\s*=\s*NATURE_(\w+)", window)
        nature = pretty(nat_m[1].replace("_", " ").lower()) if nat_m else None
        iv_m = re.search(r"\.iv\s*=\s*TRAINER_PARTY_IVS\(([^)]*)\)", window)
        ivs = None
        if iv_m:
            parts = [int(x.strip()) for x in iv_m[1].split(",")]
            if len(parts) == 6:
                hp, atk, df, spe, spa, spd = parts
                ivs = (("atk", atk), ("def", df), ("hp", hp), ("spa", spa), ("spd", spd), ("spe", spe))
        mv_m = re.search(r"\.moves\s*=\s*\{([^}]*)\}", window)
        moves = None
        if mv_m:
            macros = [mm.strip() for mm in mv_m[1].split(",") if mm.strip() and mm.strip() != "MOVE_NONE"]
            moves = tuple(adapter.calc_name("move", adapter.move_name(move_ids[mo])) if mo in move_ids else mo
                          for mo in macros)
        records.append({
            "species": _canon(adapter.calc_species(sid)), "level": int(m[2]),
            "item": item, "nature": nature, "ivs": ivs, "moves": moves,
        })
    return records


def _source_species_level_multiset(src: Path) -> Counter:
    return Counter((r["species"], r["level"]) for r in _source_full_records(src))


def _source_full_multiset(src: Path) -> Counter:
    """species+level+item+nature+ivs -- all always explicit or always None-if-absent in this
    build, so this is a full-equality multiset (unlike moves, see the module docstring)."""
    return Counter((r["species"], r["level"], r["item"], r["nature"], r["ivs"]) for r in _source_full_records(src))


def _source_explicit_moves_multiset(src: Path) -> Counter:
    return Counter((r["species"], r["level"], r["item"], r["nature"], r["ivs"], r["moves"])
                   for r in _source_full_records(src) if r["moves"] is not None)


def _json_pack_multiset() -> Counter:
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    c: Counter = Counter()
    for t in data["trainers"].values():
        for mon in t["party"]:
            c[(_canon(mon["species"]), mon["level"])] += 1
    return c


def _json_pack_mon_key(mon: dict) -> tuple:
    ivs = mon.get("ivs")
    ivs_t = tuple(sorted(ivs.items())) if ivs else None
    return (_canon(mon["species"]), mon["level"], mon.get("item"), mon.get("nature"), ivs_t)


def _json_pack_full_multiset() -> Counter:
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    return Counter(_json_pack_mon_key(mon) for t in data["trainers"].values() for mon in t["party"])


def _json_pack_moves_multiset() -> Counter:
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    c: Counter = Counter()
    for t in data["trainers"].values():
        for mon in t["party"]:
            moves = mon.get("moves")
            c[_json_pack_mon_key(mon) + (tuple(moves) if moves else None,)] += 1
    return c


def _js_setdex_dict() -> dict:
    text = _JS_SETDEX.read_text(encoding="utf-8")
    lines = [ln for ln in text.splitlines() if not ln.strip().startswith("//")]
    text = "\n".join(lines).strip()
    assert text.startswith("var "), _JS_SETDEX
    body = text[text.index("=") + 1:].strip().rstrip(";")
    return json.loads(body)


def _js_setdex_multiset() -> Counter:
    dex = _js_setdex_dict()
    c: Counter = Counter()
    for species, sets in dex.items():
        for entry in sets.values():
            c[(_canon(species), entry["level"])] += 1
    return c


def test_json_pack_identity_matches_lock_pin():
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    assert data["source"]["commit"] == _PIN


def test_gen3_exp_trainers_json_matches_pinned_source():
    src = _need_source()
    assert _json_pack_multiset() == _source_species_level_multiset(src)


def test_emerald_expansion_js_matches_pinned_source():
    src = _need_source()
    assert _js_setdex_multiset() == _source_species_level_multiset(src)


def test_gen3_exp_trainers_json_full_fidelity_matches_pinned_source():
    """species+level+item+nature+ivs, whole-file, full equality (OMP cx-081c78d3 F3)."""
    src = _need_source()
    assert _json_pack_full_multiset() == _source_full_multiset(src)


def test_explicit_moves_in_source_all_appear_in_the_json_pack():
    """Every mon whose .moves the source spells out explicitly must appear -- species, level,
    item, nature, ivs AND that exact move list -- in the JSON pack at least as many times as the
    source has it. A subset check, not full-multiset equality: the pack also carries
    level-up-learnset-derived move lists (no explicit .moves in source) mixed into the same
    "moves" field, and nothing in the pack says which branch produced any one entry."""
    src = _need_source()
    explicit = _source_explicit_moves_multiset(src)
    pack = _json_pack_moves_multiset()
    missing = explicit - pack
    assert not missing, dict(missing)


def test_default_derived_moves_match_a_learnset_sample():
    """A sample of mons the source gives NO .moves for (GiveBoxMonInitialMoveset's level-up
    learnset default applies instead): recompute the expected move list independently
    (server.adapters.gen3_frlge.default_moves() over the same learnset tables, not
    tools/gen_gen3_exp_trainers.py's own default_moveset() closure) and confirm the JSON pack
    has a matching entry for each sampled (species, level)."""
    src = _need_source()
    text = re.sub(r"#line \d+\n\s*", "", (src / "src/data/trainers.h").read_text(encoding="utf-8"))
    species_ids = enum_values((src / "include/constants/species.h").read_text(encoding="utf-8"), "SPECIES_")
    move_ids = enum_values((src / "include/constants/moves.h").read_text(encoding="utf-8"), "MOVE_")
    sp_learnset_sym = parse_species_learnset_symbols(src)
    learnset_tables = parse_learnset_tables(src)
    adapter = Gen3ExpansionAdapter(rom_type=ROM_TYPE)

    sample: list[tuple[str, int]] = []
    for m in re.finditer(r"\.species\s*=\s*(SPECIES_\w+),.{1,300}?\.lvl\s*=\s*(\d+),", text, re.S):
        window = text[m.start():m.start() + 700]
        nxt = window.find(".species", len(".species"))
        if nxt != -1:
            window = window[:nxt]
        if re.search(r"\.moves\s*=", window) or m[1] not in sp_learnset_sym:
            continue
        sample.append((m[1], int(m[2])))
        if len(sample) >= 25:
            break
    assert sample, "expected at least one default-moveset mon with a known learnset in this build"

    pack_moves: dict[tuple[str, int], set] = {}
    for t in json.loads(_JSON_PACK.read_text(encoding="utf-8"))["trainers"].values():
        for mon in t["party"]:
            key = (_canon(mon["species"]), mon["level"])
            pack_moves.setdefault(key, set()).add(tuple(mon.get("moves") or ()))

    for sp_macro, level in sample:
        sym = sp_learnset_sym[sp_macro]
        expected_macros = default_moves(learnset_tables.get(sym, []), level)
        expected = tuple(adapter.calc_name("move", adapter.move_name(move_ids[mv])) for mv in expected_macros)
        key = (_canon(adapter.calc_species(species_ids[sp_macro])), level)
        assert expected in pack_moves.get(key, set()), (sp_macro, level, expected, pack_moves.get(key))


def test_generator_check_passes_against_a_regenerated_copy():
    """OMP cx-081c78d3 F11: `--check` actually runs (and passes) when the pinned source is
    present, instead of only ever being exercised by hand."""
    src = _need_source()
    r = subprocess.run([sys.executable, str(_REPO / "tools/gen_gen3_exp_trainers.py"),
                         "--src", str(src), "--check"], capture_output=True, text=True)
    assert r.returncode == 0, r.stdout + r.stderr


# --------------------------------------------------------------------------------------
# Adapter tests -- no pinned source needed, exercise the shipped data pack directly.
# --------------------------------------------------------------------------------------

def _adapter() -> Gen3ExpansionAdapter:
    return Gen3ExpansionAdapter(rom_type=ROM_TYPE)


def _pack() -> dict:
    return json.loads(_JSON_PACK.read_text(encoding="utf-8"))


def test_trainer_info_and_party_for_a_gym_leader():
    a = _adapter()
    data = _pack()
    tid, roxanne = next((int(k), v) for k, v in data["trainers"].items() if v["const"] == "TRAINER_ROXANNE_1")
    assert a.trainer_info(tid) == ("Roxanne", "Leader")
    party = a.trainer_party(tid)
    assert party == roxanne["party"]
    assert [p["species"] for p in party] == ["Geodude", "Geodude", "Nosepass"]


def test_no_base_name_maps_to_more_than_one_trainer_index():
    """OMP cx-081c78d3 F1 falsifier: the Prep tab groups a vendored setdex key by the text
    before " | " (calc/src/js/slink_bridge.js's _buildTrainerIndex); if two different trainer
    ids ever produced the same base text, their parties would silently merge into one fake
    combined encounter (this is exactly what happened before compute_bases() -- a rematch
    tier's discriminator sat after the pipe, an opaque uniqueness key the Prep tab never reads
    for grouping)."""
    dex = _js_setdex_dict()
    base_to_indexes: dict[str, set] = {}
    for sets in dex.values():
        for key, entry in sets.items():
            pipe = key.find(" | ")
            base = key[:pipe].strip() if pipe != -1 else key
            base_to_indexes.setdefault(base, set()).add(entry["index"])
    collisions = {b: idx for b, idx in base_to_indexes.items() if len(idx) > 1}
    assert not collisions


def test_trainers_by_area_keys_are_client_emittable_areas():
    """Derived-data oracle (OMP cx-081c78d3 F3/F4): every area gen3_exp_trainers.json groups key
    trainers under must be an area id the Lua client can actually emit
    (data/games/gen3_exp/28877d73/gen3_exp_areas.lua's values), never a made-up or stale one."""
    data = _pack()
    lua_text = _AREAS_LUA.read_text(encoding="utf-8")
    valid_areas = set(re.findall(r'=\s*"([^"]+)"', lua_text))
    assert data["trainers_by_area"], "expected at least one area with key trainers"
    for area in data["trainers_by_area"]:
        assert area in valid_areas, area


def test_every_key_trainers_by_area_entry_is_flagged_key_and_matches_its_area():
    """Replaces the old mirror test (asserted the pack against itself): cross-checks
    trainers_by_area against the per-trainer records it was built from, and against the live
    adapter, independently of trusting either side alone."""
    a = _adapter()
    data = _pack()
    for area, tids in data["trainers_by_area"].items():
        assert tids, area
        for tid in tids:
            t = data["trainers"][str(tid)]
            assert t.get("key") is True
            assert t.get("area") == area
        assert sorted(a.trainers_for_area(area)) == sorted(tids)


def test_every_key_trainer_level_cap_equals_max_party_level():
    """Derived-data oracle (OMP cx-081c78d3 F3): level_cap is documented as "the trainer's own
    highest party level" -- prove it, for every key trainer, not just the Champion."""
    data = _pack()
    checked = 0
    for t in data["trainers"].values():
        if not t.get("key"):
            continue
        assert t["level_cap"] == max(p["level"] for p in t["party"])
        checked += 1
    assert checked > 0


def test_trainers_pack_is_lazy_loaded():
    """OMP cx-081c78d3 F8: constructing the adapter (what calc_profile()/a Manager render does)
    must not parse the ~40k-line trainers pack; only a trainer_* call should."""
    _gen3_expansion_mod._load_trainers_pack.cache_clear()
    try:
        a = Gen3ExpansionAdapter(rom_type=ROM_TYPE)
        assert _gen3_expansion_mod._load_trainers_pack.cache_info().currsize == 0
        assert a.calc_profile() is not None
        assert _gen3_expansion_mod._load_trainers_pack.cache_info().currsize == 0
        a.trainer_info(1)
        assert _gen3_expansion_mod._load_trainers_pack.cache_info().currsize == 1
    finally:
        _gen3_expansion_mod._load_trainers_pack.cache_clear()


def test_trainers_pack_source_mismatch_fails_closed(tmp_path, monkeypatch):
    """OMP cx-081c78d3 F7: a trainers pack whose source.commit doesn't match
    data/gen3_exp_sources.lock.json must raise, never serve stale/wrong data quietly."""
    bad = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    bad["source"]["commit"] = "0" * 40
    bad_path = tmp_path / "gen3_exp_trainers.json"
    bad_path.write_text(json.dumps(bad), encoding="utf-8")
    monkeypatch.setattr(_gen3_expansion_mod, "TRAINERS_PACK", bad_path)
    _gen3_expansion_mod._load_trainers_pack.cache_clear()
    try:
        with pytest.raises(ValueError):
            _gen3_expansion_mod._load_trainers_pack()
    finally:
        _gen3_expansion_mod._load_trainers_pack.cache_clear()


# ── OMP cx-c801628e (independent re-review of XC4b's fixes) -- card XC4c ────────────────────

def test_key_trainer_name_collisions_within_an_area_get_distinct_fight_labels():
    """Item 1 (MAJOR): server.py's _trainer_panel_html (~server.py:1020-1041) only folds
    same-name key trainers into ONE Upcoming Key Trainers row (rendered as sub-variants) when
    every trainer in the (area, name, level_cap // 10) bucket has a NON-EMPTY and pairwise
    DISTINCT fight_label; otherwise every trainer gets its own row. Without fight_label at all
    (the bug this card fixes), Brendan/May's starter-variant fights and a gym leader's Vs
    Seeker rematch tiers would never group -- 6 separate "Brendan" rows on route_103 instead of
    one "Brendan" row with 3 starter sub-variants. Reproduces server.py's exact bucketing over
    the shipped pack (not source-gated: this is a property of the generated data, checked
    directly)."""
    data = _pack()
    by_const = {t["const"]: t for t in data["trainers"].values()}
    cap_bucket_size = 10
    buckets: dict[tuple, list[str]] = {}
    for t in data["trainers"].values():
        if not t.get("key") or not t.get("area"):
            continue
        cap_bucket = (t.get("level_cap") or 0) // cap_bucket_size
        buckets.setdefault((t["area"], t["name"].title(), cap_bucket), []).append(t["const"])
    multi = {k: v for k, v in buckets.items() if len(v) > 1}
    assert multi, "expected at least one same-name/same-area/same-level-band key trainer group"
    # The review's own example: route_103/110/119 each carry a 3-way Brendan bucket and a
    # 3-way May bucket (their three starter variants) -- THESE must clear server.py's
    # distinct-nonempty check (fight_label present and unique per variant), or the panel would
    # still show them as 6 separate rows instead of one row with 3 sub-variants. (Not every
    # multi-trainer bucket needs this: e.g. victory_road's WALLY_VR_1/VR_2 land in the same
    # cap_bucket by coincidence but are genuinely different fights, not a starter/rematch
    # group -- WALLY_VR_1 has no fight_label, so server.py correctly falls back to separate
    # rows for that pair instead of merging them.)
    # level_cap differs per route (5 / 20 / 31 -- Brendan/May get stronger as the story
    # advances), so each area lands in its own cap_bucket; look each one up rather than
    # assuming a shared bucket index.
    for area in ("route_103", "route_110", "route_119"):
        for name in ("Brendan", "May"):
            cap = next(t["level_cap"] for t in data["trainers"].values()
                       if t.get("area") == area and t["name"] == name and t.get("key"))
            key = (area, name, cap // cap_bucket_size)
            assert key in multi, (key, sorted(buckets))
            labels = [by_const[c].get("fight_label") or "" for c in multi[key]]
            assert len(multi[key]) == 3, (key, multi[key])
            assert all(labels), (key, multi[key], labels)
            assert len(set(labels)) == len(labels), (key, multi[key], labels)
    wally = [t["fight_label"] for t in data["trainers"].values()
             if t["const"].startswith("TRAINER_WALLY_") and t.get("fight_label")]
    assert any(fl.startswith("Rematch") for fl in wally), wally


def test_grematchtable_area_matches_independently_derived_map_area():
    """Item 2 (MAJOR): literal ground-truth check for four gRematchTable rows, read straight
    from src/battle_setup.c at the pin (not from the generator's own output) and resolved to
    an area through the SAME area_of_map() BFS-fallback the generator uses -- Rustboro City
    and Mauville City are named in area_map.json since EXP-TOWNS (before it the BFS filed them
    under route_104/route_110); Lavaridge Town has an entry since EXP-GIFT-AREAS."""
    src = _need_source()
    keys = map_keys(src)
    all_maps = map_jsons(src)
    grouped_maps = {name: m for name, m in all_maps.items() if m["id"] in keys}
    area_map = json.loads(AREA_MAP.read_text(encoding="utf-8"))
    map_area = area_of_map(grouped_maps, keys, area_map)
    battle_setup = _read(src / "src/battle_setup.c")

    cases = [
        ("REMATCH_ROXANNE", "TRAINER_ROXANNE_", "MAP_RUSTBORO_CITY", "rustboro_city"),
        ("REMATCH_WATTSON", "TRAINER_WATTSON_", "MAP_MAUVILLE_CITY", "mauville_city"),
        ("REMATCH_FLANNERY", "TRAINER_FLANNERY_", "MAP_LAVARIDGE_TOWN", "lavaridge_town"),
        ("REMATCH_TATE_AND_LIZA", "TRAINER_TATE_AND_LIZA_", "MAP_MOSSDEEP_CITY", "mossdeep_city"),
    ]
    data = _pack()
    for rematch_name, const_prefix, expected_map, expected_area in cases:
        m = re.search(rf"\[{rematch_name}\]\s*=\s*REMATCH\(([^)]*)\)", battle_setup)
        assert m, rematch_name
        args = [p.strip() for p in m.group(1).split(",")]
        assert len(args) == 6 and args[-1] == expected_map, (rematch_name, args)
        assert map_area.get(expected_map) == expected_area, (expected_map, map_area.get(expected_map))

        tiers = {t["const"]: t for t in data["trainers"].values()
                  if re.fullmatch(rf"{const_prefix}\d", t["const"])}
        assert len(tiers) == 5, (const_prefix, sorted(tiers))
        for const, t in tiers.items():
            assert t.get("area") == expected_area, (const, t.get("area"))


def test_trainer_party_ivs_macro_param_order_matches_the_generator():
    """Item 3 (MAJOR): the generator's per-mon .iv parse (tools/gen_gen3_exp_trainers.py's
    parse_mons + build()) assumes TRAINER_PARTY_IVS(hp, atk, def, speed, spatk, spdef) --
    SPEED in the 4th slot, not spatk (module docstring). Read the macro definition straight
    from this pin's include/data.h, independent of the generator, and assert the parameter
    order actually matches, so a future pin reordering the macro's arguments fails loudly here
    instead of silently mis-mapping every trainer mon's IVs."""
    src = _need_source()
    text = _read(src / "include/data.h")
    m = re.search(r"#define\s+TRAINER_PARTY_IVS\(([^)]*)\)", text)
    assert m, "TRAINER_PARTY_IVS macro definition not found in include/data.h"
    params = [p.strip() for p in m.group(1).split(",")]
    assert params == ["hp", "atk", "def", "speed", "spatk", "spdef"], params


def test_every_json_pack_mon_carries_explicit_ivs():
    """Item 5 (MINOR): this build's trainers.h always sets an explicit .iv (module docstring,
    verified one .iv per .species in src/data/trainers.h) -- the generator now refuses instead
    of defaulting to a fake all-31 spread (tools/gen_gen3_exp_trainers.py's setdex-building
    loop) when a mon has none, so every party mon shipped in the pack must carry its own
    explicit ivs dict; this asserts the invariant the refusal protects, on the shipped data."""
    data = _pack()
    checked = 0
    for t in data["trainers"].values():
        for mon in t["party"]:
            assert mon.get("ivs"), (t["const"], mon["species"])
            checked += 1
    assert checked > 0


def test_area_map_digest_refuses_on_a_mismatched_source_tree(tmp_path):
    """Item 5 (MINOR): _check_area_map_digest() recomputes tools/gen_area_map.py's
    _expansion_source_sha256 (the same digest gen3_exp_areas.lua's own header records,
    binding it to its map_groups.json/region_map_sections.json/wild_encounters.json inputs)
    and refuses area_map.json when it doesn't match -- a stale area_map.json built from a
    different source tree (a map reordering between expansion versions) must never be used
    quietly. Self-contained: builds a tiny synthetic source tree, no pinned source needed."""
    fake_src = tmp_path / "src"
    (fake_src / "data/maps").mkdir(parents=True)
    (fake_src / "src/data/region_map").mkdir(parents=True)
    (fake_src / "data/maps/map_groups.json").write_text("{}", encoding="utf-8")
    (fake_src / "src/data/region_map/region_map_sections.json").write_text("{}", encoding="utf-8")
    (fake_src / "src/data/wild_encounters.json").write_text("{}", encoding="utf-8")
    area_map = tmp_path / "area_map.json"
    area_map.write_text("{}", encoding="utf-8")
    areas_lua = tmp_path / "gen3_exp_areas.lua"

    areas_lua.write_text(f"-- source_sha256: {'0' * 64}\n", encoding="utf-8")
    with pytest.raises(SystemExit):
        _check_area_map_digest(fake_src, area_map)

    areas_lua.write_text(f"-- source_sha256: {_expansion_source_sha256(fake_src)}\n", encoding="utf-8")
    _check_area_map_digest(fake_src, area_map)  # matching digest: no raise

    areas_lua.unlink()
    with pytest.raises(SystemExit):
        _check_area_map_digest(fake_src, area_map)  # no areas.lua at all: refuse, don't skip


def test_rival_class_is_trainer_class_rival_never_a_pokemon_trainer_macro():
    """Item 6 (reviewer's open question): confirm which TRAINER_CLASS_* Brendan/May/Wally use
    in this build. Verified against the pin: TRAINER_CLASS_RIVAL (displayed "{PKMN} TRAINER"
    via src/battle_main.c's gTrainerClasses, which the adapter's calc_name/pretty() path turns
    into "Pokémon Trainer"); no TRAINER_CLASS_POKEMON_TRAINER macro exists anywhere in this
    pin. KEY_CLASSES must track the real constant, not the display text."""
    src = _need_source()
    trainer_types = _read(src / "include/constants/trainers.h")
    assert "TRAINER_CLASS_RIVAL" in trainer_types
    assert "TRAINER_CLASS_POKEMON_TRAINER" not in trainer_types
    trainers_h = re.sub(r"#line \d+\n\s*", "", _read(src / "src/data/trainers.h"))
    m = re.search(r"\[DIFFICULTY_NORMAL\]\[TRAINER_BRENDAN_ROUTE_103_MUDKIP\]\s*=\s*\{.*?"
                  r"\.trainerClass\s*=\s*TRAINER_CLASS_(\w+),", trainers_h, re.S)
    assert m and m.group(1) == "RIVAL"
    assert "RIVAL" in KEY_CLASSES


def test_unbattled_key_candidates_never_appear_in_any_battle_script():
    """Item 5 (MINOR): TRAINER_RED/TRAINER_LEAF are RIVAL-classed with a real party, so
    KEY_CLASSES alone would flag them key -- but nothing in the pinned source ever fights
    them: not a map trainerbattle/multi-battle script, not a gRematchTable row. Scans the same
    two file sets tools/gen_gen3_trainers.py's trainer_maps() and this generator's
    parse_rematch_groups() read (map scripts.inc/data/scripts *.inc, and battle_setup.c) --
    independent of trusting the generator's own UNBATTLED_KEY_CANDIDATES exclusion."""
    src = _need_source()
    haystack = [_read(src / "src/battle_setup.c")]
    haystack += [_read(p) for p in (src / "data/maps").glob("*/scripts.inc")]
    haystack += [_read(p) for p in (src / "data/scripts").glob("*.inc")]
    text = "\n".join(haystack)
    for const in sorted(UNBATTLED_KEY_CANDIDATES):
        assert not re.search(rf"\b{const}\b", text), const

    data = _pack()
    for const in UNBATTLED_KEY_CANDIDATES:
        t = next(v for v in data["trainers"].values() if v["const"] == const)
        assert not t.get("key"), const


def test_key_trainers_with_no_area_are_reported():
    """TG-MULTI: every key trainer has an area, including the Mossdeep multi-battle pair."""
    data = _pack()
    arealess = sorted(t["const"] for t in data["trainers"].values()
                       if t.get("key") and not t.get("area"))
    print(f"key trainers with no area: {arealess}", file=sys.stderr)
    assert arealess == [], arealess


def test_multi_battle_macro_argument_roles_match_the_pinned_source():
    src = _need_source()
    text = _read(src / "asm/macros/battle_frontier/battle_tower.inc")
    definitions = {name: [arg.strip().split(":")[0] for arg in args.split(",")]
                   for name, args in re.findall(r"^\s*\.macro (multi_\w+) ([^\n]+)", text, re.M)}
    two_opponents = ["trainer1Id", "trainer1LoseText", "trainer2Id", "trainer2LoseText", "partnerId"]
    one_opponent = ["trainer1Id", "trainer1LoseText", "partnerId"]
    assert definitions == {
        "multi_2_vs_2": two_opponents, "multi_fixed_2_vs_2": two_opponents,
        "multi_2_vs_1": one_opponent, "multi_fixed_2_vs_1": one_opponent,
        "multi_wild": ["partnerId"], "multi_fixed_wild": ["partnerId"],
        "multi_do": ["type"], "multi_do_fixed": ["type"],
    }
    event = _read(src / "asm/macros/event.inc")
    low_level = re.search(r"\.macro setmultitrainerbattle ([^\n]+)", event)
    assert low_level
    assert [arg.strip().split(":")[0] for arg in low_level[1].split(",")] == [
        "trainer_a", "lose_text_a", "trainer_b", "lose_text_b", "partnerId"]


def test_space_center_multi_battle_opponents_are_upcoming_in_mossdeep():
    data = _pack()
    for trainer_id, name in ((514, "TRAINER_TABITHA_MOSSDEEP"), (734, "TRAINER_MAXIE_MOSSDEEP")):
        trainer = data["trainers"][str(trainer_id)]
        assert (trainer["const"], trainer["area"], trainer["key"]) == (name, "mossdeep_city", True)
    assert {514, 734} <= set(_adapter().trainers_for_area("mossdeep_city"))
