"""Falsifier for the pokeemerald-expansion trainer sets (card XC4).

Mirrors tests/unit/test_calc_trainer_sets.py's species+level whole-file multiset check: parses
the PINNED expansion source directly (independent of tools/gen_gen3_exp_trainers.py's own
block-based parser -- a flat regex scan is the "ground truth from the decomp, not from a second
copy" this repo's other trainer-set tests already use) and checks it against both generated
outputs: the vendored calc setdex (calc/src/js/data/sets/games/EmeraldExpansion.js) and the
trainer-panel data pack (data/games/gen3_exp/28877d73/gen3_exp_trainers.json).

OMP cx-081c78d3 F3 extended this beyond species+level: held item, nature and IVs are always
explicit in this build (checked full-equality, whole-file multiset, same style as species+level);
explicit .moves are checked too, but only as a SUBSET (a mon with no .moves gets the level-up
learnset default instead, and the JSON pack doesn't record which branch produced its "moves" list,
so a full-multiset equality on moves would conflate the two) -- see
test_explicit_moves_in_source_all_appear_in_the_json_pack and, for the default branch,
test_default_derived_moves_match_a_learnset_sample. Ponytail note: this does not repeat the
full-fidelity comparison a second time for the JS setdex (calc/src/js/...); that file is derived
from the exact same in-process `trainers` dict as the JSON pack in one tools/gen_gen3_exp_trainers.py
run, so a JSON-pack fidelity bug would already be visible here -- add a JS-side copy only if the
two outputs are ever generated by separate passes.

The pinned source (data/gen3_exp_sources.lock.json: tag expansion/1.17.0, commit
e8bd1cd7b03fc032ea37e3ecd38b379b5d01a1e7) lives only on the build host (ssh hgbox, ~/slink-exp)
-- never checked into this repo -- so most runs of this file hit the "source not found" skip.
Point SLINK_EXPANSION_SRC at a local copy (or a `.cache/expansion/<commit>` checkout under the
repo, same walk-up convention as pret) to run the source-comparison tests for real: an absent
source is a named skip, but a PRESENT source at the wrong commit is a hard failure, never a
silent pass -- the whole point of pinning.

The adapter tests at the bottom need no pinned source: they exercise the shipped data pack
directly. Only test_trainer_info_and_party_for_a_gym_leader is a literal (hardcoded) check; the
rest are derived-data oracles (OMP cx-081c78d3 F4 -- the previous trio just re-read the pack and
asserted it against itself, which can't fail when the generator itself is wrong).
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO))

from server.adapters import gen3_expansion as _gen3_expansion_mod  # noqa: E402
from server.adapters.gen3_expansion import ROM_TYPE, Gen3ExpansionAdapter  # noqa: E402
from server.adapters.gen3_frlge import default_moves  # noqa: E402
from tools.gen_gen3_exp_trainers import (  # noqa: E402
    enum_values,
    parse_learnset_tables,
    parse_species_learnset_symbols,
    pretty,
)

_LOCK = json.loads((_REPO / "data/gen3_exp_sources.lock.json").read_text(encoding="utf-8"))
_PIN = _LOCK["source"]["commit"]
_JSON_PACK = _REPO / "data/games/gen3_exp/28877d73/gen3_exp_trainers.json"
_JS_SETDEX = _REPO / "calc/src/js/data/sets/games/EmeraldExpansion.js"
_AREAS_LUA = _REPO / "data/games/gen3_exp/28877d73/gen3_exp_areas.lua"


def _canon(s: str) -> str:
    """Fold a species name down to bare lowercase alnum -- sidesteps SPECIES_MR_MIME vs
    "Mr. Mime" / "Nidoran-F" vs SPECIES_NIDORAN_F without a per-name exceptions table."""
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _find_expansion_src() -> Path | None:
    env = os.environ.get("SLINK_EXPANSION_SRC")
    if env:
        return Path(env)
    d = _REPO
    for _ in range(6):
        cand = d / ".cache" / "expansion" / _PIN
        if cand.is_dir():
            return cand
        parent = d.parent
        if parent == d:
            break
        d = parent
    return None


def _git_head(path: Path) -> str | None:
    r = subprocess.run(["git", "-C", str(path), "rev-parse", "HEAD"], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else None


def _need_source() -> Path:
    src = _find_expansion_src()
    if src is None:
        pytest.skip(f"pokeemerald-expansion checkout not found (set SLINK_EXPANSION_SRC; pin {_PIN})")
    head = _git_head(src)
    assert head == _PIN, f"{src} is at {head}, not the pin {_PIN} (data/gen3_exp_sources.lock.json)"
    return src


def _source_full_records(src: Path) -> list[dict]:
    """Independent (not tools/gen_gen3_exp_trainers.py's block parser) flat scan of every mon in
    src/data/trainers.h: species+level (as before), plus whichever of .heldItem/.nature/.iv/
    .moves appear anywhere in that mon's block before the NEXT mon's .species begins -- the
    window spans from THIS mon's own .species (field order varies per mon: .iv sometimes comes
    before .lvl, sometimes after) up to the next ".species", so a later mon's fields are never
    misattributed to an earlier one and an earlier field is never missed. "moves" is None when
    the source has no explicit .moves for that mon (the level-up-learnset default applies
    instead -- see test_default_derived_moves_match_a_learnset_sample)."""
    text = re.sub(r"#line \d+\n\s*", "", (src / "src/data/trainers.h").read_text(encoding="utf-8"))
    species_ids = enum_values((src / "include/constants/species.h").read_text(encoding="utf-8"), "SPECIES_")
    move_ids = enum_values((src / "include/constants/moves.h").read_text(encoding="utf-8"), "MOVE_")
    item_ids = enum_values((src / "include/constants/items.h").read_text(encoding="utf-8"), "ITEM_")
    adapter = Gen3ExpansionAdapter(rom_type=ROM_TYPE)
    records = []
    for m in re.finditer(r"\.species\s*=\s*(SPECIES_\w+),.{1,300}?\.lvl\s*=\s*(\d+),", text, re.S):
        sid = species_ids.get(m[1])
        if sid is None:
            continue
        window = text[m.start():m.start() + 700]
        nxt = window.find(".species", len(".species"))
        if nxt != -1:
            window = window[:nxt]
        item_m = re.search(r"\.heldItem\s*=\s*(ITEM_\w+)", window)
        item = None
        if item_m and item_m[1] != "ITEM_NONE":
            iid = item_ids.get(item_m[1])
            item = adapter.calc_name("item", adapter.item_name(iid)) if iid else item_m[1]
        nat_m = re.search(r"\.nature\s*=\s*NATURE_(\w+)", window)
        nature = pretty(nat_m[1].replace("_", " ").lower()) if nat_m else None
        iv_m = re.search(r"\.iv\s*=\s*TRAINER_PARTY_IVS\(([^)]*)\)", window)
        ivs = None
        if iv_m:
            parts = [int(x.strip()) for x in iv_m[1].split(",")]
            if len(parts) == 6:
                hp, atk, df, spe, spa, spd = parts
                ivs = (("atk", atk), ("def", df), ("hp", hp), ("spa", spa), ("spd", spd), ("spe", spe))
        mv_m = re.search(r"\.moves\s*=\s*\{([^}]*)\}", window)
        moves = None
        if mv_m:
            macros = [mm.strip() for mm in mv_m[1].split(",") if mm.strip() and mm.strip() != "MOVE_NONE"]
            moves = tuple(adapter.calc_name("move", adapter.move_name(move_ids[mo])) if mo in move_ids else mo
                          for mo in macros)
        records.append({
            "species": _canon(adapter.calc_species(sid)), "level": int(m[2]),
            "item": item, "nature": nature, "ivs": ivs, "moves": moves,
        })
    return records


def _source_species_level_multiset(src: Path) -> Counter:
    return Counter((r["species"], r["level"]) for r in _source_full_records(src))


def _source_full_multiset(src: Path) -> Counter:
    """species+level+item+nature+ivs -- all always explicit or always None-if-absent in this
    build, so this is a full-equality multiset (unlike moves, see the module docstring)."""
    return Counter((r["species"], r["level"], r["item"], r["nature"], r["ivs"]) for r in _source_full_records(src))


def _source_explicit_moves_multiset(src: Path) -> Counter:
    return Counter((r["species"], r["level"], r["item"], r["nature"], r["ivs"], r["moves"])
                   for r in _source_full_records(src) if r["moves"] is not None)


def _json_pack_multiset() -> Counter:
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    c: Counter = Counter()
    for t in data["trainers"].values():
        for mon in t["party"]:
            c[(_canon(mon["species"]), mon["level"])] += 1
    return c


def _json_pack_mon_key(mon: dict) -> tuple:
    ivs = mon.get("ivs")
    ivs_t = tuple(sorted(ivs.items())) if ivs else None
    return (_canon(mon["species"]), mon["level"], mon.get("item"), mon.get("nature"), ivs_t)


def _json_pack_full_multiset() -> Counter:
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    return Counter(_json_pack_mon_key(mon) for t in data["trainers"].values() for mon in t["party"])


def _json_pack_moves_multiset() -> Counter:
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    c: Counter = Counter()
    for t in data["trainers"].values():
        for mon in t["party"]:
            moves = mon.get("moves")
            c[_json_pack_mon_key(mon) + (tuple(moves) if moves else None,)] += 1
    return c


def _js_setdex_dict() -> dict:
    text = _JS_SETDEX.read_text(encoding="utf-8")
    lines = [ln for ln in text.splitlines() if not ln.strip().startswith("//")]
    text = "\n".join(lines).strip()
    assert text.startswith("var "), _JS_SETDEX
    body = text[text.index("=") + 1:].strip().rstrip(";")
    return json.loads(body)


def _js_setdex_multiset() -> Counter:
    dex = _js_setdex_dict()
    c: Counter = Counter()
    for species, sets in dex.items():
        for entry in sets.values():
            c[(_canon(species), entry["level"])] += 1
    return c


def test_json_pack_identity_matches_lock_pin():
    data = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    assert data["source"]["commit"] == _PIN


def test_gen3_exp_trainers_json_matches_pinned_source():
    src = _need_source()
    assert _json_pack_multiset() == _source_species_level_multiset(src)


def test_emerald_expansion_js_matches_pinned_source():
    src = _need_source()
    assert _js_setdex_multiset() == _source_species_level_multiset(src)


def test_gen3_exp_trainers_json_full_fidelity_matches_pinned_source():
    """species+level+item+nature+ivs, whole-file, full equality (OMP cx-081c78d3 F3)."""
    src = _need_source()
    assert _json_pack_full_multiset() == _source_full_multiset(src)


def test_explicit_moves_in_source_all_appear_in_the_json_pack():
    """Every mon whose .moves the source spells out explicitly must appear -- species, level,
    item, nature, ivs AND that exact move list -- in the JSON pack at least as many times as the
    source has it. A subset check, not full-multiset equality: the pack also carries
    level-up-learnset-derived move lists (no explicit .moves in source) mixed into the same
    "moves" field, and nothing in the pack says which branch produced any one entry."""
    src = _need_source()
    explicit = _source_explicit_moves_multiset(src)
    pack = _json_pack_moves_multiset()
    missing = explicit - pack
    assert not missing, dict(missing)


def test_default_derived_moves_match_a_learnset_sample():
    """A sample of mons the source gives NO .moves for (GiveBoxMonInitialMoveset's level-up
    learnset default applies instead): recompute the expected move list independently
    (server.adapters.gen3_frlge.default_moves() over the same learnset tables, not
    tools/gen_gen3_exp_trainers.py's own default_moveset() closure) and confirm the JSON pack
    has a matching entry for each sampled (species, level)."""
    src = _need_source()
    text = re.sub(r"#line \d+\n\s*", "", (src / "src/data/trainers.h").read_text(encoding="utf-8"))
    species_ids = enum_values((src / "include/constants/species.h").read_text(encoding="utf-8"), "SPECIES_")
    move_ids = enum_values((src / "include/constants/moves.h").read_text(encoding="utf-8"), "MOVE_")
    sp_learnset_sym = parse_species_learnset_symbols(src)
    learnset_tables = parse_learnset_tables(src)
    adapter = Gen3ExpansionAdapter(rom_type=ROM_TYPE)

    sample: list[tuple[str, int]] = []
    for m in re.finditer(r"\.species\s*=\s*(SPECIES_\w+),.{1,300}?\.lvl\s*=\s*(\d+),", text, re.S):
        window = text[m.start():m.start() + 700]
        nxt = window.find(".species", len(".species"))
        if nxt != -1:
            window = window[:nxt]
        if re.search(r"\.moves\s*=", window) or m[1] not in sp_learnset_sym:
            continue
        sample.append((m[1], int(m[2])))
        if len(sample) >= 25:
            break
    assert sample, "expected at least one default-moveset mon with a known learnset in this build"

    pack_moves: dict[tuple[str, int], set] = {}
    for t in json.loads(_JSON_PACK.read_text(encoding="utf-8"))["trainers"].values():
        for mon in t["party"]:
            key = (_canon(mon["species"]), mon["level"])
            pack_moves.setdefault(key, set()).add(tuple(mon.get("moves") or ()))

    for sp_macro, level in sample:
        sym = sp_learnset_sym[sp_macro]
        expected_macros = default_moves(learnset_tables.get(sym, []), level)
        expected = tuple(adapter.calc_name("move", adapter.move_name(move_ids[mv])) for mv in expected_macros)
        key = (_canon(adapter.calc_species(species_ids[sp_macro])), level)
        assert expected in pack_moves.get(key, set()), (sp_macro, level, expected, pack_moves.get(key))


def test_generator_check_passes_against_a_regenerated_copy():
    """OMP cx-081c78d3 F11: `--check` actually runs (and passes) when the pinned source is
    present, instead of only ever being exercised by hand."""
    src = _need_source()
    r = subprocess.run([sys.executable, str(_REPO / "tools/gen_gen3_exp_trainers.py"),
                         "--src", str(src), "--check"], capture_output=True, text=True)
    assert r.returncode == 0, r.stdout + r.stderr


# --------------------------------------------------------------------------------------
# Adapter tests -- no pinned source needed, exercise the shipped data pack directly.
# --------------------------------------------------------------------------------------

def _adapter() -> Gen3ExpansionAdapter:
    return Gen3ExpansionAdapter(rom_type=ROM_TYPE)


def _pack() -> dict:
    return json.loads(_JSON_PACK.read_text(encoding="utf-8"))


def test_trainer_info_and_party_for_a_gym_leader():
    a = _adapter()
    data = _pack()
    tid, roxanne = next((int(k), v) for k, v in data["trainers"].items() if v["const"] == "TRAINER_ROXANNE_1")
    assert a.trainer_info(tid) == ("Roxanne", "Leader")
    party = a.trainer_party(tid)
    assert party == roxanne["party"]
    assert [p["species"] for p in party] == ["Geodude", "Geodude", "Nosepass"]


def test_no_base_name_maps_to_more_than_one_trainer_index():
    """OMP cx-081c78d3 F1 falsifier: the Prep tab groups a vendored setdex key by the text
    before " | " (calc/src/js/slink_bridge.js's _buildTrainerIndex); if two different trainer
    ids ever produced the same base text, their parties would silently merge into one fake
    combined encounter (this is exactly what happened before compute_bases() -- a rematch
    tier's discriminator sat after the pipe, an opaque uniqueness key the Prep tab never reads
    for grouping)."""
    dex = _js_setdex_dict()
    base_to_indexes: dict[str, set] = {}
    for sets in dex.values():
        for key, entry in sets.items():
            pipe = key.find(" | ")
            base = key[:pipe].strip() if pipe != -1 else key
            base_to_indexes.setdefault(base, set()).add(entry["index"])
    collisions = {b: idx for b, idx in base_to_indexes.items() if len(idx) > 1}
    assert not collisions


def test_trainers_by_area_keys_are_client_emittable_areas():
    """Derived-data oracle (OMP cx-081c78d3 F3/F4): every area gen3_exp_trainers.json groups key
    trainers under must be an area id the Lua client can actually emit
    (data/games/gen3_exp/28877d73/gen3_exp_areas.lua's values), never a made-up or stale one."""
    data = _pack()
    lua_text = _AREAS_LUA.read_text(encoding="utf-8")
    valid_areas = set(re.findall(r'=\s*"([^"]+)"', lua_text))
    assert data["trainers_by_area"], "expected at least one area with key trainers"
    for area in data["trainers_by_area"]:
        assert area in valid_areas, area


def test_every_key_trainers_by_area_entry_is_flagged_key_and_matches_its_area():
    """Replaces the old mirror test (asserted the pack against itself): cross-checks
    trainers_by_area against the per-trainer records it was built from, and against the live
    adapter, independently of trusting either side alone."""
    a = _adapter()
    data = _pack()
    for area, tids in data["trainers_by_area"].items():
        assert tids, area
        for tid in tids:
            t = data["trainers"][str(tid)]
            assert t.get("key") is True
            assert t.get("area") == area
        assert sorted(a.trainers_for_area(area)) == sorted(tids)


def test_every_key_trainer_level_cap_equals_max_party_level():
    """Derived-data oracle (OMP cx-081c78d3 F3): level_cap is documented as "the trainer's own
    highest party level" -- prove it, for every key trainer, not just the Champion."""
    data = _pack()
    checked = 0
    for t in data["trainers"].values():
        if not t.get("key"):
            continue
        assert t["level_cap"] == max(p["level"] for p in t["party"])
        checked += 1
    assert checked > 0


def test_trainers_pack_is_lazy_loaded():
    """OMP cx-081c78d3 F8: constructing the adapter (what calc_profile()/a Manager render does)
    must not parse the ~40k-line trainers pack; only a trainer_* call should."""
    _gen3_expansion_mod._load_trainers_pack.cache_clear()
    try:
        a = Gen3ExpansionAdapter(rom_type=ROM_TYPE)
        assert _gen3_expansion_mod._load_trainers_pack.cache_info().currsize == 0
        assert a.calc_profile() is not None
        assert _gen3_expansion_mod._load_trainers_pack.cache_info().currsize == 0
        a.trainer_info(1)
        assert _gen3_expansion_mod._load_trainers_pack.cache_info().currsize == 1
    finally:
        _gen3_expansion_mod._load_trainers_pack.cache_clear()


def test_trainers_pack_source_mismatch_fails_closed(tmp_path, monkeypatch):
    """OMP cx-081c78d3 F7: a trainers pack whose source.commit doesn't match
    data/gen3_exp_sources.lock.json must raise, never serve stale/wrong data quietly."""
    bad = json.loads(_JSON_PACK.read_text(encoding="utf-8"))
    bad["source"]["commit"] = "0" * 40
    bad_path = tmp_path / "gen3_exp_trainers.json"
    bad_path.write_text(json.dumps(bad), encoding="utf-8")
    monkeypatch.setattr(_gen3_expansion_mod, "TRAINERS_PACK", bad_path)
    _gen3_expansion_mod._load_trainers_pack.cache_clear()
    try:
        with pytest.raises(ValueError):
            _gen3_expansion_mod._load_trainers_pack()
    finally:
        _gen3_expansion_mod._load_trainers_pack.cache_clear()
