"""lua/nds/pkm45_crypto.lua == tools/nds_pkm45.py (independent oracle) == the Gen 4 codec == the cartridge.

Vector sources, strongest last: (1) synthetic pseudo-random records generated by the Python oracle and
checked by the Lua module, both party lengths, all 32 shuffle rows; (2) one REAL 0xEC party record each from
the owner's HG, SS and hg-engine (hge) battery saves, pinned in this file (no save or worktree needed to run
them); (3) the Gen 4 vectors (synthetic build_plain records and the real battery saves) via the Gen 4
worktree's independent decoder; (4) the BW/B2W2 cartridges' own 128-byte block-offset table and the LCRNG
literal in the decompressed ARM9; (5) a hand-computed stored-layout pin (Lua only) that fixes the shuffle
DIRECTION with none of the optional inputs present.

Absent inputs skip BY NAME (tests/TESTING.md: absent skips, wrong fails). Control tests prove every
comparison can fail: a mutated copy of the Lua module must NOT match the oracle.
"""

from __future__ import annotations

import hashlib
import importlib.util
import os
import random
import re
import struct
import sys
from pathlib import Path

import lupa
import pytest

from tools import nds_pkm45 as oracle

ROOT = Path(__file__).resolve().parents[2]
MODULE = ROOT / "lua/nds/pkm45_crypto.lua"
GEN4, GEN5 = oracle.PARTY_LEN_GEN4, oracle.PARTY_LEN_GEN5
GEN4_WT = Path(
    os.environ.get("SLINK_GEN4_WT")
    or "E:/Google Drive/SLink/.claude/worktrees/gen4-support-framework-dfd5e2"
)
ROM_DIR = Path(os.environ.get("SLINK_NDS_ROMS") or "E:/Google Drive/SLink")
SAVE_DIR = Path("E:/Howard/Bizhawk/NDS/SaveRAM")

# name -> (ROM file, RAM address of the game's 128-byte block-offset table); FILE: rom_code_anchors.md 1.2
ROMS = {
    "black": ("Pokemon - Black Version (USA, Europe) (NDSi Enhanced).nds", 0x0209E3A4),
    "white": ("Pokemon - White Version (USA, Europe) (NDSi Enhanced).nds", 0x0209E3BC),
    "black2": ("Pokemon - Black Version 2 (USA, Europe) (NDSi Enhanced).nds", 0x02090474),
    "white2": ("Pokemon - White Version 2 (USA, Europe) (NDSi Enhanced).nds", 0x020904A0),
}
ARM9_RAM_BASE = 0x02004000


def load_lua(source: str | None = None):
    lua = lupa.LuaRuntime()
    src = source if source is not None else MODULE.read_text(encoding="utf-8")
    return lua, lua.eval("function(s) return assert(load(s, '=pkm45'))() end")(src)


def py(v):
    """Lua table -> list (array) or dict; scalars unchanged."""
    if lupa.lua_type(v) != "table":
        return v
    keys = sorted(v.keys(), key=lambda k: (not isinstance(k, int), k if isinstance(k, int) else 0))
    if keys and keys == list(range(1, len(keys) + 1)):
        return [py(v[k]) for k in keys]
    return {k: py(v[k]) for k in keys}


@pytest.fixture(scope="module")
def rt():
    return load_lua()


@pytest.fixture(scope="module")
def mod(rt):
    return rt[1]


def lua_bytes(v) -> bytes:
    return bytes(py(v))


def random_plain(rng: random.Random, party_len: int, pid: int | None = None, flags: int = 0) -> bytes:
    p = bytearray(rng.randbytes(party_len))
    if pid is not None:
        struct.pack_into("<I", p, 0, pid)
    struct.pack_into("<H", p, 4, flags)  # default 0; bits 0-1 clear = the encrypted representation
    return bytes(p)


def opts(rt, **kw):
    return rt[0].table_from(kw)


def same_but_checksum(a: bytes, b: bytes) -> bool:
    return a[:6] == b[:6] and a[8:] == b[8:]  # encryption recomputes the checksum header word


# -- the shuffle table -----------------------------------------------------------------------------
def test_block_order_matches_the_oracle_for_every_row(mod):
    for row in range(32):
        pid = (0xABCD_0001 & ~0x3E000) | (row << 13)
        assert py(mod.block_order(pid)) == list(oracle.block_order(pid))
        assert mod.shuffle_row(pid) == row == oracle.shuffle_row(pid)
    assert bytes(b for r in range(32) for b in py(mod.block_order(r << 13))) == oracle.GAME_TABLE


# -- synthetic vectors: oracle generates, Lua checks ----------------------------------------------------
@pytest.mark.parametrize("party_len", [GEN4, GEN5])
def test_pseudo_random_records_agree_and_round_trip(mod, party_len):
    rng = random.Random(0x5EED_0000 + party_len)
    for n in range(256):
        pid = rng.getrandbits(32) if n >= 32 else (rng.getrandbits(32) & ~0x3E000) | (n << 13)
        flags = 4 if n % 5 == 0 else 0  # bit 2 = bad egg, a legitimate stored state
        plain = random_plain(rng, party_len, pid, flags)
        stored = oracle.encrypt_party(plain, party_len)
        assert struct.unpack_from("<H", stored, 4)[0] == flags  # encrypt preserves bit 2
        # Lua decrypt == oracle decrypt, header included
        want, info = oracle.decrypt_party(stored, party_len)
        assert same_but_checksum(want, plain)
        got, linfo = mod.decrypt_party(stored, party_len)
        assert lua_bytes(got) == want
        assert linfo.bad_egg == info["bad_egg"] == bool(flags) and linfo.decrypted is False and linfo.checksum_ok is True
        assert linfo.pid == info["pid"] == pid and linfo.row == info["row"] and linfo.checksum == info["checksum"]
        assert py(linfo.order) == info["order"]
        # Lua encrypt == oracle encrypt (checksum recomputed identically), and the round trip is exact
        assert lua_bytes(mod.encrypt_party(want, party_len)) == stored
        assert lua_bytes(mod.encrypt_party(got, party_len)) == stored
        # the 0x88 stored forms (a box record) agree too
        box = oracle.encrypt_stored(plain[:0x88])
        assert box == stored[:0x88]
        bgot, _ = mod.decrypt_stored(box)
        assert lua_bytes(bgot) == oracle.decrypt_stored(box)[0] == want[:0x88]
        assert lua_bytes(mod.encrypt_stored(bgot)) == box
        # strings and 1-based arrays are interchangeable inputs; outputs are fresh arrays


def test_arrays_and_strings_are_interchangeable_inputs_and_outputs_are_fresh(rt, mod):
    lua, _ = rt
    stored = oracle.encrypt_party(random_plain(random.Random(5), GEN5, 0x0001_2345), GEN5)
    arr = lua.table_from(list(stored))
    got, _ = mod.decrypt_party(arr, GEN5)
    assert lua_bytes(got) == oracle.decrypt_party(stored, GEN5)[0]
    assert list(py(arr)) == list(stored)  # the caller's array is never mutated


def test_stored_checksum_is_the_u16_sum_and_the_seed(rt, mod):
    rng = random.Random(7)
    plain = random_plain(rng, 0x88, 0x1234_5678)
    stored = oracle.encrypt_stored(plain)
    body_logical = plain[8:]
    assert oracle.checksum(body_logical) == struct.unpack_from("<H", stored, 6)[0] == mod.checksum(body_logical)
    assert mod.checksum(rt[0].table_from(list(body_logical))) == oracle.checksum(body_logical)



def test_odd_length_checksum_is_refused_identically_in_lua_and_python(mod):
    assert R(mod.checksum(b"\0" * 3)) == (None, "size")
    with pytest.raises(oracle.PkmError) as e:
        oracle.checksum(b"\0" * 3)
    assert e.value.reason == "size"
    assert mod.checksum(b"\x01\x00\x02\x00") == oracle.checksum(b"\x01\x00\x02\x00") == 3


# -- flags word: bad egg (bit 2) and the game's own "decrypted" marker (bits 0-1) --------------------------------
def R(v):
    """A Lua multi-return as a tuple (lupa gives a bare value for a single return)."""
    return v if isinstance(v, tuple) else (v,)


def make_decrypted(stored: bytes, party_len: int, bits: int = 3) -> bytes:
    """What the game's Decrypt() leaves in RAM: body+tail XOR-plain, blocks still SHUFFLED, flags bits 0-1 set
    (docs/gen5/research/rom_code_anchors.md:66,214). Built from the oracle's logical plain + its block order."""
    plain, info = oracle.decrypt_party(stored, party_len)
    body = bytearray(0x80)
    for which, o in enumerate(oracle.block_order(info["pid"])):
        body[o : o + 0x20] = plain[8 + which * 0x20 : 8 + (which + 1) * 0x20]
    flags = info["flags"] | bits
    return plain[:4] + struct.pack("<H", flags) + plain[6:8] + bytes(body) + plain[0x88:]


@pytest.mark.parametrize("party_len", [GEN4, GEN5])
def test_bad_egg_is_reported_preserved_and_never_an_error(mod, party_len):
    plain = random_plain(random.Random(21), party_len, 0x0001_4321, flags=0x0004)
    stored = oracle.encrypt_party(plain, party_len)
    got, info = mod.decrypt_party(stored, party_len)
    assert info.bad_egg is True and info.decrypted is False and info.flags == 4
    assert lua_bytes(got) == oracle.decrypt_party(stored, party_len)[0]
    assert oracle.decrypt_party(stored, party_len)[1]["bad_egg"] is True
    assert struct.unpack_from("<H", lua_bytes(mod.encrypt_party(got, party_len)), 4)[0] == 4  # never repaired
    clean, cinfo = mod.decrypt_party(oracle.encrypt_party(random_plain(random.Random(22), party_len, 5), party_len), party_len)
    assert cinfo.bad_egg is False
    # bad egg + decrypted marker: the refusal is "locked", not "checksum"
    dec = make_decrypted(stored, party_len)
    assert struct.unpack_from("<H", dec, 4)[0] == 7
    assert R(mod.decrypt_party(dec, party_len)) == (None, "locked")


@pytest.mark.parametrize("bits", [1, 2, 3])
@pytest.mark.parametrize("party_len", [GEN4, GEN5])
def test_decrypted_marker_is_refused_by_default_and_opt_in_decodes(rt, mod, party_len, bits):
    plain = random_plain(random.Random(31 + bits), party_len, (7 << 13) | 0x55)
    stored = oracle.encrypt_party(plain, party_len)
    want, winfo = oracle.decrypt_party(stored, party_len)
    dec = make_decrypted(stored, party_len, bits)
    assert R(mod.decrypt_party(dec, party_len)) == (None, "locked")
    assert R(mod.decrypt_stored(dec[:0x88])) == (None, "locked")
    assert R(mod.decrypt_party(dec, party_len, opts(rt, allow_decrypted=False))) == (None, "locked")
    with pytest.raises(oracle.PkmError) as e:
        oracle.decrypt_party(dec, party_len)
    assert e.value.reason == "locked"
    got, info = mod.decrypt_party(dec, party_len, opts(rt, allow_decrypted=True))
    ogot, oinfo = oracle.decrypt_party(dec, party_len, allow_decrypted=True)
    assert lua_bytes(got) == ogot == want[:4] + struct.pack("<H", bits) + want[6:]  # logical blocks, plain tail
    assert info.decrypted is True and info.checksum_ok is True and oinfo["decrypted"] is True
    assert info.flags == oinfo["flags"] == bits and py(info.order) == oinfo["order"] == winfo["order"]
    # box form too
    bgot, _ = mod.decrypt_stored(dec[:0x88], opts(rt, allow_decrypted=True))
    assert lua_bytes(bgot) == ogot[:0x88]
    # encrypt always clears bits 0-1, and the result decrypts back by default
    again = lua_bytes(mod.encrypt_party(got, party_len))
    assert struct.unpack_from("<H", again, 4)[0] & 0x3 == 0 and again == stored
    assert oracle.encrypt_party(ogot, party_len) == stored
    assert lua_bytes(mod.decrypt_party(again, party_len)[0]) == want
    assert struct.unpack_from("<H", lua_bytes(mod.encrypt_stored(bgot)), 4)[0] & 0x3 == 0


def test_decrypted_mode_reports_a_stale_checksum_instead_of_enforcing_it(rt, mod):
    stored = oracle.encrypt_party(random_plain(random.Random(41), GEN4, 0x0002_0099), GEN4)
    dec = bytearray(make_decrypted(stored, GEN4))
    dec[0x20] ^= 0xFF  # the game edited a field; the checksum is only recomputed by Encrypt()
    got, info = mod.decrypt_party(bytes(dec), GEN4, opts(rt, allow_decrypted=True))
    assert got is not None and info.checksum_ok is False
    ogot, oinfo = oracle.decrypt_party(bytes(dec), GEN4, allow_decrypted=True)
    assert lua_bytes(got) == ogot and oinfo["checksum_ok"] is False


# -- hand-computed stored layout (Lua only): pins the shuffle DIRECTION with no optional input present ------------
def lcg_local(data: bytes, seed: int) -> bytes:
    out = bytearray()
    for i in range(0, len(data), 2):
        seed = (seed * 0x41C64E6D + 0x6073) & 0xFFFFFFFF
        out += struct.pack("<H", struct.unpack_from("<H", data, i)[0] ^ (seed >> 16))
    return bytes(out)


# Read off the cartridge table indexed sv*4 + logical block (bytes at sv*4: 3 -> 00 60 20 40,
# 12 -> 20 40 00 60, 17 -> 60 40 00 20): the stored sequence of logical blocks, slot 0 first. All three are
# non-involutions, so a flipped direction cannot pass.
STORED_SEQUENCE = {3: "ACDB", 12: "CABD", 17: "CDBA"}
FILL = {"A": 0xA1, "B": 0xB2, "C": 0xC3, "D": 0xD4}


@pytest.mark.parametrize("row", sorted(STORED_SEQUENCE))
def test_shuffle_direction_pinned_without_any_optional_input(mod, row):
    pid = (row << 13) | 0x123
    seq = STORED_SEQUENCE[row]
    header = struct.pack("<IHH", pid, 0, 0)
    logical = b"".join(bytes([FILL[c]]) * 0x20 for c in "ABCD")
    # encrypt: strip the cipher by hand and read the stored order
    stored = lua_bytes(mod.encrypt_stored(header + logical))
    body = lcg_local(stored[8:], struct.unpack_from("<H", stored, 6)[0])
    assert "".join({v: k for k, v in FILL.items()}[body[s * 0x20]] for s in range(4)) == seq
    # decrypt: hand-build the stored record from the layout, expect logical A,B,C,D back
    hand = b"".join(bytes([FILL[c]]) * 0x20 for c in seq)
    csum = sum(struct.unpack("<64H", hand)) & 0xFFFF
    rec = struct.pack("<IHH", pid, 0, csum) + lcg_local(hand, csum)
    got, info = mod.decrypt_stored(rec)
    assert lua_bytes(got)[8:] == logical and info.row == row


# -- real party records, one per game (HG, SS, hge); pinned so they run with no save or worktree -------------------
# Derived read-only on 2026-10-02 from the owner's battery saves with the Gen 4 worktree codec
# (server/adapters/gen4_codec.py): party slot 0 of Pokemon - HeartGold / SoulSilver (USA).SaveRAM and of
# hg-engine.SaveRAM (the hge populated record, party count 1). Each is a 0xEC encrypted record: PID-seeded LCG
# tail 0x88..0xEC. expect = (species, level, tid, sid, sha256 of the Gen 4 codec's plain decrypt).
REAL_PARTY = {
    "hg": {
        "raw": (
        "42bbedeb00008fee9f1bdfcc30ff44307de1b516192c58c835e3c6dd64482b31808ffd7c00b2d46e7e080e1e60aa9e42"
        "1b94fa8202a19b29c2fd8b3d5c8e590bc87de80480d5f7b247ec74cdc3b015b90103c8916ce860aa971b7919efa67550"
        "4e6febeb3f7fe278864fcfc96b6e532e0db74d7f1b78a865e345022ab1216e79edd63a5c3e8f2006537a69344026f88b"
        "00fd6a7ac31995edb9a16b9587aa8964340a4ded4847fc3b1e648632f6f1f8b90dd8a9e4905c6d2176fc41d7ca8f207f"
        "1ef74b83aae9720e3a345751f7ff7d18ba3cc92ea0c2117ba75a819994da99919c1dd4b7dc14a3a6b3730600"
        ),
        "pid": 0xebedbb42, "tid": 26310, "sid": 29888,
        "sha": "30fd492786706606f2ec4f5ff2f63b0289e03c2ddecca3229dde0f7adbf2c74b",
    },
    "ss": {
        "raw": (
        "0f2866240000df2ee8ecd8addfd617b595cbbf0615791659452adf5138ee056a7e67de9da9bf8ce1a732370e1e4a8731"
        "8742ae80a1c933cc8ade728c0d784daad8146aa9085af8a101eaab5f9f07fab71ec6738ed1e0c9640c057c1bff1c0a28"
        "c86f9c2534ba70fd48969a5097f064c495ffae0625ec56fa4fbbd7eadfb5673ae094e621ee42be974e6afb026c23a62c"
        "59eca6cbd7e4d7cb6bd13a4fa158d39c7e1cc4649c9c455e25cf052615ea2a69c5658f32f61274618982507145d4c49a"
        "c9d065dc794c77c703e11decd5006d6a98b3bc167723b6acb6cc93d379fa3cf08a24d77bdbdc1738ef79f987"
        ),
        "pid": 0x2466280f, "tid": 25944, "sid": 16585,
        "sha": "74a1b0c69ae4548292289a96dc8f90b5c5e111bfa266090f87cf317e896a7163",
    },
    "hge": {
        "raw": (
        "e6ebdcee0000651d3e6a081f6d42a5d631d4b26e36f6ab8cf44190d1654b6d93e79f9472b56021a74b1a8cc626bd967e"
        "0c06afdcd173912e4908a3d2224241facaf2d23c05a7aa3e7eacb8ec6c1c402c92a42119ea7885907a2ae5716fedc22a"
        "c96c94e071c1f07f4cc3a6896d58be78d91c9c47aee47c03953fed914668f4b503fce6ab89e99354d4dd8f5b2ba1d302"
        "f1188b9725136a43d5e72669f1771c9edba721532c0f3e20dbd551926568470e066a5f0a7b40785827f2907961cc98e0"
        "122ed021adf93e0235960bd5bc39140da828066c5d2cf9d70705223e2697e0214ce383215ae7cb9d4ce903ae"
        ),
        "pid": 0xeedcebe6, "tid": 630, "sid": 62679,
        "sha": "412430200f94550dab60ece1c457f33fe0dc9d24dc2229cee025276067865ed2",
    },
}


@pytest.mark.parametrize("game", sorted(REAL_PARTY))
def test_real_party_vectors_pinned(mod, game):
    v = REAL_PARTY[game]
    raw = bytes.fromhex(v["raw"])
    assert len(raw) == GEN4
    plain, info = oracle.decrypt_party(raw, GEN4)
    got, linfo = mod.decrypt_party(raw, GEN4)
    assert lua_bytes(got) == plain and hashlib.sha256(plain).hexdigest() == v["sha"]
    assert (mod.pid(got), mod.tid(got), mod.sid(got)) == (v["pid"], v["tid"], v["sid"]) == (
        oracle.pid(plain), oracle.tid(plain), oracle.sid(plain))
    assert linfo.bad_egg is False and linfo.decrypted is False and info["decrypted"] is False
    assert 1 <= plain[0x8C] <= 100, "party tail level byte is implausible: the PID-seeded tail decode is wrong"
    assert raw[0x88:] != plain[0x88:]  # the tail really is enciphered in the stored record
    assert oracle.encrypt_party(plain, GEN4) == raw == lua_bytes(mod.encrypt_party(got, GEN4))
    # the Gen 5 length cuts the same PID-keyed stream: a 0xDC view of the first 0xDC bytes agrees (positional XOR)
    p5, _ = oracle.decrypt_party(raw[:GEN5], GEN5)
    assert p5 == plain[:GEN5] and lua_bytes(mod.decrypt_party(raw[:GEN5], GEN5)[0]) == p5


# Pinned from the oracle; the 0xEC form was cross-checked against the Gen 4 codec when generated. The PID-keyed
# tail stream is positional, so the Gen 5 (0xDC) record is the 0xEC one cut to length.
GOLDEN_GEN4 = (
    "efbeadde000000e0648693209849facc449787e7260e45ef35bb9d416e746508fbfa22b732816d69363b05174b3f5146"
    "93e76bb656972828946dd26931595c45df7d069cb9b3177b8790cb55c038b3dfbc5b4c55d17588296b884bf074b89425"
    "8e1f907d7fb0bc7001640d1d83d1532a11e08b9d92c9a694a5869a31116d721f0a53b96cc28b88e2bade1264e4c86834"
    "580e1390838cfbaeb7dd5ea97efe24e318a9e5adf81d88520c46dfbdff9fb719ff8de1ed5c5a70a1ee73680dafc1b9aa"
    "e1ae98c62806fe8d01d5f17455a52be2b10c9929ef3c9d6f3b2824fee3ff89a31925ba2361901eff38b1ce9c"
)
GOLDEN = {GEN4: GOLDEN_GEN4, GEN5: GOLDEN_GEN4[: GEN5 * 2]}


def test_golden_vectors_pinned(mod):
    for party_len, want_hex in GOLDEN.items():
        plain = bytes((i * 7 + 3) & 0xFF for i in range(party_len))
        plain = struct.pack("<IHH", 0xDEAD_BEEF, 0, 0) + plain[8:]
        assert oracle.encrypt_party(plain, party_len).hex() == want_hex
        assert lua_bytes(mod.encrypt_party(plain, party_len)).hex() == want_hex
        got = lua_bytes(mod.decrypt_party(bytes.fromhex(want_hex), party_len)[0])
        assert same_but_checksum(got, plain) and got[6:8] == bytes.fromhex(want_hex)[6:8]




# -- identity accessors -----------------------------------------------------------------------------
def test_identity_accessors_read_the_logical_block_a_words(rt, mod):
    p = bytearray(0xDC)
    struct.pack_into("<I", p, 0, 0xDEAD_BEEF)
    struct.pack_into("<HH", p, 0x0C, 0x1234, 0xABCD)
    plain = bytes(p)
    assert (mod.pid(plain), mod.tid(plain), mod.sid(plain), mod.otid(plain)) == (
        0xDEADBEEF, 0x1234, 0xABCD, 0xABCD_1234)
    assert (oracle.pid(plain), oracle.tid(plain), oracle.sid(plain), oracle.otid(plain)) == (
        0xDEADBEEF, 0x1234, 0xABCD, 0xABCD_1234)
    assert mod.mon_key(plain) == oracle.mon_key(plain) == "DEADBEEF:ABCD1234"
    assert tuple(mod.tid(b"\0" * 8)) == (None, "size")
    arr = rt[0].table_from(list(plain))  # a dense array works as well as a string, with no copy of the record
    assert (mod.pid(arr), mod.tid(arr), mod.sid(arr), mod.otid(arr), mod.mon_key(arr)) == (
        0xDEADBEEF, 0x1234, 0xABCD, 0xABCD_1234, "DEADBEEF:ABCD1234")
    # through the cipher: the identity survives encrypt -> decrypt in every shuffle row
    for row in range(32):
        q = bytearray(plain)
        struct.pack_into("<I", q, 0, (0xDEAD_BEEF & ~0x3E000) | (row << 13))
        dec, _ = mod.decrypt_party(oracle.encrypt_party(bytes(q), 0xDC), 0xDC)
        assert (mod.tid(dec), mod.sid(dec), mod.otid(dec)) == (0x1234, 0xABCD, 0xABCD_1234)


# -- negatives ---------------------------------------------------------------------------------------
def test_refusals(mod):
    good = oracle.encrypt_party(random_plain(random.Random(1), GEN5, 0xDEAD_BEEF), GEN5)
    assert tuple(mod.decrypt_stored(b"\0" * 10)) == (None, "size")
    assert tuple(mod.encrypt_stored(b"\0" * 10)) == (None, "size")
    assert tuple(mod.decrypt_party(good, GEN4)) == (None, "size")  # right bytes, wrong declared length
    assert tuple(mod.decrypt_party(good, 0x88)) == (None, "party_len")
    assert tuple(mod.decrypt_party(good, 0xDD)) == (None, "party_len")
    assert tuple(mod.decrypt_party(good, float(0xDC))) == (None, "party_len")
    locked = bytearray(good[:0x88])
    locked[4] |= 0x01
    assert tuple(mod.decrypt_stored(bytes(locked))) == (None, "locked")
    for offset in (6, 8, 0x40, 0x87):
        bad = bytearray(good[:0x88])
        bad[offset] ^= 0x01
        assert tuple(mod.decrypt_stored(bytes(bad))) == (None, "checksum"), offset
        with pytest.raises(oracle.PkmError) as e:
            oracle.decrypt_stored(bytes(bad))
        assert e.value.reason == "checksum"
    for fn, args, why in (
        (oracle.decrypt_stored, (b"\0" * 10,), "size"),
        (oracle.decrypt_party, (good, GEN4), "size"),
        (oracle.decrypt_party, (good, 0x88), "party_len"),
    ):
        with pytest.raises(oracle.PkmError) as e:
            fn(*args)
        assert e.value.reason == why


def test_party_tail_is_pid_keyed_and_a_wrong_pid_is_not_a_box_checksum_failure(mod):
    """The checksum sums the shuffled body, so it cannot see a wrong PID: decrypt succeeds with scrambled
    blocks. Lua and the oracle must agree on exactly that behaviour (the PID is the caller's to trust)."""
    stored = oracle.encrypt_party(random_plain(random.Random(3), GEN5, 0x0002_0077), GEN5)
    bad = bytearray(stored)
    struct.pack_into("<I", bad, 0, 0x0004_0077)
    got, _ = mod.decrypt_party(bytes(bad), GEN5)
    assert lua_bytes(got) == oracle.decrypt_party(bytes(bad), GEN5)[0]
    assert lua_bytes(got) != oracle.decrypt_party(stored, GEN5)[0]


# -- controls: a mutated Lua module must diverge -------------------------------------------------------
def test_controls_mutated_lua_must_diverge_from_the_oracle():
    src = MODULE.read_text(encoding="utf-8")
    # row 3 is a 3-cycle (not its own inverse): a flipped shuffle direction cannot hide behind an involution
    plain = random_plain(random.Random(11), GEN5, (3 << 13) | 0x1357)
    raw = oracle.encrypt_party(plain, GEN5)
    want = oracle.decrypt_party(raw, GEN5)[0]
    mutations = {
        "shuffle row": ("% 24 + 1", "% 24 + 2"),
        "shuffle direction": ("if not to_stored then from, to = stored, logical end",
                              "if to_stored then from, to = stored, logical end"),
        "prng multiplier": ("seed * 0x41C64E6D", "seed * 0x41C64E6C"),
        "prng increment": ("+ 0x6073)", "+ 0x6074)"),
        "party tail seed": ("lcg_xor(tail, 0, info.pid)", "lcg_xor(tail, 0, 0)"),
        "checksum seed": ("lcg_xor(body, 0, stored_sum)", "lcg_xor(body, 0, 0)"),
    }
    _, ok = load_lua(src)
    assert lua_bytes(ok.decrypt_party(raw, GEN5)[0]) == want  # unmutated copy is green
    for name, (old, new) in mutations.items():
        assert src.count(old) == 1, f"mutation anchor for {name!r} drifted"
        _, bad = load_lua(src.replace(old, new))
        got = bad.decrypt_party(raw, GEN5)
        got = got[0] if isinstance(got, tuple) else got
        assert got is None or lua_bytes(got) != want, f"mutating the {name} did not break the decode"
    # the same direction flip must also break the Lua-only hand-computed layout pin (no worktree needed)
    _, flipped = load_lua(src.replace(*mutations["shuffle direction"]))
    pid = (3 << 13) | 0x123
    stored = lua_bytes(flipped.encrypt_stored(struct.pack("<IHH", pid, 0, 0) + b"".join(bytes([FILL[c]]) * 0x20 for c in "ABCD")))
    body = lcg_local(stored[8:], struct.unpack_from("<H", stored, 6)[0])
    assert "".join({v: k for k, v in FILL.items()}[body[s * 0x20]] for s in range(4)) != STORED_SEQUENCE[3]


def test_controls_the_flag_gates_are_load_bearing(rt):
    src = MODULE.read_text(encoding="utf-8")
    stored = oracle.encrypt_party(random_plain(random.Random(51), GEN5, (5 << 13) | 0x31), GEN5)
    locked = make_decrypted(stored, GEN5, bits=1)
    ok_lua, ok = load_lua(src)
    assert R(ok.decrypt_party(locked, GEN5)) == (None, "locked")
    gate = "local decrypted = flags & 0x3 ~= 0"
    clear = "b[5] = b[5] & 0xFC"
    assert src.count(gate) == 1 and src.count(clear) == 1, "mutation anchors drifted"
    _, no_gate = load_lua(src.replace(gate, "local decrypted = flags & 0x0 ~= 0"))
    assert R(no_gate.decrypt_party(locked, GEN5)) != (None, "locked")  # the gate gone: the marker is ignored
    plain_with_marker = make_decrypted(stored, GEN5, bits=3)
    got, _ = ok.decrypt_party(plain_with_marker, GEN5, ok_lua.table_from({"allow_decrypted": True}))
    assert struct.unpack_from("<H", lua_bytes(ok.encrypt_party(got, GEN5)), 4)[0] & 0x3 == 0
    nc_lua, no_clear = load_lua(src.replace(clear, "b[5] = b[5]"))
    got2, _ = no_clear.decrypt_party(plain_with_marker, GEN5, nc_lua.table_from({"allow_decrypted": True}))
    assert struct.unpack_from("<H", lua_bytes(no_clear.encrypt_party(got2, GEN5)), 4)[0] & 0x3 == 3


def test_module_loads_with_no_globals_leaked():
    lua = lupa.LuaRuntime()
    dump = lua.eval("function() local t = {} for k in pairs(_G) do t[#t + 1] = k end return t end")
    before = set(py(dump()))
    lua.eval("function(s) return assert(load(s, '=pkm45'))() end")(MODULE.read_text(encoding="utf-8"))
    assert set(py(dump())) == before


def test_module_has_no_engine_or_size_constants():
    lines = MODULE.read_text(encoding="utf-8").splitlines()
    src = chr(10).join(ln for ln in lines if not ln.lstrip().startswith("--"))
    for banned in ("memory.", "emu.", "client.", "PARTY_MON_SIZE", "0xEC", "0xDC"):
        assert banned not in src, banned
    # per-game field offsets (PK4 and PK5 differ here) must not appear in code: 0x41 / 0x42 / 0x85
    assert not re.search(r"\b0x(41|42|85)\b", src, re.IGNORECASE)


def test_public_api_is_exactly_the_documented_set_with_no_inert_exports(mod):
    assert set(py(mod).keys()) == {
        "shuffle_row", "block_order", "checksum", "decrypt_stored", "encrypt_stored", "decrypt_party",
        "encrypt_party", "pid", "tid", "sid", "otid", "mon_key",
    }


# -- Gen 4 vectors (independent decoder from the Gen 4 worktree) ---------------------------------------------
def load_gen4_codec():
    path = GEN4_WT / "server/adapters/gen4_codec.py"
    if not path.is_file():
        pytest.skip(f"Gen 4 oracle not found: {path} (override the worktree with SLINK_GEN4_WT)")
    spec = importlib.util.spec_from_file_location("_gen4_codec_ro", path)
    m = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = m  # dataclasses needs the module registered
    spec.loader.exec_module(m)
    return m


def build_plain(codec, pid: int, party: bool) -> bytes:
    """tests/unit/test_gen4_pk4_lua.py::build_plain (structure only: a plausible PK4 record)."""
    p = bytearray(codec.PARTY_MON_SIZE if party else codec.BOX_MON_SIZE)
    a, b, c, d = (8 + 0x20 * i for i in range(4))
    struct.pack_into("<IHH", p, 0, pid, 0, 0)
    struct.pack_into("<HHII", p, a, 250, 5, 0x1234_5678, 1_000_000)
    p[a + 0x0C : a + 0x10] = bytes((70, 0x2A, 3, 2))
    struct.pack_into("<4H", p, b, 33, 45, 52, 0)
    struct.pack_into("<I", p, b + 0x10, 0x8000_0000 | 0x1F | (7 << 5))
    struct.pack_into("<11H", p, c, *codec.encode_name("Lugi", 11))
    struct.pack_into("<8H", p, d, *codec.encode_name("RED", 8))
    if party:
        struct.pack_into("<IBBHHHHHHH", p, 0x88, 0, 50, 0, 100, 150, 90, 80, 70, 60, 50)
    return bytes(p)


@pytest.mark.parametrize("row", range(32))
def test_gen4_synthetic_vectors_every_shuffle_row(mod, row):
    codec = load_gen4_codec()
    pid = (0xABCD_0001 & ~0x3E000) | (row << 13)
    for party in (True, False):
        plain = build_plain(codec, pid, party)
        raw = (codec.encrypt_party if party else codec.encrypt_box)(plain)
        n = len(plain)
        assert (oracle.encrypt_party(plain, n) if party else oracle.encrypt_stored(plain)) == raw
        want = (codec.decrypt_party if party else codec.decrypt_box)(raw)
        got, _ = mod.decrypt_party(raw, n) if party else mod.decrypt_stored(raw)
        assert lua_bytes(got) == want
        assert lua_bytes(mod.encrypt_party(got, n) if party else mod.encrypt_stored(got)) == raw
        assert (mod.pid(got), mod.otid(got)) == (pid, 0x1234_5678)
        assert mod.mon_key(got) == codec.mon_key(pid, 0x1234_5678)


@pytest.mark.parametrize("which,default,profile", [
    ("hg", "Pokemon - HeartGold Version (USA).SaveRAM", "hgss"),
    ("ss", "Pokemon - SoulSilver Version (USA).SaveRAM", "hgss"),
    ("pt", "Pokemon - Platinum Version (USA).SaveRAM", "pt"),
])
def test_gen4_real_save_records(mod, which, default, profile):
    codec = load_gen4_codec()
    env = f"SLINK_GEN4_{which.upper()}_SAVE"
    path = Path(os.environ.get(env) or SAVE_DIR / default)
    if not path.is_file():
        pytest.skip(f"{which} battery save not found: {path} (override with {env})")
    save = codec.parse_save(path.read_bytes(), profile)
    p = save.profile
    recs = []
    _, cur = struct.unpack_from("<II", save.general, p.party_off)
    for i in range(cur):
        o = p.party_off + 8 + i * codec.PARTY_MON_SIZE
        recs.append((True, save.general[o : o + codec.PARTY_MON_SIZE]))
    for b in range(p.box_count):
        for s in range(30):
            o = p.boxes_off + b * p.box_stride + s * codec.BOX_MON_SIZE
            recs.append((False, save.pc[o : o + codec.BOX_MON_SIZE]))
    checked = 0
    for party, raw in recs:
        if codec.is_empty_slot(raw):
            continue
        want = (codec.decrypt_party if party else codec.decrypt_box)(raw)
        n = len(raw)
        got, _ = mod.decrypt_party(raw, n) if party else mod.decrypt_stored(raw)
        assert lua_bytes(got) == want
        assert lua_bytes(mod.encrypt_party(got, n) if party else mod.encrypt_stored(got)) == raw
        assert (oracle.decrypt_party(raw, n) if party else oracle.decrypt_stored(raw))[0] == want
        checked += 1
    assert checked, f"{which}: no populated slot to compare (the test would prove nothing)"


# -- the cartridges ---------------------------------------------------------------------------------------
@pytest.fixture(scope="module")
def arm9_of():
    why = (
        "package 'ndspy' is not installed (pip install ndspy); it is NOT declared in requirements-dev.txt, so the "
        "cartridge cross-check cases skip on a clean box; ROM directory env: SLINK_NDS_ROMS"
    )
    ndspy_rom = pytest.importorskip("ndspy.rom", reason=why)
    codeCompression = pytest.importorskip("ndspy.codeCompression", reason=why)
    cache: dict[str, bytes] = {}

    def get(name: str) -> bytes:
        fname, _ = ROMS[name]
        path = ROM_DIR / fname
        if not path.is_file():
            pytest.skip(f"{name} ROM not found: {path} (override the directory with SLINK_NDS_ROMS)")
        if name not in cache:
            rom = ndspy_rom.NintendoDSRom.fromFile(str(path))
            assert rom.arm9RamAddress == ARM9_RAM_BASE
            cache[name] = codeCompression.decompress(rom.arm9)
        return cache[name]

    return get


@pytest.mark.parametrize("name", sorted(ROMS))
def test_cartridge_block_offset_table_equals_ours(mod, arm9_of, name):
    arm9 = arm9_of(name)
    off = ROMS[name][1] - ARM9_RAM_BASE
    game = arm9[off : off + 128]
    assert len(game) == 128
    assert game == oracle.GAME_TABLE  # the oracle's generated table
    assert game == bytes(b for r in range(32) for b in py(mod.block_order(r << 13)))  # the Lua literal table
    # the games index it as table[sv * 4 + logical_block] -> stored byte offset (PML_PkmGetParamBlockCore)
    for sv in range(32):
        assert tuple(game[sv * 4 : sv * 4 + 4]) == tuple(py(mod.block_order(sv << 13)))


@pytest.mark.parametrize("name", sorted(ROMS))
def test_cartridge_arm9_contains_the_lcrng_multiplier(arm9_of, name):
    arm9 = arm9_of(name)
    lit = struct.pack("<I", 0x41C64E6D)
    hits = [i for i in range(0, len(arm9) - 3, 4) if arm9[i : i + 4] == lit]  # literal-pool words are aligned
    assert len(hits) >= 3, hits  # >= : crypto step, its ARM/duplicate copy, libc rand (rom_code_anchors.md 1.1: 3 today)
    # the 0x6073 increment follows the multiplier in the crypto step's pool (the other hit is libc rand 0x3039)
    assert any(struct.unpack_from("<I", arm9, h + 4)[0] == 0x6073 for h in hits)
