"""The Gen 4 server's HGSS gift set IS the generated pack's `gift_areas.ids`.

data/games/gen4_hgss/area_map.json is generated by tools/gen_gen4_area_map.py from the pinned
pret/pokeheartgold clone plus the pack's own acquisition.json (tools/gen_gen4_acquisition.py). Its
`rules.gift_areas` states the split this file pins: an id in `gift_areas.ids` is an area a scripted
starter/gift/egg/loan reaches where NO map in the area owns a wildEncounterBank, so a failed wild
encounter there is impossible; every candidate whose area DOES own a wild map is named in
`gift_areas.on_wild_area` instead. The generator refuses to emit an id that owns a wild map
(tools/gen_gen4_area_map.py check_gift_ids, :357-369).

Exempting a wild area is the failure mode, not a cosmetic one: the exemption suppresses that area's
no_catch (server/state.py:3053) and its capture quarantine (:2365), so a genuine KO disappears and
both players keep an encounter slot the run spent. The Gen 4 client already builds its own predicate
from this same list (lua/gen4/inputs.lua:117-138); these tests pin the server half so a pin bump
that moves an area across the split cannot leave the adapter behind.

data/games/gen4_hgss/encounters.json is a SECOND generated file, so the wild/non-wild fact is also
checked against the encounter banks rather than only against the block that claims it.
"""

import json
import logging
import os

import pytest

from server.adapters import gen4_hgsspt as gen4
from server.adapters.gen4_hgsspt import Gen4Adapter


def _pack(name: str) -> dict:
    with open(os.path.join(gen4._HGSS_PACK_DIR, name), encoding="utf-8") as f:
        return json.load(f)


AREA_MAP = _pack("area_map.json")
ENCOUNTERS = _pack("encounters.json")
PACK_AREAS = sorted(AREA_MAP["areas"])
PACK_GIFT_IDS = frozenset(AREA_MAP["gift_areas"]["ids"])
PACK_ON_WILD = frozenset(AREA_MAP["gift_areas"]["on_wild_area"].values())
# Every area a bank in encounters.json backs — the independent half of the split.
WILD_AREAS = frozenset(a for bank in ENCOUNTERS["banks"].values() for a in bank.get("areas", ()))

# Platinum (Sinnoh) has no generated pack, so its ids stay hand-typed in the adapter. Exactly one of
# them is also an HGSS area: pal_park (data/games/gen4_hgss/area_map.json owns it, and it is a real
# Pal Park in both games), which is the only Platinum id this file has to account for.
PLATINUM_IDS_IN_THE_HGSS_MAP = {"pal_park"}

# The areas the old hand-typed HGSS list called gift areas. Every one of them owns a wild-encounter
# map, and route_30 additionally has no acquisition site at all (no Mr. Pokémon in Johto: his house
# is in Violet City).
REGRESSED = ["route_30", "mt_mortar", "ilex_forest", "route_35", "dragons_den",
             "new_bark_town", "cianwood_city", "ruins_of_alph", "violet_city"]


@pytest.fixture
def adapter():
    return Gen4Adapter(rom_type="heartgold")


def _expected_gift(area_id: str) -> bool:
    return area_id in PACK_GIFT_IDS or area_id in PLATINUM_IDS_IN_THE_HGSS_MAP


def _parity_failures(adapter: Gen4Adapter) -> list[str]:
    """Areas of the pack's own map whose gift status the adapter gets wrong."""
    return [a for a in PACK_AREAS if adapter.is_gift_area(a) is not _expected_gift(a)]


def test_the_adapter_loaded_the_pack_not_a_fallback():
    """Guard: every other assertion here is vacuous if the module failed closed at import."""
    assert gen4._HGSS_GIFT_AREAS == PACK_GIFT_IDS
    assert PACK_GIFT_IDS


def test_every_mapped_area_matches_the_pack_gift_ids(adapter):
    assert _parity_failures(adapter) == []


def test_a_hand_typed_list_that_re_adds_a_wild_area_breaks_parity(adapter, monkeypatch):
    """The control: the pre-pack HGSS list called mt_mortar a gift area.

    Mt. Mortar backs four encounter banks (D22R0101, D38R0102/0103/0104 in encounters.json), so
    exempting the whole area would swallow a real no_catch on its grass. The parity check has to
    name it rather than pass.
    """
    assert "mt_mortar" in PACK_ON_WILD
    assert adapter.is_gift_area("mt_mortar") is False
    monkeypatch.setattr(gen4, "_GIFT_AREAS", gen4._GIFT_AREAS | {"mt_mortar"})
    assert _parity_failures(adapter) == ["mt_mortar"]


@pytest.mark.parametrize("area_id", sorted(PACK_ON_WILD))
def test_no_candidate_area_that_backs_wild_encounters_is_exempt(adapter, area_id):
    assert adapter.is_gift_area(area_id) is False


@pytest.mark.parametrize("area_id", REGRESSED)
def test_the_areas_the_old_list_exempted_are_not_gift_areas(adapter, area_id):
    assert adapter.is_gift_area(area_id) is False


@pytest.mark.parametrize("area_id", REGRESSED)
def test_each_of_those_areas_really_backs_a_wild_encounter_bank(area_id):
    """The other half of the same fact, from encounters.json instead of the area map's claim."""
    assert area_id in WILD_AREAS


def test_pack_gift_ids_are_disjoint_from_every_wild_encounter_area():
    """Independent proof from encounters.json that the four pack ids own no grass at all."""
    assert not PACK_GIFT_IDS & WILD_AREAS
    assert set(PACK_GIFT_IDS) == {"goldenrod_city", "pewter_city", "saffron_city", "sinjoh_ruins"}


# ── egg pickups ───────────────────────────────────────────────────────────

def test_violet_city_is_the_hgss_egg_pickup_and_route_30_is_not(adapter):
    # acquisition.json has exactly four `kind: "egg"` script sites and all four are violet_city:
    # Mr. Pokémon's Togepi on MAP_VIOLET_POKEMART (scr_seq_0858_T22FS0101:53) and Mareep, Wooper
    # and Slugma on MAP_VIOLET_POKECENTER_1F (scr_seq_0860_T22PC0101:79, :91, :103).
    assert adapter.is_egg_pickup_area("violet_city") is True
    # Mr. Pokémon's house is in Violet City; no acquisition site resolves into route_30.
    assert adapter.is_egg_pickup_area("route_30") is False
    # Kiyo's Tyrogue (mt_mortar) is `kind: "gift"` — a mon handed over, not an egg. The Spiky-eared
    # Pichu (ilex_forest) is `kind: "special_gift"`, likewise not an egg.
    assert adapter.is_egg_pickup_area("mt_mortar") is False
    assert adapter.is_egg_pickup_area("ilex_forest") is False


# ── the fail-closed loader ────────────────────────────────────────────────

def test_a_missing_pack_exempts_nothing(monkeypatch, tmp_path):
    monkeypatch.setattr(gen4, "_HGSS_PACK_DIR", str(tmp_path))
    assert gen4._load_hgss_gift_areas() == frozenset()


@pytest.mark.parametrize("body", [
    {"gift_areas": {"ids": ["goldenrod_city", 7]}},        # a non-string id
    {"gift_areas": {"ids": [""]}},                          # an empty id
    {"gift_areas": {"ids": "goldenrod_city"}},             # ids is not a list
    {"gift_areas": {}},                                    # no ids key at all
    {"areas": {}},                                         # no gift_areas block at all
])
def test_a_malformed_block_exempts_nothing_and_says_so(monkeypatch, tmp_path, caplog, body):
    (tmp_path / "area_map.json").write_text(json.dumps(body), encoding="utf-8")
    monkeypatch.setattr(gen4, "_HGSS_PACK_DIR", str(tmp_path))
    with caplog.at_level(logging.ERROR):
        assert gen4._load_hgss_gift_areas() == frozenset()
    assert any("no HGSS area is exempt" in r.getMessage() for r in caplog.records), caplog.records


def test_unreadable_json_exempts_nothing_and_says_so(monkeypatch, tmp_path, caplog):
    (tmp_path / "area_map.json").write_text("{not json", encoding="utf-8")
    monkeypatch.setattr(gen4, "_HGSS_PACK_DIR", str(tmp_path))
    with caplog.at_level(logging.ERROR):
        assert gen4._load_hgss_gift_areas() == frozenset()
    assert any("no usable HGSS gift-area pack" in r.getMessage() for r in caplog.records)


def test_an_id_the_pack_itself_lists_on_a_wild_area_is_dropped(monkeypatch, tmp_path, caplog):
    """A contradiction between two halves of one file is a reason to refuse that id, not to trust it."""
    (tmp_path / "area_map.json").write_text(json.dumps({"gift_areas": {
        "ids": ["goldenrod_city", "mt_mortar"],
        "on_wild_area": {"252": "mt_mortar"},
    }}), encoding="utf-8")
    monkeypatch.setattr(gen4, "_HGSS_PACK_DIR", str(tmp_path))
    with caplog.at_level(logging.ERROR):
        assert gen4._load_hgss_gift_areas() == frozenset({"goldenrod_city"})
    assert any("covers wild-encounter areas" in r.getMessage() for r in caplog.records)
