"""
Regression tests for the BizHawk launcher Lua file generated by the Run Manager.

The launcher is a small Lua bootstrap that BizHawk's Lua Console loads.  It
auto-detects the SLink project root by scanning upward from its own directory.
Any Lua-parse error here makes the file silently fail to load in BizHawk, so
we validate it parses cleanly under a real Lua runtime (Lua 5.4 via lupa,
matching BizHawk's embedded Lua).
"""
import pytest

from server.manager import _build_launcher

lupa = pytest.importorskip("lupa")

RUN = {"run_id": "rid-test", "name": "Trial Run", "tcp_port": 54321}


def _parse(src: str) -> None:
    """Raise if the Lua source fails to parse under Lua 5.4."""
    L = lupa.LuaRuntime(unpack_returned_tuples=True)
    L.execute("local f, err = load(...); if not f then error(err) end", src)


@pytest.mark.parametrize("player", ["a", "b"])
def test_launcher_parses_as_valid_lua(player):
    """Regression for the `\\/` invalid-escape that broke loading in BizHawk."""
    _parse(_build_launcher(RUN, player, "127.0.0.1"))


def test_launcher_path_match_handles_both_separators():
    """The auto-detect pattern must capture the trailing dir on Windows and Unix paths."""
    L = lupa.LuaRuntime(unpack_returned_tuples=True)
    L.execute(r"""
function extract_dir(s)
    return s:match("@(.+[\\/])")
end
""")
    extract = L.globals().extract_dir
    assert extract(r"@C:\Users\foo\Downloads\slink_a.lua") == "C:\\Users\\foo\\Downloads\\"
    assert extract("@/home/foo/Downloads/slink_a.lua") == "/home/foo/Downloads/"


def test_launcher_embeds_connect_params():
    src = _build_launcher(RUN, "a", "192.168.1.10")
    assert 'SLINK_HOST   = "192.168.1.10"' in src
    assert "SLINK_PORT   = 54321" in src
    assert 'SLINK_PLAYER = "a"' in src
